In [7]:
import pandas as pd

path = r"C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\(Clone) out\out_archiv\Nano Family\docling_chunks.jsonl"

import json

with open(path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f, start=1):
        line=line.strip()
        if not line:
            print(f"⚠️ Empty line at {i}")
            continue
        try:
            json.loads(line)
        except Exception as e:
            print(f"❌ Error in line {i}: {e} -> {line}")

import pandas as pd


df = pd.read_json(path, lines=True)
df.head()

,file_name,chunk_id,chunk_size,semantic_density,product_category,product,section,text
0,Nano 33 IoT-datasheet.pdf,Nano 33 IoT-datasheet::c0,110,0.2552,Nano Family,Nano 33 IoT,NaN,"[Product: Nano 33 IoT] [Product category: Nano Family] [Element of Nano 33 IoT: None] [Tutorial about Nano 33 IoT: None] \n\nDescription\nThe Arduino® Nano 33 IoT and Arduino Nano 33 IoT with headers are a miniature sized module containing a Cortex M0+ SAMD21 processor, a Wi-Fi® + Bluetooth® module based on ESP32, a crypto chip which can securely store certificates and pre-shared keys and a 6 axis IMU. The module can either be mounted as a DIP component (when mounting pin headers), or as a SMT component, directly soldering it via the castellated pads."
1,Nano 33 IoT-datasheet.pdf,Nano 33 IoT-datasheet::c2,151,0.2882,Nano Family,Nano 33 IoT,NaN,"[Product: Nano 33 IoT] [Product category: Nano Family] [Element of Nano 33 IoT: None] [Tutorial about Nano 33 IoT: None] \n\nFeatures\n- SAMD21G18A\n- Processor\n- 256 kB Flash\n- 32 kB Flash\n- Power On Reset (POR) and Brown Out Detection (BOD)\n- Peripherals\n- 12 channel DMA\n- 12 channel event system\n- 5x 16 bit Timer/Counter\n- 3x 24 bit timer/counter with extended functions\n- 32 bit RTC\n- Watchdog Time\n- CRC-32 generator\n- Full speed Host/Device USB with 8 end points\n- 6x SERCOM (USART, I 2 C, SPI, LIN)\n- Two channel I 2 S\n- 12 bit 350ksps ADC (up to 16 bit with oversampling)\n- 10 bit 350ksps DAC\n- External Interrupt Controller (up to 16 lines)"
2,Nano 33 IoT-datasheet.pdf,Nano 33 IoT-datasheet::c4,48,0.3556,Nano Family,Nano 33 IoT,NaN,"[Product: Nano 33 IoT] [Product category: Nano Family] [Element of Nano 33 IoT: None] [Tutorial about Nano 33 IoT: None] \n\nWi-Fi®\n- IEEE 802.11b up to 11Mbit\n- IEEE 802.11g up to 54MBit\n- IEEE 802.11n up to 72MBit\n- 2.4 GHz, 13 channels\n- -96 dBm sensitivity"
3,Nano 33 IoT-datasheet.pdf,Nano 33 IoT-datasheet::c5,63,0.3889,Nano Family,Nano 33 IoT,NaN,"[Product: Nano 33 IoT] [Product category: Nano Family] [Element of Nano 33 IoT: None] [Tutorial about Nano 33 IoT: None] \n\nBluetooth® BR/EDR\n- Max 7 peripherals\n- 2.4 GHz, 79 channels\n- Up to 3 Mbit/s\n- 8 dBm output power at 2/3 Mbit/s\n- 11 dBm EIRP at 2/3 Mbit/s\n- -88 dBm sensitivity"
4,Nano 33 IoT-datasheet.pdf,Nano 33 IoT-datasheet::c6,48,0.3404,Nano Family,Nano 33 IoT,NaN,[Product: Nano 33 IoT] [Product category: Nano Family] [Element of Nano 33 IoT: None] [Tutorial about Nano 33 IoT: None] \n\nBluetooth® Low Energy\n- Bluetooth® 4.2 dual mode\n- 2.4GHz 40 channels\n- 6 dBm output power\n- 9 dBm EIRP\n- -88 dBm sensitivity\n- Up to 1 Mbit/

In [8]:
pd.set_option("display.max_colwidth", None)

filtered = df[df["chunk_id"].str.contains("datasheet", case=False, na=False)]

filtered = filtered[filtered["product"].str.contains("Nano 33 BLE Rev2", case=False, na=False)]

# Nur product und text anzeigen
filtered[["product", "text"]]

,product,text
147,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\nDescription\nThe Arduino® Nano 33 BLE Rev2 * is a miniature-sized module containing a NINA B306 module, based on Nordic nRF52480 and containing an Arm® Cortex®-M4F. The BMI270 and BMM150 jointly provide a 9-axis IMU. The module can either be mounted as a DIP component (when mounting pin headers) or as a SMT component, directly soldering it via the castellated pads.\n*Nano 33 BLE Rev2 product has two SKUs:\n- Without headers (ABX00071)\n- With headers (ABX00072)"
148,Nano 33 BLE Rev2,[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\nFeatures\n- NINA B306 Module\n- Processor\n- 64 MHz Arm® Cortex®-M4F (with FPU)\n- 1 MB Flash + 256 kB RAM\n- Bluetooth® 5 multiprotocol radio\n- 2 Mbps\n- Advertising Extensions\n- Long Range\n- +8 dBm TX power\n- -95 dBm sensitivity\n- 4.8 mA in TX (0 dBm)\n- 4.6 mA in RX (1 Mbps)\n- Integrated balun with 50 Ω single-ended output\n- IEEE 802.15.4 radio support\n- Thread\n- Zigbee®\n- Peripherals\n- Full-speed 12 Mbps USB\n- NFC-A tag\n- Arm® CryptoCell CC310 security subsystem\n- QSPI/SPI/TWI/I²S/PDM/QDEC\n- High speed 32 MHz SPI\n- Quad SPI interface 32 MHz\n- EasyDMA for all digital interfaces\n- 12-bit 200 ksps ADC\n- 128 bit AES/ECB/CCM/AAR co-processor\n- BMI270 6-axis IMU (Accelerometer and Gyroscope)\n- 3-axis accelerometer with ±2g/±4g/±8g/±16g range\n- 3-axis gyroscope with ±125dps/±250dps/±500dps/±1000dps/±2000dps range\n- BMM150 3-axis IMU (Magnetometer)\n- 3-axis digital geomagnetic sensor\n- 0.3μT resolution\n- MP2322 DC-DC\n- Regulates input voltage from up to 21V with a minimum of 65% efficiency @minimum load\n- More than 85% efficiency @12V
149,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n1 The Board\n1.1 Ratings, 1 = 4. 1.1.1 Recommended Operating Conditions, 1 = 4. 1.2 Power Consumption, 1 = 4. 2 Functional Overview, 1 = 5. 2.1 Board Topology, 1 = 5. 2.2 Processor, 1 = 6. 2.3 IMU, 1 = 6. 2.4 Power Tree, 1 = 6. 2.5 Block Diagram, 1 = 7. 3 Board Operation, 1 = 8. 3.1 Getting Started - IDE, 1 = 8. 3.2 Getting Started - Arduino Cloud Editor, 1 = 8. 3.3 Getting Started - Arduino Cloud, 1 = 8. 3.4 Sample Sketches, 1 = 8. 3.5 Online Resources, 1 = 8. 3.6 Board Recovery, 1 = 9. 4 Connector Pinouts, 1 = 9. 4.1 USB, 1 = 10. 4.2 Headers, 1 = 10. 4.3 Debug, 1 = 11. 5 Mechanical Information, 1 = 11. 5.1 Board Outline and Mounting Holes, 1 = 11. 6 Certifications, 1 = 12. 6.1 Declaration of Conformity CE DoC (EU), 1 = 12. 6.2 Declaration of Conformity to EU RoHS & REACH 211 01/19/2021, 1 = 12. 6.3 Conflict Minerals Declaration, 1 = 13. 7 FCC Caution, 1 = 13. 8 Company Information, 1 = 14. 9 Reference Documentation, 1 = 14. 10 Revision History, 1 = 15\nAs all Nano form factor boards, Nano 33 BLE Rev2 does not have a battery charger but can be powered through USB or headers.\nNOTE: Nano 33 BLE Rev2 only supports 3.3 V I/Os and is NOT 5V tolerant so please make sure you are not directly connecting 5 V signals to this board or it will be damaged. Also, as opposed to other Arduino Nano boards that support 5 V operation, the 5V pin does NOT supply voltage but is rather connected, through a jumper, to the USB power input."
150,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n1.1.1 Recommended Operating Conditions\n, Description = Conservative thermal limits for the whole board:. , Min = -40 °C ( 40 °F). , Max = 85 °C ( 185 °F)"
151,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n1.2 Power Consumption\nPBL, Description = Power consumption with busy loop. PBL, Min = . PBL, Typ = TBC. PBL, Max = . PBL, Unit = mW. PLP, Description = Power consumption in low power mode. PLP, Min = . PLP, Typ = TBC. PLP, Max = . PLP, Unit = mW. PMAX, Description = Maximum Power Consumption. PMAX, Min = . PMAX, Typ = TBC. PMAX, Max = . PMAX, Unit = mW"
152,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\nTop:\nBoard topology top\nU1, Description = NINA-B306 Module Bluetooth® Low Energy 5.0 Module. U1, Ref. = U6. U1, Description = MP2322GQH Step Down Converter. U2, Description = BMI270 Sensor IMU. U2, Ref. = PB1. U2, Description = IT-1185AP1C-160G-GTR Push button. U7, Description = BMM150 Magnetometer IC. U7, Ref. = DL1. U7, Description = Led L. SJ5, Description = VUSB Jumper. SJ5, Ref. = . SJ5, Description ="
153,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\nBottom:\nBoard topology bot\nSJ1, Description = VUSB Jumper. SJ1, Ref. = SJ2. SJ1, Description = D7 Jumper. SJ3, Description = 3v3 Jumper. SJ3, Ref. = SJ4. SJ3, Description = D8 Jumper"
154,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n2.2 Processor\nThe Main Processor is an Arm® Cortex®-M4F running at up to 64 MHz. Most of its pins are connected to the external headers however some are reserved for internal communication with the wireless module and the onboard internal I 2 C peripherals (IMU and Crypto).\nNOTE : As opposed to other Arduino Nano boards, pins A4 and A5 have an internal pull-up and default to be used as an I 2 C Bus so usage as analog inputs is not recommended."
155,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n2.3 IMU\nNano 33 BLE Rev2 provides IMU capabilities with 9-axis, through a combination of the BMI270 and BMM150 ICs. The BMI270 includes both a three-axis gyroscope as well as a three-axis accelerometer, while the BMM150 is capable of sensing magnetic field variations in all three dimensions. The information obtained can be used for measuring raw movement parameters as well as for machine learning."
156,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n2.4 Power Tree\nThe board can be powered via USB connector, V IN or V USB pins on headers.\nPower tree\nNOTE: Since V USB feeds V IN via a Schottky diode and a DC-DC regulator specified minimum input voltage is 4.5 V the minimum supply voltage from USB has to be increased to a voltage in the range between 4.8 V to 4.96 V depending on the current being drawn."
157,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n3.1 Getting Started - IDE\nIf you want to program your Nano 33 BLE Rev2 while offline you need to install the Arduino Desktop IDE [1] To connect the Nano 33 BLE Rev2 to your computer, you'll need a Micro-B USB cable. This also provides power to the board, as indicated by the LED."
158,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n3.2 Getting Started - Arduino Cloud Editor\nAll Arduino boards, including this one, work out-of-the-box on the Arduino Cloud Editor [2], by just installing a simple plugin.\nThe Arduino Cloud Editor is hosted online, therefore it will always be up-to-date with the latest features and support for all boards. Follow [3] to start coding on the browser and upload your sketches onto your board."
159,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n3.3 Getting Started - Arduino Cloud\nAll Arduino IoT-enabled products are supported on Arduino Cloud which allows you to log, graph and analyze sensor data, trigger events, and automate your home or business."
160,Nano 33 BLE Rev2,[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n3.4 Sample Sketches\nSample sketches for the Nano 33 BLE Sense can be found either in the 'Examples' menu in the Arduino IDE or in the 'Built-in Examples' section of the Arduino Docs website.
161,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n3.5 Online Resources\nNow that you have gone through the basics of what you can do with the board you can explore the endless possibilities it provides by checking exciting projects on Arduino Project Hub [4], the Arduino Library Reference [5] and the online store where you will be able to complement your board with sensors, actuators and more."
162,Nano 33 BLE Rev2,[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n3.6 Board Recovery\nAll Arduino boards have a built-in bootloader which allows flashing the board via USB. In case a sketch locks up the processor and the board is not reachable anymore via USB it is possible to enter bootloader mode by doubletapping the reset button right after powering up the board.
163,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n4.1 USB\n1, Function = VUSB. 1, Type = Power. 1, Description = Power Supply Input. If board is powered via VUSB from header this is an Output (1). 2, Function = D-. 2, Type = Differential. 2, Description = USB differential data -. 3, Function = D+. 3, Type = Differential. 3, Description = USB differential data +. 4, Function = ID. 4, Type = Analog. 4, Description = Selects Host/Device functionality. 5, Function = GND. 5, Type = Power. 5, Description = Power Ground"
164,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n4.2 Headers\n1, Function = D13. 1, Type = Digital. 1, Description = GPIO. 2, Function = +3V3. 2, Type = Power Out. 2, Description = Internally generated power output to external devices. 3, Function = AREF. 3, Type = Analog. 3, Description = Analog Reference; can be used as GPIO. 4, Function = A0/DAC0. 4, Type = Analog. 4, Description = ADC in/DAC out; can be used as GPIO. 5, Function = A1. 5, Type = Analog. 5, Description = ADC in; can be used as GPIO. 6, Function = A2. 6, Type = Analog. 6, Description = ADC in; can be used as GPIO. 7, Function = A3. 7, Type = Analog. 7, Description = ADC in; can be used as GPIO. 8, Function = A4/SDA. 8, Type = Analog. 8, Description = ADC in; I2C SDA; Can be used as GPIO (1). 9, Function = A5/SCL. 9, Type = Analog. 9, Description = ADC in; I2C SCL; Can be used as GPIO (1). 10, Function = A6. 10, Type = Analog. 10, Description = ADC in; can be used as GPIO. 11, Function = A7. 11, Type = Analog. 11, Description = ADC in; can be used as GPIO. 12, Function = VUSB. 12, Type = Power In/Out. 12, Description = Normally NC; can be connected to VUSB pin of the USB connector by shorting a jumper. 13, Function = RST. 13, Type = Digital In. 13, Description = Active low reset input (duplicate of pin 18). 14, Function = GND. 14, Type = Power. 14, Description = Power Ground. 15, Function = VIN. 15, Type = Power In. 15, Description = Vin Power input. 16, Function = TX. 16, Type = Digital. 16, Description = USART TX; can be used as GPIO. 17, Function = RX. 17, Type = Digital. 17, Description = USART RX; can be used as GPIO. 18, Function = RST. 18, Type = Digital. 18, Description = Active low reset input (duplicate of pin 13). 19, Function = GND. 19, Type = Power. 19, Description = Power Ground. 20, Function = D2. 20, Type = Digital. 20, Description = GPIO. 21, Function = D3/PWM. 21, Type = Digital. 21, Description = GPIO; can be used asPWM. 22, Function = D4. 22, Type = Digital. 22, Description = GPIO. 23, Function = D5/PWM. 23, Type = Digital. 23, Description = GPIO; can be used asPWM. 24, Function = D6/PWM. 24, Type = Digital. 24, Description = GPIO, can be used asPWM. 25, Function = D7. 25, Type = Digital. 25, Description = GPIO. 26, Function = D8. 26, Type = Digital. 26, Description = GPIO. 27, Function = D9/PWM. 27, Type = Digital. 27, Description = GPIO; can be used asPWM. 28, Function = D10/PWM. 28, Type = Digital. 28, Description = GPIO; can be used asPWM. 29, Function = D11/MOSI. 29, Type = Digital."
165,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n4.2 Headers\n29, Description = SPI MOSI; can be used as GPIO\nPin, 1 = Function. Pin, 2 = Type. Pin, 3 = Description. 30, 1 = D12/MISO. 30, 2 = Digital. 30, 3 = SPI MISO; can be used as GPIO"
166,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n4.3 Debug\nOn the bottom side of the board, under the communication module, debug signals are arranged as 3x2 test pads with 100 mil pitch with pin 4 removed. Pin 1 is depicted in Figure 3 - Connector Positions\n1, Function = +3V3. 1, Type = Power Out. 1, Description = Internally generated power output to be used as voltage reference. 2, Function = SWD. 2, Type = Digital. 2, Description = nRF52480 Single Wire Debug Data. 3, Function = SWCLK. 3, Type = Digital In. 3, Description = nRF52480 Single Wire Debug Clock. 5, Function = GND. 5, Type = Power. 5, Description = Power Ground. 6, Function = RST. 6, Type = Digital In. 6, Description = Active low reset input"
167,Nano 33 BLE Rev2,[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n5.1 Board Outline and Mounting Holes\nThe board measures are mixed between metric and imperial. Imperial measures are used to maintain a 100 mil pitch grid between pin rows to allow them to fit a breadboard whereas board length is Metric.\nBoard layout
168,Nano 33 BLE Rev2,[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n6.1 Declaration of Conformity CE DoC (EU)\nWe declare under our sole responsibility that the products above conform with the essential requirements of the following EU Directives and therefore qualify for free movement within markets comprising the European Union (EU) and European Economic Area (EEA).
169,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n6.2 Declaration of Conformity to EU RoHS & REACH 211 01/19/2021\nArduino boards are in compliance with RoHS 2 Directive 2011/65/EU of the European Parliament and RoHS 3 Directive 2015/863/EU of the Council of 4 June 2015 on the restriction of the use of certain hazardous substances in electrical and electronic equipment.\nLead (Pb), Maximum limit (ppm) = 1000. Cadmium (Cd), Maximum limit (ppm) = 100. Mercury (Hg), Maximum limit (ppm) = 1000. Hexavalent Chromium (Cr6+), Maximum limit (ppm) = 1000. Poly Brominated Biphenyls (PBB), Maximum limit (ppm) = 1000. Poly Brominated Diphenyl ethers (PBDE), Maximum limit (ppm) = 1000. Bis(2-Ethylhexyl} phthalate (DEHP), Maximum limit (ppm) = 1000. Benzyl butyl phthalate (BBP), Maximum limit (ppm) = 1000. Dibutyl phthalate (DBP), Maximum limit (ppm) = 1000. Diisobutyl phthalate (DIBP), Maximum limit (ppm) = 1000\nExemptions: No exemptions are claimed.\nArduino boards are fully compliant with the related requirements of European Union Regulation (EC) 1907 /2006 concerning the Registration, Evaluation, Authorization and Restriction of Chemicals (REACH). We declare none of the SVHCs (https://echa.europa.eu/web/guest/candidate-list-table), the Candidate List of Substances of Very High Concern for authorization currently released by ECHA, is present in all products (and also package) in quantities totaling in a concentration equal or above 0.1%. To the best of our knowledge, we also declare that our products do not contain any of the substances listed on the ""Authorization List"" (Annex XIV of the REACH regulations) and Substances of Very High Concern (SVHC) in any significant amounts as specified by the Annex XVII of Candidate list published by ECHA (European Chemical Agency) 1907 /2006/EC."
170,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n6.3 Conflict Minerals Declaration\nAs a global supplier of electronic and electrical components, Arduino is aware of our obligations with regard to laws and regulations regarding Conflict Minerals, specifically the Dodd-Frank Wall Street Reform and Consumer Protection Act, Section 1502. Arduino does not directly source or process conflict minerals such as Tin, Tantalum, Tungsten, or Gold. Conflict minerals are contained in our products in the form of solder or as a component in metal alloys. As part of our reasonable due diligence, Arduino has contacted component suppliers within our supply chain to verify their continued compliance with the regulations. Based on the information received thus far we declare that our products contain Conflict Minerals sourced from conflict-free areas."
171,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\n7 FCC Caution\nAny Changes or modifications not expressly approved by the party responsible for compliance could void the user's authority to operate the equipment.\nThis device complies with part 15 of the FCC Rules. Operation is subject to the following two conditions:\n- (1) This device may not cause harmful interference\n- (2) this device must accept any interference received, including interference that may cause undesired operation."
172,Nano 33 BLE Rev2,"[Product: Nano 33 BLE Rev2] [Product category: Nano Family] [Element of Nano 33 BLE Rev2: None] [Tutorial about Nano 33 BLE Rev2: None] \n\nFCC RF Radiation Exposure Statement:\n1. This Transmitter must not be co-located or operating in conjunction with any other antenna or transmitter.\n2. This equipment complies with RF radiation exposure limits set forth for an uncontrolled environment.\n3. This equipment should be installed and operated with a minimum distance of 20cm between the radiator & your body.\nEnglish: User manuals for license-exempt radio apparatus shall contain the following or equivalent notice in a conspicuous location in the user manual, alternatively on the device or both. This device complies with Industry Canada license-exempt RSS standard(s). Operation is subject to the following two conditions:\n- (1) this device may not cause interference\n- (2) this device must accept any interference, including interference that may cause undesired operation of the device.\nFrench: Le présent appareil est conforme aux CNR d'Industrie Canada applicables aux appareils radio exempts de licence. L'exploitation est autorisée aux deux conditions suivantes :\n- (1) l' appareil nedoit pas produire de brouillage\n- (2) l'utilisateur de l'appareil doit accepter tout brouillage radioélectrique subi, même si le brouillage est susceptible d'en compromettre le fonctionnement."

In [6]:

from pathlib import Path
import pandas as pd
BASE_DIR = r"C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\out_aktuell\Mega\docling_chunks.jsonl"

df = pd.read_json(BASE_DIR, lines=True)
df.head()

,file_name,chunk_id,chunk_size,semantic_density,product_category,product,section,text
0,Due-datasheet.pdf,Due-datasheet::c0,139,0.2384,Mega,Due,NaN,[Product: Due] [Product category: Mega] [Eleme...
1,Due-datasheet.pdf,Due-datasheet::c9,548,0.2010,Mega,Due,NaN,[Product: Due] [Product category: Mega] [Eleme...
2,Due-datasheet.pdf,Due-datasheet::c10,409,0.2661,Mega,Due,NaN,[Product: Due] [Product category: Mega] [Eleme...
3,Due-datasheet.pdf,Due-datasheet::c11,57,0.2984,Mega,Due,NaN,[Product: Due] [Product category: Mega] [Eleme...
4,Due-datasheet.pdf,Due-datasheet::c16,251,0.3476,Mega,Due,NaN,[Product: Due] [Product category: Mega] [Eleme...

In [7]:
df["product"].unique()

array(['Due', 'GIGA Display Shield', 'Mega 2560 Rev3', 'GIGA R1 WiFi'],
      dtype=object)

In [5]:
import pandas as pd
BASE_DIR_2 = r"C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\out_aktuell\Mega Tutorial\docling_chunks.jsonl"

df2 = pd.read_json(BASE_DIR_2, lines=True)
df2.head()

,file_name,chunk_id,chunk_size,semantic_density,product_category,product,section,tutorial,element,text
0,Tutorial_Due_Keyboard Controller.pdf,Tutorial_Due_Keyboard Controller::c0,NaN,NaN,Mega,Due,NaN,Tutorial_Due,NaN,[Product: Due] [Product category: Mega] [Eleme...
1,Tutorial_Due_Keyboard Controller.pdf,Tutorial_Due_Keyboard Controller::c1,NaN,NaN,Mega,Due,NaN,Tutorial_Due,NaN,[Product: Due] [Product category: Mega] [Eleme...
2,Tutorial_Due_Mouse Controller.pdf,Tutorial_Due_Mouse Controller::c0,NaN,NaN,Mega,Due,NaN,Tutorial_Due,NaN,[Product: Due] [Product category: Mega] [Eleme...
3,Tutorial_Due_Mouse Controller.pdf,Tutorial_Due_Mouse Controller::c1,NaN,NaN,Mega,Due,NaN,Tutorial_Due,NaN,[Product: Due] [Product category: Mega] [Eleme...
4,Tutorial_Due_Mouse Controller.pdf,Tutorial_Due_Mouse Controller::c2,NaN,NaN,Mega,Due,NaN,Tutorial_Due,NaN,[Product: Due] [Product category: Mega] [Eleme...