In [1]:
import os
import json
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

from langchain_community.graphs.neo4j_graph import Neo4jGraph
from langchain_experimental.graph_transformers.llm import LLMGraphTransformer
from langchain_community.graphs.graph_document import Node, Relationship
from langchain_core.documents.base import Document
from langchain_community.chat_models import ChatLlamaCpp
from langchain_community.embeddings import HuggingFaceEmbeddings

In [2]:
from dotenv import load_dotenv
load_dotenv()
import os
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.graphs.neo4j_graph import Neo4jGraph
from langchain_community.vectorstores.neo4j_vector import Neo4jVector
from langchain.chains.combine_documents  import create_stuff_documents_chain
from langchain.chains.retrieval import create_retrieval_chain
from langchain_core.prompts.chat import ChatPromptTemplate
from langchain_community.chat_models import ChatLlamaCpp

ModuleNotFoundError: No module named 'langchain.chains'

In [2]:
from main.evaluation.logger import log_antwort

ModuleNotFoundError: No module named 'main'

In [ ]:
import sys; print(sys.executable); print(sys.version)

c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Scripts\python.exe
3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)]

In [ ]:
!pip show langchain

Name: langchain
Version: 1.0.5
Summary: Building applications with LLMs through composability
Home-page:
Author:
Author-email:
License: MIT
Location: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv_Python11\Lib\site-packages
Requires: langchain-core, langgraph, pydantic
Required-by:

In [8]:
!pip show  llama-cpp-python

Name: llama_cpp_python
Version: 0.3.16
Summary: Python bindings for the llama.cpp library
Home-page:
Author:
Author-email: Andrei Betlen <abetlen@gmail.com>
License: MIT
Location: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv_Python11\Lib\site-packages
Requires: diskcache, jinja2, numpy, typing-extensions
Required-by:

In [7]:
!pip show langchain
!pip show langchain_experimental
!pip show langchain_community
!pip show -U langchain langchain-core langchain-community langchain-experimental
!pip show langchain-core
!pip show pydantic
!pip show langgraph
!pip show json-repair
!pip show --no-cache-dir -U llama-cpp-python
!pip show langchain-neo4j
!pip show -U neo4j langchain-neo4j
!pip show pandas

Name: langchain
Version: 1.0.5
Summary: Building applications with LLMs through composability
Home-page:
Author:
Author-email:
License: MIT
Location: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv_Python11\Lib\site-packages
Requires: langchain-core, langgraph, pydantic
Required-by:
Name: langchain-experimental
Version: 0.4.0
Summary: Building applications with LLMs through composability
Home-page:
Author:
Author-email:
License: MIT
Location: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv_Python11\Lib\site-packages
Requires: langchain-community, langchain-core
Required-by:
Name: langchain-community
Version: 0.4.1
Summary: Community contributed LangChain integrations.
Home-page:
Author:
Author-email:
License: MIT
Location: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv_Python11\Lib\site-packages
Requires: aiohttp, dataclasses-json, httpx-sse, langchain-classic, langchain-core, langsmith, numpy, pydantic-settings, PyYAML, requests, SQLAlchemy, tenacity
Required-by: langchain-experimental

Usage:
  pip show [options] <package> ...

no such option: -U

Name: langchain-core
Version: 1.0.4
Summary: Building applications with LLMs through composability
Home-page:
Author:
Author-email:
License: MIT
Location: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv_Python11\Lib\site-packages
Requires: jsonpatch, langsmith, packaging, pydantic, pyyaml, tenacity, typing-extensions
Required-by: langchain, langchain-classic, langchain-community, langchain-experimental, langchain-neo4j, langchain-text-splitters, langgraph, langgraph-checkpoint, langgraph-prebuilt
Name: pydantic
Version: 2.12.4
Summary: Data validation using Python type hints
Home-page:
Author:
Author-email: Samuel Colvin <s@muelcolvin.com>, Eric Jolibois <em.jolibois@gmail.com>, Hasan Ramezani <hasan.r67@gmail.com>, Adrian Garcia Badaracco <1755071+adriangb@users.noreply.github.com>, Terrence Dorsey <terry@pydantic.dev>, David Montague <david@pydantic.dev>, Serge Matveenko <lig@countzero.co>, Marcelo Trylesinski <marcelotryle@gmail.com>, Sydney Runkle <sydneymarierunkle@gmail.com>, David Hewitt <mail@davidhewitt.io>, Alex Hall <alex.mojaki@gmail.com>, Victorien Plot <contact@vctrn.dev>, Douwe Maan <hi@douwe.me>
License:
Location: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv_Python11\Lib\site-packages
Requires: annotated-types, pydantic-core, typing-extensions, typing-inspection
Required-by: langchain, langchain-classic, langchain-core, langgraph, langsmith, neo4j-graphrag, pydantic-settings
Name: langgraph
Version: 1.0.3
Summary: Building stateful, multi-actor applications with LLMs
Home-page:
Author:
Author-email:
License:
Location: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv_Python11\Lib\site-packages
Requires: langchain-core, langgraph-checkpoint, langgraph-prebuilt, langgraph-sdk, pydantic, xxhash
Required-by: langchain
Name: json_repair
Version: 0.44.1
Summary: A package to repair broken json strings
Home-page:
Author:
Author-email: Stefano Baccianella <4247706+mangiucugna@users.noreply.github.com>
License: MIT License

Copyright (c) 2023 Stefano Baccianella

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Location: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv_Python11\Lib\site-packages
Requires:
Required-by: neo4j-graphrag

Usage:
  pip show [options] <package> ...

no such option: -U

Name: langchain-neo4j
Version: 0.6.0
Summary: An integration package connecting Neo4j and LangChain
Home-page: https://github.com/langchain-ai/langchain-neo4j
Author:
Author-email:
License: MIT
Location: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv_Python11\Lib\site-packages
Requires: langchain-classic, langchain-core, neo4j, neo4j-graphrag
Required-by:

Usage:
  pip show [options] <package> ...

no such option: -U

Name: pandas
Version: 2.3.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page:
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2023, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Location: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv_Python11\Lib\site-packages
Requires: numpy, python-dateutil, pytz, tzdata
Required-by:

In [11]:
!pip show langchain langchain-core pydantic

Name: langchain
Version: 0.3.27
Summary: Building applications with LLMs through composability
Home-page:
Author:
Author-email:
License: MIT
Location: C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages
Requires: langchain-core, langchain-text-splitters, langsmith, pydantic, PyYAML, requests, SQLAlchemy
Required-by: langchain-neo4j
---
Name: langchain-core
Version: 0.3.79
Summary: Building applications with LLMs through composability
Home-page:
Author:
Author-email:
License: MIT
Location: C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages
Requires: jsonpatch, langsmith, packaging, pydantic, PyYAML, tenacity, typing-extensions
Required-by: langchain, langchain-classic, langchain-community, langchain-experimental, langchain-neo4j, langchain-text-splitters, langgraph, langgraph-checkpoint, langgraph-prebuilt
---
Name: pydantic
Version: 2.12.3
Summary: Data validation using Python type hints
Home-page: https://github.com/pydantic/pydantic
Author:
Author-email: Samuel Colvin <s@muelcolvin.com>, Eric Jolibois <em.jolibois@gmail.com>, Hasan Ramezani <hasan.r67@gmail.com>, Adrian Garcia Badaracco <1755071+adriangb@users.noreply.github.com>, Terrence Dorsey <terry@pydantic.dev>, David Montague <david@pydantic.dev>, Serge Matveenko <lig@countzero.co>, Marcelo Trylesinski <marcelotryle@gmail.com>, Sydney Runkle <sydneymarierunkle@gmail.com>, David Hewitt <mail@davidhewitt.io>, Alex Hall <alex.mojaki@gmail.com>, Victorien Plot <contact@vctrn.dev>, Douwe Maan <hi@douwe.me>
License-Expression: MIT
Location: C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages
Requires: annotated-types, pydantic-core, typing-extensions, typing-inspection
Required-by: langchain, langchain-classic, langchain-core, langgraph, langsmith, neo4j-graphrag, pydantic-settings

In [ ]:
!pip install "langchain==0.3.27"

In [2]:
import langchain, langchain_community, langchain_experimental
print("langchain:", langchain.__version__)
print("community:", langchain_community.__version__)
print("experimental:", langchain_experimental.__version__)
import inspect
from langchain_experimental import graph_transformers

# alle Submodule:
print([name for name, val in inspect.getmembers(graph_transformers) if inspect.ismodule(val)])

# alle Klassen:
print([name for name, val in inspect.getmembers(graph_transformers) if inspect.isclass(val)])

# alle Funktionen:
print([name for name, val in inspect.getmembers(graph_transformers) if inspect.isfunction(val)])

langchain: 1.0.5
community: 0.4.1
experimental: 0.4.0
['diffbot', 'gliner', 'llm', 'relik']
['DiffbotGraphTransformer', 'GlinerGraphTransformer', 'LLMGraphTransformer', 'RelikGraphTransformer']
[]

In [3]:
from langchain.chains.retrieval import create_retrieval_chain
from langchain_core.prompts.chat import ChatPromptTemplate
from langchain_community.chat_models import ChatLlamaCpp

ModuleNotFoundError: No module named 'langchain.chains'

In [5]:
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.graphs.neo4j_graph import Neo4jGraph
from langchain_community.vectorstores.neo4j_vector import Neo4jVector

In [ ]:
from langchain.

In [4]:

from langchain.chains.combine_documents import create_stuff_documents_chain

ModuleNotFoundError: No module named 'langchain.chains'

In [12]:
import sys, builtins, traceback, importlib

print("PYTHON:", sys.executable)
print(sys.version)
print("builtins.dict type:", type(builtins.dict))

# Test: erlaubt dein Python 'dict[...]'?
try:
    print("dict[str,int] ->", dict[str, int])
except Exception as e:
    print("dict[subscript] error:", type(e).__name__, e)

# Test: lässt sich das LangChain-Modul importieren?
try:
    m = importlib.import_module("langchain.chains.combine_documents")
    print("Imported langchain.chains.combine_documents OK")
    print("module __file__:", getattr(m, "__file__", None))
except Exception:
    print("\nIMPORT TRACEBACK:")
    traceback.print_exc()

PYTHON: c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Scripts\python.exe
3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)]
builtins.dict type: <class 'type'>
dict[str,int] -> dict[str, int]

IMPORT TRACEBACK:

Traceback (most recent call last):
  File "C:\Users\Nasiba\AppData\Local\Temp\ipykernel_33924\1302338123.py", line 15, in <module>
    m = importlib.import_module("langchain.chains.combine_documents")
  File "C:\Program Files\Python314\Lib\importlib\__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
    return _find_and_load(name, _gcd_import)
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
    return _find_and_load_unlocked(name, import_)
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
    module = _load_unlocked(spec)
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
    spec.loader.exec_module(module)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 762, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
    return f(*args, **kwds)
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\langchain\chains\combine_documents\__init__.py", line 3, in <module>
    from langchain.chains.combine_documents.reduce import (
    ...<3 lines>...
    )
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\langchain\chains\combine_documents\reduce.py", line 12, in <module>
    from langchain.chains.combine_documents.base import BaseCombineDocumentsChain
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\langchain\chains\combine_documents\base.py", line 18, in <module>
    from langchain.chains.base import Chain
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\langchain\chains\base.py", line 52, in <module>
    class Chain(RunnableSerializable[dict[str, Any], dict[str, Any]], ABC):
    ...<747 lines>...
            return [self(inputs, callbacks=callbacks) for inputs in input_list]
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 242, in __new__
    set_model_fields(cls, config_wrapper=config_wrapper, ns_resolver=ns_resolver)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\pydantic\_internal\_model_construction.py", line 566, in set_model_fields
    fields, class_vars = collect_model_fields(cls, config_wrapper, ns_resolver, typevars_map=typevars_map)
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\pydantic\_internal\_fields.py", line 256, in collect_model_fields
    type_hints = _typing_extra.get_model_type_hints(cls, ns_resolver=ns_resolver)
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\pydantic\_internal\_typing_extra.py", line 350, in get_model_type_hints
    hints[name] = try_eval_type(value, globalns, localns)
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\pydantic\_internal\_typing_extra.py", line 404, in try_eval_type
    return eval_type_backport(value, globalns, localns), True
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\pydantic\_internal\_typing_extra.py", line 455, in eval_type_backport
    return _eval_type_backport(value, globalns, localns, type_params)
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\pydantic\_internal\_typing_extra.py", line 492, in _eval_type_backport
    return _eval_type(value, globalns, localns, type_params)
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\pydantic\_internal\_typing_extra.py", line 524, in _eval_type
    evaluated = typing._eval_type(  # type: ignore
        value,
    ...<2 lines>...
        type_params=type_params,
    )
  File "C:\Program Files\Python314\Lib\typing.py", line 461, in _eval_type
    return evaluate_forward_ref(t, globals=globalns, locals=localns,
                                type_params=type_params, owner=owner,
                                _recursive_guard=recursive_guard, format=format)
  File "C:\Program Files\Python314\Lib\typing.py", line 1000, in evaluate_forward_ref
    value = forward_ref.evaluate(globals=globals, locals=locals,
                                 type_params=type_params, owner=owner, format=format)
  File "C:\Program Files\Python314\Lib\annotationlib.py", line 186, in evaluate
    return eval(code, globals=globals, locals=locals)
  File "<string>", line 1, in <module>
TypeError: 'function' object is not subscriptable
Unable to evaluate type annotation 'Optional[dict[str, Any]]'.

In [2]:
from pathlib import Path
import pandas as p
# Projektwurzel robuster finden: gehe von der aktuellen Arbeitsdir nach oben,
# bis ein 'main' Ordner existiert.
cur = Path.cwd().resolve()
candidates = [cur, *cur.parents]
project_root = next(p for p in candidates if (p / "main").exists())
#C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\knowledeg_graph\experiments\kg_rebel_test.ipynb
json_path = (project_root / "main" / "ressources" / "knowledge_graph" /
             "neo4j" / "neo4j" / "import" / "docling_chunks.jsonl")

json_path_2 = (project_root / "main" / "knowledeg_graph" / "experiments" / "docling_chunks_portentac33.jsonl")

print("Pfad:", json_path_2)
print("Existiert?", json_path_2.exists())

output_file_name = "entities_relations_portentac33.json"


df = p.read_json(Path(json_path), lines=True)

df_2 = p.read_json(Path(json_path_2), lines=True)
df_2.head(2)

Pfad: C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\knowledeg_graph\experiments\docling_chunks_portentac33.jsonl
Existiert? True

,category,chunk_id,chunk_size,chunk_type,product,section,semantic_density,text,total_chunks,element,tutorial
0,Portenta Family,Microcontroller Renesas R7FA6M5BH2CBG::c0,127,contextualized,Portenta C33,NaN,0.2326,[Product: Portenta C33] [Category: Portenta Fa...,310,NaN,NaN
1,Portenta Family,Microcontroller Renesas R7FA6M5BH2CBG::c1,116,contextualized,Portenta C33,NaN,0.2886,[Product: Portenta C33] [Category: Portenta Fa...,310,NaN,NaN

In [3]:
json_path = (project_root / "main" / "ressources" / "knowledge_graph" /
             "neo4j" / "neo4j" / "import" / "docling_chunks.jsonl")
#C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\out\Portenta Family\docling_chunks.jsonl

json_path_2 = (project_root / "main" / "out" / "Portenta Family" / "docling_chunks.jsonl")

print("Pfad:", json_path_2)
print("Existiert?", json_path_2.exists())

output_file_name = "entities_relations_portentac33.json"


df = p.read_json(Path(json_path), lines=True)

df_2 = p.read_json(Path(json_path_2), lines=True)
df_2.head(2)

Pfad: C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\out\Portenta Family\docling_chunks.jsonl
Existiert? True

,file_name,chunk_id,chunk_size,semantic_density,product_category,product,section,text
0,Microcontroller Renesas R7FA6M5BH2CBG.pdf,Microcontroller Renesas R7FA6M5BH2CBG::c0,127,0.2326,Portenta Family,Portenta C33,NaN,[Product: Portenta C33] [Product category: Por...
1,Microcontroller Renesas R7FA6M5BH2CBG.pdf,Microcontroller Renesas R7FA6M5BH2CBG::c1,116,0.2886,Portenta Family,Portenta C33,NaN,[Product: Portenta C33] [Product category: Por...

In [9]:
result =  df_2.loc[
    (df_2["element"].notnull()) | (df_2["tutorial"].notnull()),
    ["product", "text", "chunk_id"]
]

result.head(5)

KeyError: 'element'

In [1]:
from main.knowledeg_graph.extract_entities_langchain import load_docs_from_jsonl, docs_to_graph_docs, write_to_neo4j

docs = load_docs_from_jsonl(json_path_2)
print(f"Gefundene Chunks: {len(docs)}")

# Optional: nur ein paar zum Test
# docs = docs[:20]

graph_docs = docs_to_graph_docs(docs, batch_size=6)  # batch_size je nach RAM/Modell
print(f"Erzeugte GraphDocuments: {len(graph_docs)}")

write_to_neo4j(graph_docs)

ModuleNotFoundError: No module named 'main'

In [80]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1211 entries, 0 to 1210
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   category          1211 non-null   object
 1   chunk_id          1211 non-null   object
 2   chunk_size        1211 non-null   int64
 3   chunk_type        1211 non-null   object
 4   product           1211 non-null   object
 5   section           0 non-null      float64
 6   semantic_density  1211 non-null   float64
 7   text              1211 non-null   object
 8   total_chunks      1211 non-null   int64
 9   element           0 non-null      float64
 10  tutorial          0 non-null      float64
dtypes: float64(4), int64(2), object(5)
memory usage: 104.2+ KB

In [5]:
import os
from langchain_experimental.graph_transformers.llm import LLMGraphTransformer
 
#import networkx as nx
#from langchain.chains import GraphQAChain
from langchain_core.documents import Document
#from langchain_community.graphs.networkx_graph import NetworkxEntityGraph

In [6]:

text = """
2 Features
2.1 General Specifications Overview
The Portenta C33 is a powerful microcontroller board designed for low-cost IoT applications. Based on the highperformance
R7FA6M5BH2CBG microcontroller from Renesas®, it offers a range of key features and a low-power
design that make it well-suited for a variety of applications. The board has been designed with the same form factor
as the Portenta H7 and is backward compatible, making it fully compatible with all Portenta family shields and
carriers through its MKR-styled and high-density connectors. Table 1 summarizes the board's main features, and
Table 2, 3, 4, 5, and 6 shows more detailed information about the board's microcontroller, secure element, Ethernet
transceiver, and external memory.
"""

documents = [Document(page_content=text)]
documents

[Document(metadata={}, page_content="\n2 Features\n2.1 General Specifications Overview\nThe Portenta C33 is a powerful microcontroller board designed for low-cost IoT applications. Based on the highperformance\nR7FA6M5BH2CBG microcontroller from Renesas®, it offers a range of key features and a low-power\ndesign that make it well-suited for a variety of applications. The board has been designed with the same form factor\nas the Portenta H7 and is backward compatible, making it fully compatible with all Portenta family shields and\ncarriers through its MKR-styled and high-density connectors. Table 1 summarizes the board's main features, and\nTable 2, 3, 4, 5, and 6 shows more detailed information about the board's microcontroller, secure element, Ethernet\ntransceiver, and external memory.\n")]

In [18]:
import pandas as pd

pd.set_option('display.max_colwidth', None)

result = df_2.loc[
    (df_2["product"] == "Portenta C33")
    & (df_2["text"].str.contains(
        "The Portenta C33 is a powerful microcontroller board designed",
        regex=False, na=False
    ))
    & (df_2["chunk_id"].astype(str).str.contains("Portenta C33 Datasheet", regex=False, na=False)),
    ["product", "text", "chunk_id"]
]

#  Als JSONL speichern
result.to_json("test_json_entities.jsonl", orient="records", lines=True, force_ascii=False)

In [7]:
json_path_2 = (project_root / "main" / "knowledeg_graph" / "experiments" / "test_json_entities.jsonl")

print("Pfad:", json_path_2)
print("Existiert?", json_path_2.exists())

output_file_name = "entities_relations_portentac33.json"
import pandas as p

df = p.read_json(Path(json_path), lines=True)

df_2 = p.read_json(Path(json_path_2), lines=True)
df_2.head(2)

Pfad: C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\knowledeg_graph\experiments\test_json_entities.jsonl
Existiert? True

,product,text,chunk_id
0,Portenta C33,[Product: Portenta C33] [Category: Portenta Fa...,Portenta C33 Datasheet::c4
1,Portenta C33,[Product: Portenta C33] [Category: Portenta Fa...,Portenta C33 Datasheet::c4

In [8]:
from langchain_community.chat_models import ChatLlamaCpp
from langchain_experimental.graph_transformers import LLMGraphTransformer
from langchain.docstore.document import Document
#from langchain_neo4j import Neo4jGraph

# ---- Lokales GGUF als Chat-Modell (WICHTIG: ChatLlamaCpp, nicht llama_cpp.Llama) ----
chat_llm = ChatLlamaCpp(
    model_path=r"C:\models\qwen2.5-7b-instruct-q3_k_m.gguf",
    temperature=0,
    n_ctx=4096,            # je nach Modell/Hardware
    n_threads=4,           # passe an deine CPU an
    n_gpu_layers=0         # CPU-only; bei GPU >0 setzen
)

# ---- LLMGraphTransformer OHNE function-calling / structured_output ----
gt = LLMGraphTransformer(
    llm=chat_llm,
    # function_call=False     # <-- Das verhindert den Fehler 'with_structured_output'
)

llama_model_loader: loaded meta data with 26 key-value pairs and 339 tensors from C:\models\qwen2.5-7b-instruct-q3_k_m.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = qwen2.5-7b-instruct
llama_model_loader: - kv   3:                            general.version str              = v0.1
llama_model_loader: - kv   4:                           general.finetune str              = qwen2.5-7b-instruct
llama_model_loader: - kv   5:                         general.size_label str              = 7.6B
llama_model_loader: - kv   6:                          qwen2.block_count u32              = 28
llama_model_loader: - kv   7:                       qwen2.context_length u32              = 131072
llama_model_loader: - kv   8:                     qwen2.embedding_length u32              = 3584
llama_model_loader: - kv   9:                  qwen2.feed_forward_length u32              = 18944
llama_model_loader: - kv  10:                 qwen2.attention.head_count u32              = 28
llama_model_loader: - kv  11:              qwen2.attention.head_count_kv u32              = 4
llama_model_loader: - kv  12:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  14:                          general.file_type u32              = 12
llama_model_loader: - kv  15:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  16:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  17:                      tokenizer.ggml.tokens arr[str,152064]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  18:                  tokenizer.ggml.token_type arr[i32,152064]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  19:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  22:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  23:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
llama_model_loader: - kv  25:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  141 tensors
llama_model_loader: - type q3_K:  113 tensors
llama_model_loader: - type q4_K:   81 tensors
llama_model_loader: - type q5_K:    3 tensors
llama_model_loader: - type q6_K:    1 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q3_K - Medium
print_info: file size   = 3.54 GiB (3.99 BPW)
init_tokenizer: initializing tokenizer for type 2
load: control token: 151661 '<|fim_suffix|>' is not marked as EOG
load: control token: 151649 '<|box_end|>' is not marked as EOG
load: control token: 151647 '<|object_ref_end|>' is not marked as EOG
load: control token: 151654 '<|vision_pad|>' is not marked as EOG
load: control token: 151659 '<|fim_prefix|>' is not marked as EOG
load: control token: 151648 '<|box_start|>' is not marked as EOG
load: control token: 151644 '<|im_start|>' is not marked as EOG
load: control token: 151646 '<|object_ref_start|>' is not marked as EOG
load: control token: 151650 '<|quad_start|>' is not marked as EOG
load: control token: 151651 '<|quad_end|>' is not marked as EOG
load: control token: 151652 '<|vision_start|>' is not marked as EOG
load: control token: 151653 '<|vision_end|>' is not marked as EOG
load: control token: 151655 '<|image_pad|>' is not marked as EOG
load: control token: 151656 '<|video_pad|>' is not marked as EOG
load: control token: 151660 '<|fim_middle|>' is not marked as EOG
load: printing all EOG tokens:
load:   - 151643 ('<|endoftext|>')
load:   - 151645 ('<|im_end|>')
load:   - 151662 ('<|fim_pad|>')
load:   - 151663 ('<|repo_name|>')
load:   - 151664 ('<|file_sep|>')
load: special tokens cache size = 22
load: token to piece cache size = 0.9310 MB
print_info: arch             = qwen2
print_info: vocab_only       = 0
print_info: n_ctx_train      = 131072
print_info: n_embd           = 3584
print_info: n_layer          = 28
print_info: n_head           = 28
print_info: n_head_kv        = 4
print_info: n_rot            = 128
print_info: n_swa            = 0
print_info: is_swa_any       = 0
print_info: n_embd_head_k    = 128
print_info: n_embd_head_v    = 128
print_info: n_gqa            = 7
print_info: n_embd_k_gqa     = 512
print_info: n_embd_v_gqa     = 512
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-06
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 0.0e+00
print_info: n_ff             = 18944
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: causal attn      = 1
print_info: pooling type     = -1
print_info: rope type        = 2
print_info: rope scaling     = linear
print_info: freq_base_train  = 1000000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 131072
print_info: rope_finetuned   = unknown
print_info: model type       = 7B
print_info: model params     = 7.62 B
print_info: general.name     = qwen2.5-7b-instruct
print_info: vocab type       = BPE
print_info: n_vocab          = 152064
print_info: n_merges         = 151387
print_info: BOS token        = 151643 '<|endoftext|>'
print_info: EOS token        = 151645 '<|im_end|>'
print_info: EOT token        = 151645 '<|im_end|>'
print_info: PAD token        = 151643 '<|endoftext|>'
print_info: LF token         = 198 'Ċ'
print_info: FIM PRE token    = 151659 '<|fim_prefix|>'
print_info: FIM SUF token    = 151661 '<|fim_suffix|>'
print_info: FIM MID token    = 151660 '<|fim_middle|>'
print_info: FIM PAD token    = 151662 '<|fim_pad|>'
print_info: FIM REP token    = 151663 '<|repo_name|>'
print_info: FIM SEP token    = 151664 '<|file_sep|>'
print_info: EOG token        = 151643 '<|endoftext|>'
print_info: EOG token        = 151645 '<|im_end|>'
print_info: EOG token        = 151662 '<|fim_pad|>'
print_info: EOG token        = 151663 '<|repo_name|>'
print_info: EOG token        = 151664 '<|file_sep|>'
print_info: max token length = 256
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors: layer   0 assigned to device CPU, is_swa = 0
load_tensors: layer   1 assigned to device CPU, is_swa = 0
load_tensors: layer   2 assigned to device CPU, is_swa = 0
load_tensors: layer   3 assigned to device CPU, is_swa = 0
load_tensors: layer   4 assigned to device CPU, is_swa = 0
load_tensors: layer   5 assigned to device CPU, is_swa = 0
load_tensors: layer   6 assigned to device CPU, is_swa = 0
load_tensors: layer   7 assigned to device CPU, is_swa = 0
load_tensors: layer   8 assigned to device CPU, is_swa = 0
load_tensors: layer   9 assigned to device CPU, is_swa = 0
load_tensors: layer  10 assigned to device CPU, is_swa = 0
load_tensors: layer  11 assigned to device CPU, is_swa = 0
load_tensors: layer  12 assigned to device CPU, is_swa = 0
load_tensors: layer  13 assigned to device CPU, is_swa = 0
load_tensors: layer  14 assigned to device CPU, is_swa = 0
load_tensors: layer  15 assigned to device CPU, is_swa = 0
load_tensors: layer  16 assigned to device CPU, is_swa = 0
load_tensors: layer  17 assigned to device CPU, is_swa = 0
load_tensors: layer  18 assigned to device CPU, is_swa = 0
load_tensors: layer  19 assigned to device CPU, is_swa = 0
load_tensors: layer  20 assigned to device CPU, is_swa = 0
load_tensors: layer  21 assigned to device CPU, is_swa = 0
load_tensors: layer  22 assigned to device CPU, is_swa = 0
load_tensors: layer  23 assigned to device CPU, is_swa = 0
load_tensors: layer  24 assigned to device CPU, is_swa = 0
load_tensors: layer  25 assigned to device CPU, is_swa = 0
load_tensors: layer  26 assigned to device CPU, is_swa = 0
load_tensors: layer  27 assigned to device CPU, is_swa = 0
load_tensors: layer  28 assigned to device CPU, is_swa = 0
load_tensors: tensor 'token_embd.weight' (q3_K) (and 257 others) cannot be used with preferred buffer type CPU_REPACK, using CPU instead
load_tensors:   CPU_REPACK model buffer size =  1201.92 MiB
load_tensors:   CPU_Mapped model buffer size =  3626.29 MiB
repack: repack tensor blk.0.attn_output.weight with q4_K_8x8
repack: repack tensor blk.1.attn_output.weight with q4_K_8x8
repack: repack tensor blk.1.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.2.attn_v.weight with q4_K_8x8
repack: repack tensor blk.2.attn_output.weight with q4_K_8x8
repack: repack tensor blk.2.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.3.attn_v.weight with q4_K_8x8
repack: repack tensor blk.3.attn_output.weight with q4_K_8x8
repack: repack tensor blk.3.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.4.attn_v.weight with q4_K_8x8
repack: repack tensor blk.4.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.4.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.5.attn_v.weight with q4_K_8x8
repack: repack tensor blk.5.attn_output.weight with q4_K_8x8
repack: repack tensor blk.5.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.6.attn_v.weight with q4_K_8x8
repack: repack tensor blk.6.attn_output.weight with q4_K_8x8
repack: repack tensor blk.6.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.7.attn_v.weight with q4_K_8x8
repack: repack tensor blk.7.attn_output.weight with q4_K_8x8
repack: repack tensor blk.7.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.8.attn_v.weight with q4_K_8x8
repack: repack tensor blk.8.attn_output.weight with q4_K_8x8
repack: repack tensor blk.8.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.9.attn_v.weight with q4_K_8x8
repack: repack tensor blk.9.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.9.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.10.attn_v.weight with q4_K_8x8
repack: repack tensor blk.10.attn_output.weight with q4_K_8x8
repack: repack tensor blk.10.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.11.attn_v.weight with q4_K_8x8
repack: repack tensor blk.11.attn_output.weight with q4_K_8x8
repack: repack tensor blk.11.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.12.attn_v.weight with q4_K_8x8
repack: repack tensor blk.12.attn_output.weight with q4_K_8x8
repack: repack tensor blk.12.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.13.attn_v.weight with q4_K_8x8
repack: repack tensor blk.13.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.13.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.14.attn_v.weight with q4_K_8x8
repack: repack tensor blk.14.attn_output.weight with q4_K_8x8
repack: repack tensor blk.14.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.15.attn_v.weight with q4_K_8x8
repack: repack tensor blk.15.attn_output.weight with q4_K_8x8
repack: repack tensor blk.15.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.16.attn_v.weight with q4_K_8x8
repack: repack tensor blk.16.attn_output.weight with q4_K_8x8
repack: repack tensor blk.16.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.17.attn_v.weight with q4_K_8x8
repack: repack tensor blk.17.attn_output.weight with q4_K_8x8
repack: repack tensor blk.17.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.18.attn_v.weight with q4_K_8x8
repack: repack tensor blk.18.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.18.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.19.attn_v.weight with q4_K_8x8
repack: repack tensor blk.19.attn_output.weight with q4_K_8x8
repack: repack tensor blk.19.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.20.attn_v.weight with q4_K_8x8
repack: repack tensor blk.20.attn_output.weight with q4_K_8x8
repack: repack tensor blk.20.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.21.attn_v.weight with q4_K_8x8
repack: repack tensor blk.21.attn_output.weight with q4_K_8x8
repack: repack tensor blk.21.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.22.attn_v.weight with q4_K_8x8
repack: repack tensor blk.22.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.22.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.23.attn_v.weight with q4_K_8x8
repack: repack tensor blk.23.attn_output.weight with q4_K_8x8
repack: repack tensor blk.23.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.24.attn_v.weight with q4_K_8x8
repack: repack tensor blk.24.attn_output.weight with q4_K_8x8
repack: repack tensor blk.24.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.25.attn_v.weight with q4_K_8x8
repack: repack tensor blk.25.attn_output.weight with q4_K_8x8
repack: repack tensor blk.25.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.26.attn_v.weight with q4_K_8x8
repack: repack tensor blk.26.attn_output.weight with q4_K_8x8
repack: repack tensor blk.26.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.27.attn_v.weight with q4_K_8x8
repack: repack tensor blk.27.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.27.ffn_down.weight with q4_K_8x8
....................................................
llama_context: constructing llama_context
llama_context: n_batch is less than GGML_KQ_MASK_PAD - increasing to 64
llama_context: n_seq_max     = 1
llama_context: n_ctx         = 4096
llama_context: n_ctx_per_seq = 4096
llama_context: n_batch       = 64
llama_context: n_ubatch      = 8
llama_context: causal_attn   = 1
llama_context: flash_attn    = 0
llama_context: kv_unified    = false
llama_context: freq_base     = 10000.0
llama_context: freq_scale    = 1
llama_context: n_ctx_per_seq (4096) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
set_abort_callback: call
llama_context:        CPU  output buffer size =     0.58 MiB
create_memory: n_ctx = 4096 (padded)
llama_kv_cache_unified: layer   0: dev = CPU
llama_kv_cache_unified: layer   1: dev = CPU
llama_kv_cache_unified: layer   2: dev = CPU
llama_kv_cache_unified: layer   3: dev = CPU
llama_kv_cache_unified: layer   4: dev = CPU
llama_kv_cache_unified: layer   5: dev = CPU
llama_kv_cache_unified: layer   6: dev = CPU
llama_kv_cache_unified: layer   7: dev = CPU
llama_kv_cache_unified: layer   8: dev = CPU
llama_kv_cache_unified: layer   9: dev = CPU
llama_kv_cache_unified: layer  10: dev = CPU
llama_kv_cache_unified: layer  11: dev = CPU
llama_kv_cache_unified: layer  12: dev = CPU
llama_kv_cache_unified: layer  13: dev = CPU
llama_kv_cache_unified: layer  14: dev = CPU
llama_kv_cache_unified: layer  15: dev = CPU
llama_kv_cache_unified: layer  16: dev = CPU
llama_kv_cache_unified: layer  17: dev = CPU
llama_kv_cache_unified: layer  18: dev = CPU
llama_kv_cache_unified: layer  19: dev = CPU
llama_kv_cache_unified: layer  20: dev = CPU
llama_kv_cache_unified: layer  21: dev = CPU
llama_kv_cache_unified: layer  22: dev = CPU
llama_kv_cache_unified: layer  23: dev = CPU
llama_kv_cache_unified: layer  24: dev = CPU
llama_kv_cache_unified: layer  25: dev = CPU
llama_kv_cache_unified: layer  26: dev = CPU
llama_kv_cache_unified: layer  27: dev = CPU
llama_kv_cache_unified:        CPU KV buffer size =   224.00 MiB
llama_kv_cache_unified: size =  224.00 MiB (  4096 cells,  28 layers,  1/1 seqs), K (f16):  112.00 MiB, V (f16):  112.00 MiB
llama_context: enumerating backends
llama_context: backend_ptrs.size() = 1
llama_context: max_nodes = 2712
llama_context: worst-case: n_tokens = 8, n_seqs = 1, n_outputs = 0
graph_reserve: reserving a graph for ubatch with n_tokens =    8, n_seqs =  1, n_outputs =    8
graph_reserve: reserving a graph for ubatch with n_tokens =    1, n_seqs =  1, n_outputs =    1
graph_reserve: reserving a graph for ubatch with n_tokens =    8, n_seqs =  1, n_outputs =    8
llama_context:        CPU compute buffer size =     4.97 MiB
llama_context: graph nodes  = 1070
llama_context: graph splits = 1
CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 |

In [9]:
text = "The Portenta Breakout board has an RJ45 Ethernet interface and belongs to the Portenta Family."
#docs = Document(page_content=text)
docs = [Document(page_content=text)]
#docs = documents
graph_docs = gt.convert_to_graph_documents(docs)
len(graph_docs), graph_docs[0].nodes[:2], graph_docs[0].relationships[:2]
print(graph_docs[0].nodes)
print(graph_docs[0].relationships)

llama_perf_context_print:        load time =  148677.05 ms
llama_perf_context_print: prompt eval time =  148675.93 ms /  1228 tokens (  121.07 ms per token,     8.26 tokens per second)
llama_perf_context_print:        eval time =   27290.78 ms /    87 runs   (  313.69 ms per token,     3.19 tokens per second)
llama_perf_context_print:       total time =  181778.70 ms /  1315 tokens
llama_perf_context_print:    graphs reused =        197

[Node(id='The Portenta Breakout Board', type='Portenta breakout board', properties={})]
[Relationship(source=Node(id='The Portenta Breakout Board', type='Portenta breakout board', properties={}), target=Node(id='Rj45 Ethernet Interface', type='Rj45 ethernet interface', properties={}), type='HAS', properties={})]

In [10]:
result_tuple = (graph_docs[0].nodes, graph_docs[0].relationships)

In [ ]:
from langchain_community.graphs.neo4j_graph import Neo4jGraph
from langchain_core.documents import Document
from langchain_community.graphs.graph_document import GraphDocument
# Verbindung herstellen
graph = Neo4jGraph(
    url="bolt://localhost:7687",    # oder neo4j+s://<id>.databases.neo4j.io für Aura
    username="neo4j",
    password="testmaster123"
)

# Ersten Graph nehmen
nodes = graph_docs[0].nodes
rels = graph_docs[0].relationships

# Wieder in GraphDocument packen (falls nötig)
source=Document(page_content="manuell importierter Chunk", metadata={"id": "manual_import"})
graph_doc = GraphDocument(nodes=nodes, relationships=rels, source=source)

# In Neo4j speichern
graph.add_graph_documents([graph_doc])
print(" Graph wurde erfolgreich in Neo4j geladen.")
print(rels)
print(nodes)

 Graph wurde erfolgreich in Neo4j geladen.

In [10]:
!pip install sentence_transformers

Collecting sentence_transformers
  Downloading sentence_transformers-5.1.2-py3-none-any.whl.metadata (16 kB)
Collecting transformers<5.0.0,>=4.41.0 (from sentence_transformers)
  Downloading transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Collecting tqdm (from sentence_transformers)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting torch>=1.11.0 (from sentence_transformers)
  Downloading torch-2.9.0-cp314-cp314-win_amd64.whl.metadata (30 kB)
Collecting scikit-learn (from sentence_transformers)
  Downloading scikit_learn-1.7.2-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting scipy (from sentence_transformers)
  Downloading scipy-1.16.3-cp314-cp314-win_amd64.whl.metadata (60 kB)
Collecting huggingface-hub>=0.20.0 (from sentence_transformers)
  Downloading huggingface_hub-1.1.2-py3-none-any.whl.metadata (13 kB)
Collecting Pillow (from sentence_transformers)
  Downloading pillow-12.0.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from sentence_transformers) (4.15.0)
Collecting filelock (from transformers<5.0.0,>=4.41.0->sentence_transformers)
  Downloading filelock-3.20.0-py3-none-any.whl.metadata (2.1 kB)
Collecting huggingface-hub>=0.20.0 (from sentence_transformers)
  Downloading huggingface_hub-0.36.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2.3.4)
Requirement already satisfied: packaging>=20.0 in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (6.0.3)
Collecting regex!=2019.12.17 (from transformers<5.0.0,>=4.41.0->sentence_transformers)
  Downloading regex-2025.11.3-cp314-cp314-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: requests in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2.32.5)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers<5.0.0,>=4.41.0->sentence_transformers)
  Downloading tokenizers-0.22.1-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Collecting safetensors>=0.4.3 (from transformers<5.0.0,>=4.41.0->sentence_transformers)
  Downloading safetensors-0.6.2-cp38-abi3-win_amd64.whl.metadata (4.1 kB)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2024.12.0)
Collecting sympy>=1.13.3 (from torch>=1.11.0->sentence_transformers)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Collecting networkx>=2.5.1 (from torch>=1.11.0->sentence_transformers)
  Downloading networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: jinja2 in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Collecting setuptools (from torch>=1.11.0->sentence_transformers)
  Downloading setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: colorama in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from tqdm->sentence_transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\nasiba\documents\1 master data science\master thesis\vs code new\master_thesis-rag\.venv\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence_transformers) (2025.10.5)
Collecting joblib>=1.2.0 (from scikit-learn->sentence_transformers)
  Downloading joblib-1.5.2-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn->sentence_transformers)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading sentence_transformers-5.1.2-py3-none-any.whl (488 kB)
Downloading transformers-4.57.1-py3-none-any.whl (12.0 MB)
   ---------------------------------------- 0.0/12.0 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.0 MB 5.6 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.0 MB 7.4 MB/s eta 0:00:02
   ------------------ --------------------- 5.5/12.0 MB 9.4 MB/s eta 0:00:01
   ----------------------------- ---------- 8.9/12.0 MB 11.5 MB/s eta 0:00:01
   ---------------------------------------  11.8/12.0 MB 12.9 MB/s eta 0:00:01
   ---------------------------------------- 12.0/12.0 MB 11.3 MB/s  0:00:01
Downloading huggingface_hub-0.36.0-py3-none-any.whl (566 kB)
   ---------------------------------------- 0.0/566.1 kB ? eta -:--:--
   ---------------------------------------- 566.1/566.1 kB 12.2 MB/s  0:00:00
Downloading tokenizers-0.22.1-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 2.7/2.7 MB 15.1 MB/s  0:00:00
Downloading regex-2025.11.3-cp314-cp314-win_amd64.whl (280 kB)
Downloading safetensors-0.6.2-cp38-abi3-win_amd64.whl (320 kB)
Downloading torch-2.9.0-cp314-cp314-win_amd64.whl (109.3 MB)
   ---------------------------------------- 0.0/109.3 MB ? eta -:--:--
   -- ------------------------------------- 6.0/109.3 MB 28.6 MB/s eta 0:00:04
   --- ------------------------------------ 10.2/109.3 MB 24.6 MB/s eta 0:00:05
   ----- ---------------------------------- 15.2/109.3 MB 24.5 MB/s eta 0:00:04
   ------- -------------------------------- 20.2/109.3 MB 24.9 MB/s eta 0:00:04
   --------- ------------------------------ 25.2/109.3 MB 24.7 MB/s eta 0:00:04
   ---------- ----------------------------- 29.4/109.3 MB 24.0 MB/s eta 0:00:04
   ------------ --------------------------- 33.6/109.3 MB 23.6 MB/s eta 0:00:04
   ------------- -------------------------- 37.5/109.3 MB 23.1 MB/s eta 0:00:04
   --------------- ------------------------ 41.7/109.3 MB 22.7 MB/s eta 0:00:03
   ---------------- ----------------------- 44.6/109.3 MB 21.8 MB/s eta 0:00:03
   ----------------- ---------------------- 47.4/109.3 MB 21.2 MB/s eta 0:00:03
   ------------------ --------------------- 50.6/109.3 MB 20.7 MB/s eta 0:00:03
   ------------------- -------------------- 53.5/109.3 MB 20.3 MB/s eta 0:00:03
   -------------------- ------------------- 56.9/109.3 MB 19.9 MB/s eta 0:00:03
   --------------------- ------------------ 59.8/109.3 MB 19.5 MB/s eta 0:00:03
   ---------------------- ----------------- 62.7/109.3 MB 19.3 MB/s eta 0:00:03
   ------------------------ --------------- 66.1/109.3 MB 19.1 MB/s eta 0:00:03
   ------------------------- -------------- 69.2/109.3 MB 19.0 MB/s eta 0:00:03
   -------------------------- ------------- 72.6/109.3 MB 18.8 MB/s eta 0:00:02
   --------------------------- ------------ 75.8/109.3 MB 18.6 MB/s eta 0:00:02
   ---------------------------- ----------- 78.9/109.3 MB 18.5 MB/s eta 0:00:02
   ----------------------------- ---------- 80.7/109.3 MB 18.0 MB/s eta 0:00:02
   ------------------------------ --------- 82.1/109.3 MB 17.6 MB/s eta 0:00:02
   ------------------------------ --------- 84.4/109.3 MB 17.3 MB/s eta 0:00:02
   ------------------------------- -------- 86.8/109.3 MB 17.0 MB/s eta 0:00:02
   -------------------------------- ------- 88.9/109.3 MB 16.8 MB/s eta 0:00:02
   --------------------------------- ------ 91.2/109.3 MB 16.6 MB/s eta 0:00:02
   ---------------------------------- ----- 93.8/109.3 MB 16.5 MB/s eta 0:00:01
   ----------------------------------- ---- 96.5/109.3 MB 16.4 MB/s eta 0:00:01
   ------------------------------------ --- 99.1/109.3 MB 16.2 MB/s eta 0:00:01
   ------------------------------------ -- 101.7/109.3 MB 16.1 MB/s eta 0:00:01
   ------------------------------------- - 103.8/109.3 MB 16.0 MB/s eta 0:00:01
   ------------------------------------- - 105.9/109.3 MB 15.8 MB/s eta 0:00:01
   --------------------------------------  107.7/109.3 MB 15.6 MB/s eta 0:00:01
   --------------------------------------  109.1/109.3 MB 15.5 MB/s eta 0:00:01
   --------------------------------------  109.1/109.3 MB 15.5 MB/s eta 0:00:01
   --------------------------------------  109.1/109.3 MB 15.5 MB/s eta 0:00:01
   --------------------------------------  109.1/109.3 MB 15.5 MB/s eta 0:00:01
   --------------------------------------  109.1/109.3 MB 15.5 MB/s eta 0:00:01
   --------------------------------------  109.1/109.3 MB 15.5 MB/s eta 0:00:01
   --------------------------------------  109.1/109.3 MB 15.5 MB/s eta 0:00:01
   --------------------------------------  109.1/109.3 MB 15.5 MB/s eta 0:00:01
   --------------------------------------  109.1/109.3 MB 15.5 MB/s eta 0:00:01
   --------------------------------------  109.1/109.3 MB 15.5 MB/s eta 0:00:01
   ---------------------------------------- 109.3/109.3 MB 12.0 MB/s  0:00:09
Downloading networkx-3.5-py3-none-any.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ------------------------------ --------- 1.6/2.0 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 6.1 MB/s  0:00:00
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   -------- ------------------------------- 1.3/6.3 MB 7.6 MB/s eta 0:00:01
   ------------------- -------------------- 3.1/6.3 MB 7.7 MB/s eta 0:00:01
   ----------------------------- ---------- 4.7/6.3 MB 7.7 MB/s eta 0:00:01
   ---------------------------------------  6.3/6.3 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 7.1 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   ---------------------------------------- 536.2/536.2 kB 5.1 MB/s  0:00:00
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Downloading filelock-3.20.0-py3-none-any.whl (16 kB)
Downloading pillow-12.0.0-cp314-cp314-win_amd64.whl (7.1 MB)
   ---------------------------------------- 0.0/7.1 MB ? eta -:--:--
   -------- ------------------------------- 1.6/7.1 MB 8.3 MB/s eta 0:00:01
   ------------------- -------------------- 3.4/7.1 MB 8.2 MB/s eta 0:00:01
   ----------------------------- ---------- 5.2/7.1 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------  7.1/7.1 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 7.1/7.1 MB 7.3 MB/s  0:00:00
Downloading scikit_learn-1.7.2-cp314-cp314-win_amd64.whl (8.8 MB)
   ---------------------------------------- 0.0/8.8 MB ? eta -:--:--
   ------- -------------------------------- 1.6/8.8 MB 8.9 MB/s eta 0:00:01
   --------------- ------------------------ 3.4/8.8 MB 8.8 MB/s eta 0:00:01
   ------------------------ --------------- 5.5/8.8 MB 9.2 MB/s eta 0:00:01
   --------------------------------- ------ 7.3/8.8 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------  8.7/8.8 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------- 8.8/8.8 MB 8.2 MB/s  0:00:01
Downloading joblib-1.5.2-py3-none-any.whl (308 kB)
Downloading scipy-1.16.3-cp314-cp314-win_amd64.whl (39.4 MB)
   ---------------------------------------- 0.0/39.4 MB ? eta -:--:--
   - -------------------------------------- 1.8/39.4 MB 10.0 MB/s eta 0:00:04
   ---- ----------------------------------- 4.2/39.4 MB 10.0 MB/s eta 0:00:04
   ------ --------------------------------- 6.0/39.4 MB 9.9 MB/s eta 0:00:04
   -------- ------------------------------- 8.1/39.4 MB 10.0 MB/s eta 0:00:04
   ---------- ----------------------------- 10.2/39.4 MB 10.0 MB/s eta 0:00:03
   ------------ --------------------------- 12.6/39.4 MB 10.2 MB/s eta 0:00:03
   -------------- ------------------------- 14.7/39.4 MB 10.3 MB/s eta 0:00:03
   ----------------- ---------------------- 17.0/39.4 MB 10.3 MB/s eta 0:00:03
   ------------------- -------------------- 19.4/39.4 MB 10.5 MB/s eta 0:00:02
   ---------------------- ----------------- 21.8/39.4 MB 10.5 MB/s eta 0:00:02
   ------------------------ --------------- 24.1/39.4 MB 10.7 MB/s eta 0:00:02
   -------------------------- ------------- 26.5/39.4 MB 10.8 MB/s eta 0:00:02
   ----------------------------- ---------- 29.1/39.4 MB 10.8 MB/s eta 0:00:01
   ------------------------------- -------- 31.5/39.4 MB 10.9 MB/s eta 0:00:01
   ---------------------------------- ----- 33.8/39.4 MB 11.0 MB/s eta 0:00:01
   ------------------------------------ --- 36.2/39.4 MB 11.0 MB/s eta 0:00:01
   ---------------------------------------  38.8/39.4 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------  39.3/39.4 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------  39.3/39.4 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------- 39.4/39.4 MB 9.9 MB/s  0:00:03
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading setuptools-80.9.0-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 1.2/1.2 MB 10.2 MB/s  0:00:00
Installing collected packages: mpmath, tqdm, threadpoolctl, sympy, setuptools, scipy, safetensors, regex, Pillow, networkx, joblib, filelock, torch, scikit-learn, huggingface-hub, tokenizers, transformers, sentence_transformers

   ----------------------------------------  0/18 [mpmath]
   ----------------------------------------  0/18 [mpmath]
   ----------------------------------------  0/18 [mpmath]
   ----------------------------------------  0/18 [mpmath]
   ----------------------------------------  0/18 [mpmath]
   ----------------------------------------  0/18 [mpmath]
   ----------------------------------------  0/18 [mpmath]
   ----------------------------------------  0/18 [mpmath]
   ----------------------------------------  0/18 [mpmath]
   ----------------------------------------  0/18 [mpmath]
   ----------------------------------------  0/18 [mpmath]
   ----------------------------------------  0/18 [mpmath]
   -- -------------------------------------  1/18 [tqdm]
   -- -------------------------------------  1/18 [tqdm]
   -- -------------------------------------  1/18 [tqdm]
   -- -------------------------------------  1/18 [tqdm]
   -- -------------------------------------  1/18 [tqdm]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]
   ------ ---------------------------------  3/18 [sympy]

In [11]:
from sentence_transformers import SentenceTransformer

embedding_provider = SentenceTransformer("all-MiniLM-L6-v2")  # 384 Dimensionen

# Beispiel:
text = "Portenta C33 is a microcontroller board."
vector = embedding_provider.encode(text).tolist()
print(len(vector))  # -> 384

c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

384

In [12]:
from langchain_community.embeddings import HuggingFaceEmbeddings

embedding_provider = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vector = embedding_provider.embed_query("Portenta C33 is a microcontroller board.")
print(len(vector))  # -> 384

c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\langchain_core\_api\deprecation.py:27: UserWarning: Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater.
  from pydantic.v1.fields import FieldInfo as FieldInfoV1
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_8724\3558486264.py:3: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embedding_provider = HuggingFaceEmbeddings(

384

In [12]:
from pathlib import Path
import pandas as p
# Projektwurzel robuster finden: gehe von der aktuellen Arbeitsdir nach oben,
# bis ein 'main' Ordner existiert.
cur = Path.cwd().resolve()
candidates = [cur, *cur.parents]
project_root = next(p for p in candidates if (p / "main").exists())
#C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\knowledeg_graph\experiments\kg_rebel_test.ipynb
json_path = (project_root / "main" / "ressources" / "knowledge_graph" /
             "neo4j" / "neo4j" / "import" / "docling_chunks.jsonl")

json_path_2 = (project_root / "main" / "knowledeg_graph" / "experiments" / "docling_chunks_portentac33.jsonl")

print("Pfad:", json_path_2)
print("Existiert?", json_path_2.exists())

output_file_name = "entities_relations_portentac33.json"


df = p.read_json(Path(json_path), lines=True)

df_2 = p.read_json(Path(json_path_2), lines=True)
df_2.head(2)

Pfad: C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\knowledeg_graph\experiments\docling_chunks_portentac33.jsonl
Existiert? True

,category,chunk_id,chunk_size,chunk_type,product,section,semantic_density,text,total_chunks,element,tutorial
0,Portenta Family,Microcontroller Renesas R7FA6M5BH2CBG::c0,127,contextualized,Portenta C33,NaN,0.2326,[Product: Portenta C33] [Category: Portenta Fa...,310,NaN,NaN
1,Portenta Family,Microcontroller Renesas R7FA6M5BH2CBG::c1,116,contextualized,Portenta C33,NaN,0.2886,[Product: Portenta C33] [Category: Portenta Fa...,310,NaN,NaN

In [14]:
import os
import json
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

from langchain_community.graphs.neo4j_graph import Neo4jGraph
from langchain_experimental.graph_transformers import LLMGraphTransformer
from langchain_community.graphs.graph_document import Node, Relationship
from langchain.docstore.document import Document
from langchain_community.chat_models import ChatLlamaCpp
from langchain_community.embeddings import HuggingFaceEmbeddings

# ----------------------------
# 0) Einstellungen
# ----------------------------
# Ordner, der mehrere .jsonl-Dateien enthält (rekursiv durchsuchen)
BASE_DIR = Path(r"C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\out")

# LLM (lokales Qwen-GGUF via ChatLlamaCpp)
llm = ChatLlamaCpp(
    model_path=r"C:\models\qwen2.5-7b-instruct-q3_k_m.gguf",
    temperature=0,
    n_ctx=4096,
    n_threads=4,
    n_gpu_layers=0
)

# Lokale Embeddings (all-MiniLM-L6-v2 -> 384 Dimensionen)
embedding_provider = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)
EMBED_DIM = 384  # wichtig: zum Vector Index passend

graph = Neo4jGraph(
    url="bolt://localhost:7687",    # oder neo4j+s://<id>.databases.neo4j.io für Aura
    username="neo4j",
    password="testmaster123"
)

doc_transformer = LLMGraphTransformer(llm=llm)

Exception ignored while calling ctypes callback function <function llama_log_callback at 0x000001EE1316FD70>:
Traceback (most recent call last):
  File "c:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\.venv\Lib\site-packages\llama_cpp\_logger.py", line 29, in llama_log_callback
    @llama_cpp.llama_log_callback
KeyboardInterrupt:
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = qwen2.5-7b-instruct
llama_model_loader: - kv   3:                            general.version str              = v0.1
llama_model_loader: - kv   4:                           general.finetune str              = qwen2.5-7b-instruct
llama_model_loader: - kv   5:                         general.size_label str              = 7.6B
llama_model_loader: - kv   6:                          qwen2.block_count u32              = 28
llama_model_loader: - kv   7:                       qwen2.context_length u32              = 131072
llama_model_loader: - kv   8:                     qwen2.embedding_length u32              = 3584
llama_model_loader: - kv   9:                  qwen2.feed_forward_length u32              = 18944
llama_model_loader: - kv  10:                 qwen2.attention.head_count u32              = 28
llama_model_loader: - kv  11:              qwen2.attention.head_count_kv u32              = 4
llama_model_loader: - kv  12:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  13:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  14:                          general.file_type u32              = 12
llama_model_loader: - kv  15:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  16:                         tokenizer.ggml.pre str              = qwen2
llama_model_loader: - kv  17:                      tokenizer.ggml.tokens arr[str,152064]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  18:                  tokenizer.ggml.token_type arr[i32,152064]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  19:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  22:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  23:               tokenizer.ggml.add_bos_token bool             = false
llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
llama_model_loader: - kv  25:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  141 tensors
llama_model_loader: - type q3_K:  113 tensors
llama_model_loader: - type q4_K:   81 tensors
llama_model_loader: - type q5_K:    3 tensors
llama_model_loader: - type q6_K:    1 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q3_K - Medium
print_info: file size   = 3.54 GiB (3.99 BPW)
init_tokenizer: initializing tokenizer for type 2
load: control token: 151661 '<|fim_suffix|>' is not marked as EOG
load: control token: 151649 '<|box_end|>' is not marked as EOG
load: control token: 151647 '<|object_ref_end|>' is not marked as EOG
load: control token: 151654 '<|vision_pad|>' is not marked as EOG
load: control token: 151659 '<|fim_prefix|>' is not marked as EOG
load: control token: 151648 '<|box_start|>' is not marked as EOG
load: control token: 151644 '<|im_start|>' is not marked as EOG
load: control token: 151646 '<|object_ref_start|>' is not marked as EOG
load: control token: 151650 '<|quad_start|>' is not marked as EOG
load: control token: 151651 '<|quad_end|>' is not marked as EOG
load: control token: 151652 '<|vision_start|>' is not marked as EOG
load: control token: 151653 '<|vision_end|>' is not marked as EOG
load: control token: 151655 '<|image_pad|>' is not marked as EOG
load: control token: 151656 '<|video_pad|>' is not marked as EOG
load: control token: 151660 '<|fim_middle|>' is not marked as EOG
load: printing all EOG tokens:
load:   - 151643 ('<|endoftext|>')
load:   - 151645 ('<|im_end|>')
load:   - 151662 ('<|fim_pad|>')
load:   - 151663 ('<|repo_name|>')
load:   - 151664 ('<|file_sep|>')
load: special tokens cache size = 22
load: token to piece cache size = 0.9310 MB
print_info: arch             = qwen2
print_info: vocab_only       = 0
print_info: n_ctx_train      = 131072
print_info: n_embd           = 3584
print_info: n_layer          = 28
print_info: n_head           = 28
print_info: n_head_kv        = 4
print_info: n_rot            = 128
print_info: n_swa            = 0
print_info: is_swa_any       = 0
print_info: n_embd_head_k    = 128
print_info: n_embd_head_v    = 128
print_info: n_gqa            = 7
print_info: n_embd_k_gqa     = 512
print_info: n_embd_v_gqa     = 512
print_info: f_norm_eps       = 0.0e+00
print_info: f_norm_rms_eps   = 1.0e-06
print_info: f_clamp_kqv      = 0.0e+00
print_info: f_max_alibi_bias = 0.0e+00
print_info: f_logit_scale    = 0.0e+00
print_info: f_attn_scale     = 0.0e+00
print_info: n_ff             = 18944
print_info: n_expert         = 0
print_info: n_expert_used    = 0
print_info: causal attn      = 1
print_info: pooling type     = -1
print_info: rope type        = 2
print_info: rope scaling     = linear
print_info: freq_base_train  = 1000000.0
print_info: freq_scale_train = 1
print_info: n_ctx_orig_yarn  = 131072
print_info: rope_finetuned   = unknown
print_info: model type       = 7B
print_info: model params     = 7.62 B
print_info: general.name     = qwen2.5-7b-instruct
print_info: vocab type       = BPE
print_info: n_vocab          = 152064
print_info: n_merges         = 151387
print_info: BOS token        = 151643 '<|endoftext|>'
print_info: EOS token        = 151645 '<|im_end|>'
print_info: EOT token        = 151645 '<|im_end|>'
print_info: PAD token        = 151643 '<|endoftext|>'
print_info: LF token         = 198 'Ċ'
print_info: FIM PRE token    = 151659 '<|fim_prefix|>'
print_info: FIM SUF token    = 151661 '<|fim_suffix|>'
print_info: FIM MID token    = 151660 '<|fim_middle|>'
print_info: FIM PAD token    = 151662 '<|fim_pad|>'
print_info: FIM REP token    = 151663 '<|repo_name|>'
print_info: FIM SEP token    = 151664 '<|file_sep|>'
print_info: EOG token        = 151643 '<|endoftext|>'
print_info: EOG token        = 151645 '<|im_end|>'
print_info: EOG token        = 151662 '<|fim_pad|>'
print_info: EOG token        = 151663 '<|repo_name|>'
print_info: EOG token        = 151664 '<|file_sep|>'
print_info: max token length = 256
load_tensors: loading model tensors, this can take a while... (mmap = true)
load_tensors: layer   0 assigned to device CPU, is_swa = 0
load_tensors: layer   1 assigned to device CPU, is_swa = 0
load_tensors: layer   2 assigned to device CPU, is_swa = 0
load_tensors: layer   3 assigned to device CPU, is_swa = 0
load_tensors: layer   4 assigned to device CPU, is_swa = 0
load_tensors: layer   5 assigned to device CPU, is_swa = 0
load_tensors: layer   6 assigned to device CPU, is_swa = 0
load_tensors: layer   7 assigned to device CPU, is_swa = 0
load_tensors: layer   8 assigned to device CPU, is_swa = 0
load_tensors: layer   9 assigned to device CPU, is_swa = 0
load_tensors: layer  10 assigned to device CPU, is_swa = 0
load_tensors: layer  11 assigned to device CPU, is_swa = 0
load_tensors: layer  12 assigned to device CPU, is_swa = 0
load_tensors: layer  13 assigned to device CPU, is_swa = 0
load_tensors: layer  14 assigned to device CPU, is_swa = 0
load_tensors: layer  15 assigned to device CPU, is_swa = 0
load_tensors: layer  16 assigned to device CPU, is_swa = 0
load_tensors: layer  17 assigned to device CPU, is_swa = 0
load_tensors: layer  18 assigned to device CPU, is_swa = 0
load_tensors: layer  19 assigned to device CPU, is_swa = 0
load_tensors: layer  20 assigned to device CPU, is_swa = 0
load_tensors: layer  21 assigned to device CPU, is_swa = 0
load_tensors: layer  22 assigned to device CPU, is_swa = 0
load_tensors: layer  23 assigned to device CPU, is_swa = 0
load_tensors: layer  24 assigned to device CPU, is_swa = 0
load_tensors: layer  25 assigned to device CPU, is_swa = 0
load_tensors: layer  26 assigned to device CPU, is_swa = 0
load_tensors: layer  27 assigned to device CPU, is_swa = 0
load_tensors: layer  28 assigned to device CPU, is_swa = 0
load_tensors: tensor 'token_embd.weight' (q3_K) (and 257 others) cannot be used with preferred buffer type CPU_REPACK, using CPU instead
load_tensors:   CPU_REPACK model buffer size =  1201.92 MiB
load_tensors:   CPU_Mapped model buffer size =  3626.29 MiB
repack: repack tensor blk.0.attn_output.weight with q4_K_8x8
repack: repack tensor blk.1.attn_output.weight with q4_K_8x8
repack: repack tensor blk.1.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.2.attn_v.weight with q4_K_8x8
repack: repack tensor blk.2.attn_output.weight with q4_K_8x8
repack: repack tensor blk.2.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.3.attn_v.weight with q4_K_8x8
repack: repack tensor blk.3.attn_output.weight with q4_K_8x8
repack: repack tensor blk.3.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.4.attn_v.weight with q4_K_8x8
repack: repack tensor blk.4.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.4.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.5.attn_v.weight with q4_K_8x8
repack: repack tensor blk.5.attn_output.weight with q4_K_8x8
repack: repack tensor blk.5.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.6.attn_v.weight with q4_K_8x8
repack: repack tensor blk.6.attn_output.weight with q4_K_8x8
repack: repack tensor blk.6.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.7.attn_v.weight with q4_K_8x8
repack: repack tensor blk.7.attn_output.weight with q4_K_8x8
repack: repack tensor blk.7.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.8.attn_v.weight with q4_K_8x8
repack: repack tensor blk.8.attn_output.weight with q4_K_8x8
repack: repack tensor blk.8.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.9.attn_v.weight with q4_K_8x8
repack: repack tensor blk.9.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.9.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.10.attn_v.weight with q4_K_8x8
repack: repack tensor blk.10.attn_output.weight with q4_K_8x8
repack: repack tensor blk.10.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.11.attn_v.weight with q4_K_8x8
repack: repack tensor blk.11.attn_output.weight with q4_K_8x8
repack: repack tensor blk.11.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.12.attn_v.weight with q4_K_8x8
repack: repack tensor blk.12.attn_output.weight with q4_K_8x8
repack: repack tensor blk.12.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.13.attn_v.weight with q4_K_8x8
repack: repack tensor blk.13.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.13.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.14.attn_v.weight with q4_K_8x8
repack: repack tensor blk.14.attn_output.weight with q4_K_8x8
repack: repack tensor blk.14.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.15.attn_v.weight with q4_K_8x8
repack: repack tensor blk.15.attn_output.weight with q4_K_8x8
repack: repack tensor blk.15.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.16.attn_v.weight with q4_K_8x8
repack: repack tensor blk.16.attn_output.weight with q4_K_8x8
repack: repack tensor blk.16.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.17.attn_v.weight with q4_K_8x8
repack: repack tensor blk.17.attn_output.weight with q4_K_8x8
repack: repack tensor blk.17.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.18.attn_v.weight with q4_K_8x8
repack: repack tensor blk.18.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.18.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.19.attn_v.weight with q4_K_8x8
repack: repack tensor blk.19.attn_output.weight with q4_K_8x8
repack: repack tensor blk.19.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.20.attn_v.weight with q4_K_8x8
repack: repack tensor blk.20.attn_output.weight with q4_K_8x8
repack: repack tensor blk.20.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.21.attn_v.weight with q4_K_8x8
repack: repack tensor blk.21.attn_output.weight with q4_K_8x8
repack: repack tensor blk.21.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.22.attn_v.weight with q4_K_8x8
repack: repack tensor blk.22.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.22.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.23.attn_v.weight with q4_K_8x8
repack: repack tensor blk.23.attn_output.weight with q4_K_8x8
repack: repack tensor blk.23.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.24.attn_v.weight with q4_K_8x8
repack: repack tensor blk.24.attn_output.weight with q4_K_8x8
repack: repack tensor blk.24.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.25.attn_v.weight with q4_K_8x8
repack: repack tensor blk.25.attn_output.weight with q4_K_8x8
repack: repack tensor blk.25.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.26.attn_v.weight with q4_K_8x8
repack: repack tensor blk.26.attn_output.weight with q4_K_8x8
repack: repack tensor blk.26.ffn_down.weight with q4_K_8x8
.repack: repack tensor blk.27.attn_v.weight with q4_K_8x8
repack: repack tensor blk.27.attn_output.weight with q4_K_8x8
.repack: repack tensor blk.27.ffn_down.weight with q4_K_8x8
....................................................
llama_context: constructing llama_context
llama_context: n_batch is less than GGML_KQ_MASK_PAD - increasing to 64
llama_context: n_seq_max     = 1
llama_context: n_ctx         = 4096
llama_context: n_ctx_per_seq = 4096
llama_context: n_batch       = 64
llama_context: n_ubatch      = 8
llama_context: causal_attn   = 1
llama_context: flash_attn    = 0
llama_context: kv_unified    = false
llama_context: freq_base     = 10000.0
llama_context: freq_scale    = 1
llama_context: n_ctx_per_seq (4096) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
set_abort_callback: call
llama_context:        CPU  output buffer size =     0.58 MiB
create_memory: n_ctx = 4096 (padded)
llama_kv_cache_unified: layer   0: dev = CPU
llama_kv_cache_unified: layer   1: dev = CPU
llama_kv_cache_unified: layer   2: dev = CPU
llama_kv_cache_unified: layer   3: dev = CPU
llama_kv_cache_unified: layer   4: dev = CPU
llama_kv_cache_unified: layer   5: dev = CPU
llama_kv_cache_unified: layer   6: dev = CPU
llama_kv_cache_unified: layer   7: dev = CPU
llama_kv_cache_unified: layer   8: dev = CPU
llama_kv_cache_unified: layer   9: dev = CPU
llama_kv_cache_unified: layer  10: dev = CPU
llama_kv_cache_unified: layer  11: dev = CPU
llama_kv_cache_unified: layer  12: dev = CPU
llama_kv_cache_unified: layer  13: dev = CPU
llama_kv_cache_unified: layer  14: dev = CPU
llama_kv_cache_unified: layer  15: dev = CPU
llama_kv_cache_unified: layer  16: dev = CPU
llama_kv_cache_unified: layer  17: dev = CPU
llama_kv_cache_unified: layer  18: dev = CPU
llama_kv_cache_unified: layer  19: dev = CPU
llama_kv_cache_unified: layer  20: dev = CPU
llama_kv_cache_unified: layer  21: dev = CPU
llama_kv_cache_unified: layer  22: dev = CPU
llama_kv_cache_unified: layer  23: dev = CPU
llama_kv_cache_unified: layer  24: dev = CPU
llama_kv_cache_unified: layer  25: dev = CPU
llama_kv_cache_unified: layer  26: dev = CPU
llama_kv_cache_unified: layer  27: dev = CPU
llama_kv_cache_unified:        CPU KV buffer size =   224.00 MiB
llama_kv_cache_unified: size =  224.00 MiB (  4096 cells,  28 layers,  1/1 seqs), K (f16):  112.00 MiB, V (f16):  112.00 MiB
llama_context: enumerating backends
llama_context: backend_ptrs.size() = 1
llama_context: max_nodes = 2712
llama_context: worst-case: n_tokens = 8, n_seqs = 1, n_outputs = 0
graph_reserve: reserving a graph for ubatch with n_tokens =    8, n_seqs =  1, n_outputs =    8
graph_reserve: reserving a graph for ubatch with n_tokens =    1, n_seqs =  1, n_outputs =    1
graph_reserve: reserving a graph for ubatch with n_tokens =    8, n_seqs =  1, n_outputs =    8
llama_context:        CPU compute buffer size =     4.97 MiB
llama_context: graph nodes  = 1070
llama_context: graph splits = 1
CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 |

In [ ]:
# ----------------------------
# 1) Constraints (einmalig)
# ----------------------------
graph.query("""
CREATE CONSTRAINT product_category_id IF NOT EXISTS
FOR (pc:ProductCategory) REQUIRE pc.id IS UNIQUE;
""")
graph.query("""
CREATE CONSTRAINT product_id IF NOT EXISTS
FOR (p:Product) REQUIRE p.id IS UNIQUE;
""")
graph.query("""
CREATE CONSTRAINT chunk_id IF NOT EXISTS
FOR (c:Chunk) REQUIRE c.id IS UNIQUE;
""")

# ----------------------------
# 2) JSONL-Iterator (zeilen-sicher)
# ----------------------------
def iter_jsonl(path: Path):
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            yield json.loads(line)

# ----------------------------
# 3) Einzel-Chunk verarbeiten
# ----------------------------
def process_row(row: dict, fallback_idx: int):
    text = (row.get("text") or "").strip()
    if not text:
        return False

    product_category = (row.get("product_category") or "UNKNOWN_CATEGORY").strip()
    product          = (row.get("product") or "UNKNOWN_PRODUCT").strip()
    chunk_id         = (row.get("chunk_id") or f"chunk_{fallback_idx}").strip()

    section          = row.get("section")
    semantic_density = row.get("semantic_density")
    element          = row.get("element")
    tutorial         = row.get("tutorial")

    # 3a) Embedding berechnen
    embedding = embedding_provider.embed_query(text)

    # 3b) Knoten & Kanten upserten (Embedding direkt als Property setzen)
    graph.query("""
    MERGE (pc:ProductCategory {id: $pc_id})
    MERGE (p:Product {id: $p_id})
    MERGE (pc)-[:HAS_PRODUCT]->(p)

    MERGE (c:Chunk {id: $chunk_id})
      ON CREATE SET c.text = $text
    SET  c.section = $section,
         c.semantic_density = $semantic_density,
         c.element = $element,
         c.tutorial = $tutorial,
         c.textEmbedding = $embedding

    MERGE (p)<-[:PART_OF]-(c)
    """, {
        "pc_id": product_category,
        "p_id": product,
        "chunk_id": chunk_id,
        "text": text,
        "section": section,
        "semantic_density": semantic_density,
        "element": element,
        "tutorial": tutorial,
        "embedding": embedding
    })

    # 3c) Entities & Relations extrahieren und Chunk verknüpfen
    lc_doc = Document(
        page_content=text,
        metadata={
            "product_category": product_category,
            "product": product,
            "chunk_id": chunk_id,
            "section": section,
            "element": element,
            "tutorial": tutorial,
        }
    )
    graph_docs = doc_transformer.convert_to_graph_documents([lc_doc])

    if graph_docs:
        for gd in graph_docs:
            chunk_node = Node(id=chunk_id, type="Chunk")
            for node in gd.nodes:
                gd.relationships.append(
                    Relationship(source=chunk_node, target=node, type="HAS_ENTITY")
                )
        graph.add_graph_documents(graph_docs)

    return True

# ----------------------------
# 4) Alle .jsonl im Ordner verarbeiten
# ----------------------------

In [ ]:
def process_dir(base_dir: Path):
    files = sorted(base_dir.rglob("*.jsonl"))
    if not files:
        print(f"Keine .jsonl-Dateien in {base_dir} gefunden.")
        return 0

    processed = 0
    for f in files:
        print(f"\n=== Datei: {f} ===")
        for i, row in enumerate(iter_jsonl(f), start=1):
            ok = process_row(row, fallback_idx=i)
            if ok:
                processed += 1
            if i % 50 == 0:
                print(f"  ... {i} Zeilen in {f.name} verarbeitet")
    return processed

total = process_dir(BASE_DIR)

# ----------------------------
# 5) Vector Index passend zur Embedding-Dimension
# ----------------------------
graph.query(f"""
CREATE VECTOR INDEX chunkVector IF NOT EXISTS
FOR (c:Chunk) ON (c.textEmbedding)
OPTIONS {{
  indexConfig: {{
    `vector.dimensions`: {EMBED_DIM},
    `vector.similarity_function`: 'cosine'
  }}
}};
""")

print(f"\nDone. Processed {total} chunks aus {BASE_DIR}.\n")

In [3]:
from pathlib import Path
import pandas as p
BASE_DIR = Path(r"C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\out\Education\docling_chunks.jsonl")

In [4]:
df = p.read_json(Path(BASE_DIR), lines=True)


df.head(2)

,file_name,chunk_id,chunk_size,semantic_density,product_category,product,section,text
0,Braccio Carrier-datasheet.pdf,Braccio Carrier-datasheet::c0,66,0.1941,Education,Braccio Carrier,NaN,[Product: Braccio Carrier] [Product category: ...
1,Braccio Carrier-datasheet.pdf,Braccio Carrier-datasheet::c2,199,0.2584,Education,Braccio Carrier,NaN,[Product: Braccio Carrier] [Product category: ...

In [9]:
import os
import json
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

from langchain_community.graphs.neo4j_graph import Neo4jGraph
from langchain_experimental.graph_transformers import LLMGraphTransformer
from langchain_community.graphs.graph_document import Node, Relationship
from langchain.docstore.document import Document
from langchain_community.chat_models import ChatLlamaCpp
from langchain_community.embeddings import HuggingFaceEmbeddings

ModuleNotFoundError: No module named 'langchain.docstore'