In [ ]:
import pandas as pd
from pathlib import Path
import os

PROJECT_ROOT = Path(os.getenv("PROJECT_ROOT", Path.cwd())).expanduser().resolve()

# Input JSONL
INPUT_PATH = PROJECT_ROOT / "golden_answers_dataset.jsonl"

# Output JSONL
OUTPUT_PATH = PROJECT_ROOT / "golden_answers_dataset_filtered_rest.jsonl"

# Load
df = pd.read_json(INPUT_PATH, lines=True)

# Filter
keep_types = {"factual", "disambiguation", "reasoning"}
df_filtered = df[df["query_type"].isin(keep_types)].copy()


cols = ["id", "query_type", "question", "gold_answer"]
df_filtered = df_filtered[cols]

# Save as JSONL
df_filtered.to_json(OUTPUT_PATH, orient="records", lines=True, force_ascii=False)

print(f"Saved {len(df_filtered)} rows to: {OUTPUT_PATH}")

# Reload check
df_check = pd.read_json(OUTPUT_PATH, lines=True)
df_check.head()

Saved 90 rows to: C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\evaluation\evaluation_datasets\golden_answers_dataset_filtered_rest.jsonl

,id,query_type,question,gold_answer
0,1,factual,What is the pressure measurement range of the ...,The LPS22HB measures absolute pressure from 26...
1,2,factual,What is the humidity measurement range of the ...,The HS3003 measures relative humidity from 0% ...
2,6,factual,What is the maximum sampling rate of the BMP39...,The BMP390 supports a sampling rate of up to 2...
3,7,reasoning,Which board is more suitable for long-term sta...,"The Nicla Sense ME, because the BMP390 offers ..."
4,9,disambiguation,What does 'ANNA-B112' refer to on the Nicla bo...,"It is a module based on the nRF52832 SoC, acti..."

In [ ]:
import pandas as pd
from pathlib import Path
import os

PROJECT_ROOT = Path(os.getenv("PROJECT_ROOT", Path.cwd())).expanduser().resolve()

# Input JSONL
INPUT_PATH = PROJECT_ROOT / "golden_answers_dataset.jsonl"

# Output JSONL
OUTPUT_PATH = PROJECT_ROOT / "golden_answers_dataset_filtered_summary.jsonl"

# Load
df = pd.read_json(INPUT_PATH, lines=True)

# Filter
keep_types = {"summary"}
df_filtered = df[df["query_type"].isin(keep_types)].copy()


cols = ["id", "query_type", "question", "gold_answer"]
df_filtered = df_filtered[cols]

# Save as JSONL
df_filtered.to_json(OUTPUT_PATH, orient="records", lines=True, force_ascii=False)

print(f"Saved {len(df_filtered)} rows to: {OUTPUT_PATH}")

# Reload check
df_check = pd.read_json(OUTPUT_PATH, lines=True)
df_check.head()

Saved 40 rows to: C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\evaluation\evaluation_datasets\golden_answers_dataset_filtered_summary.jsonl

,id,query_type,question,gold_answer
0,5,summary,Summarize the functionality of the gesture det...,It uses four directional photodiodes and an IR...
1,10,summary,Summarize the environmental sensing capabiliti...,"The BME688 measures pressure, humidity, temper..."
2,20,summary,Provide a short summary of the sensing feature...,It includes a barometer/temperature sensor (LP...
3,32,summary,Summarize the sensing architecture of the Nicl...,It integrates a programmable BHI260 sensor hub...
4,43,summary,Provide a summary of the microphone system on ...,It includes a dual MEMS microphone (U2) sendin...

In [ ]:
import pandas as pd
from pathlib import Path
import os

PROJECT_ROOT = Path(os.getenv("PROJECT_ROOT", Path.cwd())).expanduser().resolve()

# Input JSONL
INPUT_PATH = PROJECT_ROOT / "golden_answers_dataset.jsonl"

# Output JSONL
OUTPUT_PATH = PROJECT_ROOT / "golden_answers_dataset_filtered.jsonl"

# Load
df = pd.read_json(INPUT_PATH, lines=True)

# Filter
keep_types = {"summary", "multi_hop"}
df_filtered = df[df["query_type"].isin(keep_types)].copy()

cols = ["id", "query_type", "question", "gold_answer"]
df_filtered = df_filtered[cols]

# Save as JSONL
df_filtered.to_json(OUTPUT_PATH, orient="records", lines=True, force_ascii=False)

print(f"Saved {len(df_filtered)} rows to: {OUTPUT_PATH}")

# Reload check
df_check = pd.read_json(OUTPUT_PATH, lines=True)
df_check.head()

Saved 70 rows to: C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\evaluation\evaluation_datasets\golden_answers_dataset_filtered.jsonl

,id,query_type,question,gold_answer
0,5,summary,Summarize the functionality of the gesture det...,It uses four directional photodiodes and an IR...
1,10,summary,Summarize the environmental sensing capabiliti...,"The BME688 measures pressure, humidity, temper..."
2,20,summary,Provide a short summary of the sensing feature...,It includes a barometer/temperature sensor (LP...
3,25,multi_hop,"Which board uses the Bosch BME688 sensor, and ...","The Nicla Sense ME uses the BME688, which supp..."
4,32,summary,Summarize the sensing architecture of the Nicl...,It integrates a programmable BHI260 sensor hub...

In [ ]:
import pandas as pd
from pathlib import Path
import os

PROJECT_ROOT = Path(os.getenv("PROJECT_ROOT", Path.cwd())).expanduser().resolve()

# Input JSONL
INPUT_PATH = PROJECT_ROOT / "golden_answers_dataset.jsonl"

# Output JSONL
OUTPUT_PATH = PROJECT_ROOT / "golden_answers_dataset_filtered_factual.jsonl"

# Load
df = pd.read_json(INPUT_PATH, lines=True)

# Filter
keep_types = {"disambiguation", "factual"}
df_filtered = df[df["query_type"].isin(keep_types)].copy()


cols = ["id", "query_type", "question", "gold_answer"]
df_filtered = df_filtered[cols]

# Save as JSONL
df_filtered.to_json(OUTPUT_PATH, orient="records", lines=True, force_ascii=False)

print(f"Saved {len(df_filtered)} rows to: {OUTPUT_PATH}")

# Reload check
df_check = pd.read_json(OUTPUT_PATH, lines=True)
df_check.head()

Saved 60 rows to: C:\Users\Nasiba\Documents\1 Master Data Science\Master Thesis\VS Code New\master_thesis-rag\main\evaluation\evaluation_datasets\golden_answers_dataset_filtered_factual.jsonl

,id,query_type,question,gold_answer
0,1,factual,What is the pressure measurement range of the ...,The LPS22HB measures absolute pressure from 26...
1,2,factual,What is the humidity measurement range of the ...,The HS3003 measures relative humidity from 0% ...
2,6,factual,What is the maximum sampling rate of the BMP39...,The BMP390 supports a sampling rate of up to 2...
3,9,disambiguation,What does 'ANNA-B112' refer to on the Nicla bo...,"It is a module based on the nRF52832 SoC, acti..."
4,11,factual,What temperature accuracy does the HS3003 prov...,It provides a temperature accuracy of ±0.1 °C.

In [ ]:
import pandas as pd
from pathlib import Path
import os

PROJECT_ROOT = Path(os.getenv("PROJECT_ROOT", Path.cwd())).expanduser().resolve()

# Input JSONL
INPUT_PATH = PROJECT_ROOT / "golden_answers_dataset.jsonl"

# Output JSONL
OUTPUT_PATH = PROJECT_ROOT / "golden_answers_dataset_llmaindex_missing.jsonl"

# Load
df = pd.read_json(INPUT_PATH, lines=True)

# Filter
keep_types = {"summary", "multi_hop"}
df_filtered = df[df["query_type"].isin(keep_types)].copy()


cols = ["id", "query_type", "question", "gold_answer"]
df_filtered = df_filtered[cols]

# Save as JSONL
df_filtered.to_json(OUTPUT_PATH, orient="records", lines=True, force_ascii=False)

print(f"Saved {len(df_filtered)} rows to: {OUTPUT_PATH}")

# Reload check
df_check = pd.read_json(OUTPUT_PATH, lines=True)
df_check.head()