In [1]:






import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH14 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_filtered_rest_rows_1_to_90.csv"
)


CSV_PATH_NEW14 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH14))).expanduser().resolve()
df_new_14 = pd.read_csv(CSV_PATH_NEW14)

In [2]:




import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH13 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_filtered_rows_1_to_140.csv"
)


CSV_PATH_NEW13 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH13))).expanduser().resolve()
df_new_13 = pd.read_csv(CSV_PATH_NEW13)

In [3]:


import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH12 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_summary_rows_1_to_43.csv"
)


CSV_PATH_NEW12 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH12))).expanduser().resolve()
df_new_12 = pd.read_csv(CSV_PATH_NEW12)

In [4]:


import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH11 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_llmaindex_missing_rows_1_to_76.csv"
)


CSV_PATH_NEW11 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH11))).expanduser().resolve()
df_new_11 = pd.read_csv(CSV_PATH_NEW11)

In [5]:


import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH10 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_filtered_simplekg_rows_1_to_84.csv"
)
JUDGE_PATH10

CSV_PATH_NEW10 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH10))).expanduser().resolve()
df_new_10 = pd.read_csv(CSV_PATH_NEW10)

In [6]:

import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH9 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_empty_responses_rows_1_to_40.csv"
)


CSV_PATH_NEW9 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH9))).expanduser().resolve()
df_new_9 = pd.read_csv(CSV_PATH_NEW9)

In [7]:




import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH8 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_llmaindex_nonempty_rows_1_to_50.csv"
)


CSV_PATH_NEW8 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH8))).expanduser().resolve()
df_new_8 = pd.read_csv(CSV_PATH_NEW8)

In [8]:



import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH7 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_part4_rows_1_to_370.csv"
)


CSV_PATH_NEW7 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH7))).expanduser().resolve()
df_new_7 = pd.read_csv(CSV_PATH_NEW7)

In [9]:




import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH6 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_part3_rows_1_to_299.csv"
)


CSV_PATH_NEW6 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH6))).expanduser().resolve()
df_new_6 = pd.read_csv(CSV_PATH_NEW6)

In [10]:



import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH5 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_part2_rows_1_to_400.csv"
)


CSV_PATH_NEW5 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH5))).expanduser().resolve()
df_new_5 = pd.read_csv(CSV_PATH_NEW5)

In [11]:

import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH4 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_rows_1_to_500.csv"
)


CSV_PATH_NEW4 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH4))).expanduser().resolve()
df_new_4 = pd.read_csv(CSV_PATH_NEW4)

In [12]:
import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH3 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_rows_1_to_402.csv"
)


CSV_PATH_NEW3 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH3))).expanduser().resolve()
df_new_3 = pd.read_csv(CSV_PATH_NEW3)

In [13]:
import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH2 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_rows_1_to_289.csv"
)


CSV_PATH_NEW2 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH2))).expanduser().resolve()
df_new_2 = pd.read_csv(CSV_PATH_NEW2)

In [14]:
import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_rows_1_to_400.csv"
)


CSV_PATH_NEW =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH))).expanduser().resolve()
df_new_1 = pd.read_csv(CSV_PATH_NEW)

In [15]:
df_new = (
    pd.concat(
        [df_new_14, df_new_13, df_new_12, df_new_11, df_new_10,df_new_9, df_new_8,df_new_7, df_new_6, df_new_5, df_new_4, df_new_3, df_new_2, df_new_1],
        axis=0
    )
    .drop_duplicates()
)

In [16]:
df_new["script"] = df_new["script"].replace({
    "SimpleKG_Hybrid_KG_Retriever": "SimpleKG_Hybrid_Retriever"
})

df_new["script"] = df_new["script"].replace({
    "LlamaIndex_Dense_KG": "LlamaIndex_Dense"
})

In [17]:
rows_per_script = df_new.groupby("script").size()
print(rows_per_script)
# LlamaIndex_Dense_KG
# Community_Vector_Retriever_HyDE

script
Community_Vector_Retriever_HyDE      160
LLMGraph_Dense                       190
LLMGraph_Hybrid                      380
LLMGraph_Hybrid_Community            190
LlamaIndex_Dense                     260
LlamaIndex_Dense_Community_Rerank    143
LlamaIndex_Hybrid_Rerank             189
RAG_Advanced_Dense                   190
RAG_Advanced_Hybrid                  190
RAG_Advanced_Sparse                  192
RAG_Naive_Hybrid                     190
SimpleKG_Dense                       192
SimpleKG_Hybrid                      230
SimpleKG_Hybrid_Community_Rerank     190
SimpleKG_Hybrid_Rerank               294
SimpleKG_Vector_KG_Retriever           3
dtype: int64

In [18]:
df4= df_new[df_new["script"] == "LlamaIndex_Dense"]
import pandas as pd



# 1) Priorität für correctness_category festlegen (höher = besser)
# TP soll gewinnen, danach FP, danach alles andere
category_rank = {"TP": 2, "FP": 1}

df4["correctness_rank"] = df4["correctness_category"].map(category_rank).fillna(0).astype(int)

# 2) Scores robust in Zahlen umwandeln (falls sie als Strings vorliegen)
df4["faithfulness_1to5"] = pd.to_numeric(df4["faithfulness_1to5"], errors="coerce").fillna(-1)
df4["answer_relevance_1to5"] = pd.to_numeric(df4["answer_relevance_1to5"], errors="coerce").fillna(-1)
# (Optional) weiterer Tie-Breaker, falls du willst:
df4["helpfulness_final_1to5"] = pd.to_numeric(df4["helpfulness_final_1to5"], errors="coerce").fillna(-1)

# 3) Sortieren: pro (script, question_id) die beste Zeile nach Ranking zuerst
df_sorted4 = df4.sort_values(
    by=[
        "script",
        "question_id",
        "correctness_rank",      # TP > FP > Rest
        "faithfulness_1to5",     # höher besser
        "answer_relevance_1to5", # höher besser
        "helpfulness_final_1to5" # optional tie-breaker
    ],
    ascending=[True, True, False, False, False, False],
)

# 4) Pro (script, question_id) nur die erste (beste) Zeile behalten
df_best4 = df_sorted4.drop_duplicates(subset=["script", "question_id"], keep="first")

C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1115564105.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4["correctness_rank"] = df4["correctness_category"].map(category_rank).fillna(0).astype(int)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1115564105.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4["faithfulness_1to5"] = pd.to_numeric(df4["faithfulness_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1115564105.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4["answer_relevance_1to5"] = pd.to_numeric(df4["answer_relevance_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1115564105.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4["helpfulness_final_1to5"] = pd.to_numeric(df4["helpfulness_final_1to5"], errors="coerce").fillna(-1)

In [19]:
df3= df_new[df_new["script"] == "SimpleKG_Hybrid_Rerank"]
import pandas as pd



# 1) Priorität für correctness_category festlegen (höher = besser)
# TP soll gewinnen, danach FP, danach alles andere
category_rank = {"TP": 2, "FP": 1}

df3["correctness_rank"] = df3["correctness_category"].map(category_rank).fillna(0).astype(int)

# 2) Scores robust in Zahlen umwandeln (falls sie als Strings vorliegen)
df3["faithfulness_1to5"] = pd.to_numeric(df3["faithfulness_1to5"], errors="coerce").fillna(-1)
df3["answer_relevance_1to5"] = pd.to_numeric(df3["answer_relevance_1to5"], errors="coerce").fillna(-1)
# (Optional) weiterer Tie-Breaker, falls du willst:
df3["helpfulness_final_1to5"] = pd.to_numeric(df3["helpfulness_final_1to5"], errors="coerce").fillna(-1)

# 3) Sortieren: pro (script, question_id) die beste Zeile nach Ranking zuerst
df_sorted3 = df3.sort_values(
    by=[
        "script",
        "question_id",
        "correctness_rank",      # TP > FP > Rest
        "faithfulness_1to5",     # höher besser
        "answer_relevance_1to5", # höher besser
        "helpfulness_final_1to5" # optional tie-breaker
    ],
    ascending=[True, True, False, False, False, False],
)

# 4) Pro (script, question_id) nur die erste (beste) Zeile behalten
df_best3 = df_sorted3.drop_duplicates(subset=["script", "question_id"], keep="first")

C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\2523977324.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["correctness_rank"] = df3["correctness_category"].map(category_rank).fillna(0).astype(int)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\2523977324.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["faithfulness_1to5"] = pd.to_numeric(df3["faithfulness_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\2523977324.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["answer_relevance_1to5"] = pd.to_numeric(df3["answer_relevance_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\2523977324.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["helpfulness_final_1to5"] = pd.to_numeric(df3["helpfulness_final_1to5"], errors="coerce").fillna(-1)

In [20]:
df2= df_new[df_new["script"] == "SimpleKG_Hybrid"]
import pandas as pd



# 1) Priorität für correctness_category festlegen (höher = besser)
# TP soll gewinnen, danach FP, danach alles andere
category_rank = {"TP": 2, "FP": 1}

df2["correctness_rank"] = df2["correctness_category"].map(category_rank).fillna(0).astype(int)

# 2) Scores robust in Zahlen umwandeln (falls sie als Strings vorliegen)
df2["faithfulness_1to5"] = pd.to_numeric(df2["faithfulness_1to5"], errors="coerce").fillna(-1)
df2["answer_relevance_1to5"] = pd.to_numeric(df2["answer_relevance_1to5"], errors="coerce").fillna(-1)
# (Optional) weiterer Tie-Breaker, falls du willst:
df2["helpfulness_final_1to5"] = pd.to_numeric(df2["helpfulness_final_1to5"], errors="coerce").fillna(-1)

# 3) Sortieren: pro (script, question_id) die beste Zeile nach Ranking zuerst
df_sorted2 = df2.sort_values(
    by=[
        "script",
        "question_id",
        "correctness_rank",      # TP > FP > Rest
        "faithfulness_1to5",     # höher besser
        "answer_relevance_1to5", # höher besser
        "helpfulness_final_1to5" # optional tie-breaker
    ],
    ascending=[True, True, False, False, False, False],
)

# 4) Pro (script, question_id) nur die erste (beste) Zeile behalten
df_best2 = df_sorted2.drop_duplicates(subset=["script", "question_id"], keep="first")

C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1010867016.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["correctness_rank"] = df2["correctness_category"].map(category_rank).fillna(0).astype(int)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1010867016.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["faithfulness_1to5"] = pd.to_numeric(df2["faithfulness_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1010867016.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["answer_relevance_1to5"] = pd.to_numeric(df2["answer_relevance_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1010867016.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["helpfulness_final_1to5"] = pd.to_numeric(df2["helpfulness_final_1to5"], errors="coerce").fillna(-1)

In [21]:
df= df_new[df_new["script"] == "LLMGraph_Hybrid"]
import pandas as pd



# 1) Priorität für correctness_category festlegen (höher = besser)
# TP soll gewinnen, danach FP, danach alles andere
category_rank = {"TP": 2, "FP": 1}

df["correctness_rank"] = df["correctness_category"].map(category_rank).fillna(0).astype(int)

# 2) Scores robust in Zahlen umwandeln (falls sie als Strings vorliegen)
df["faithfulness_1to5"] = pd.to_numeric(df["faithfulness_1to5"], errors="coerce").fillna(-1)
df["answer_relevance_1to5"] = pd.to_numeric(df["answer_relevance_1to5"], errors="coerce").fillna(-1)

# (Optional) weiterer Tie-Breaker, falls du willst:
df["helpfulness_final_1to5"] = pd.to_numeric(df["helpfulness_final_1to5"], errors="coerce").fillna(-1)

# 3) Sortieren: pro (script, question_id) die beste Zeile nach Ranking zuerst
df_sorted = df.sort_values(
    by=[
        "script",
        "question_id",
        "correctness_rank",      # TP > FP > Rest
        "faithfulness_1to5",     # höher besser
        "answer_relevance_1to5", # höher besser
        "helpfulness_final_1to5" # optional tie-breaker
    ],
    ascending=[True, True, False, False, False, False],
)

# 4) Pro (script, question_id) nur die erste (beste) Zeile behalten
df_best = df_sorted.drop_duplicates(subset=["script", "question_id"], keep="first")

C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1181950045.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["correctness_rank"] = df["correctness_category"].map(category_rank).fillna(0).astype(int)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1181950045.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["faithfulness_1to5"] = pd.to_numeric(df["faithfulness_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1181950045.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["answer_relevance_1to5"] = pd.to_numeric(df["answer_relevance_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26780\1181950045.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["helpfulness_final_1to5"] = pd.to_numeric(df["helpfulness_final_1to5"], errors="coerce").fillna(-1)

In [22]:
check = df_best.groupby(["script", "question_id"]).size().value_counts()
print(check)
check2 = df_best2.groupby(["script", "question_id"]).size().value_counts()
print(check2)

1    190
Name: count, dtype: int64
1    190
Name: count, dtype: int64

In [23]:
df_newest = df_new[df_new["script"] != "LLMGraph_Hybrid"]
df_newest2 = df_newest[df_newest["script"] != "SimpleKG_Hybrid"] 
df_newest3 = df_newest2[df_newest2["script"] != "SimpleKG_Hybrid_Rerank"] 
df_newest4 = df_newest3[df_newest3["script"] != "LlamaIndex_Dense"] 


df_newest_combi = (
    pd.concat(
        [df_newest4,df_best4, df_best3,df_best2, df_best ],
        axis=0
    )
    .drop_duplicates()
)
df_newest_combi=  df_newest_combi[df_newest_combi["query_type"] != "relational"]
df_newest_combi["script"] = df_newest_combi["script"].replace({
    "LlamaIndex_Dense_Community_Rerank": "LlamaIndex_Hybrid_Community"
})
df_newest_combi["script"] = df_newest_combi["script"].replace({
    "SimpleKG_Hybrid_Community_Rerank": "SimpleKG_Hybrid_Community"
})
df_newest_combi["script"] = df_newest_combi["script"].replace({
    "Community_Vector_Retriever_HyDE": "LlamaIndex_Community"
})

In [24]:
df_newest_combi = df_newest_combi.drop_duplicates(
    subset=["script", "question_id"],
    keep="first"
)
df_newest_combi = df_newest_combi[
    (df_newest_combi["script"] != "SimpleKG_Vector_KG_Retriever") &
    (df_newest_combi["script"] != "LlamaIndex_Hybrid_Community")
]

In [25]:
df_newest_combi.columns

Index(['script', 'question_id', 'query_type', 'answer_relevance_score',
       'answer_relevance_1to5', 'completeness_score', 'completeness_1to5',
       'correctness_category', 'correctness_coverage',
       'correctness_coverage_1to5', 'correctness_error_severity',
       'faithfulness_score', 'faithfulness_1to5', 'helpfulness_raw_1to5',
       'helpfulness_raw_score', 'helpfulness_final_score',
       'helpfulness_final_1to5', 'helpfulness_justification', 'metrics_json',
       'correctness_rank'],
      dtype='object')

In [26]:
counts = (
    df_newest_combi.groupby(["script", "correctness_error_severity"])
      .size()
      .unstack(fill_value=0)
)
print(counts)

correctness_error_severity  high  low  medium
script
LLMGraph_Dense                 7  143      10
LLMGraph_Hybrid               14  141       5
LLMGraph_Hybrid_Community     10  143       7
LlamaIndex_Community          16  134      10
LlamaIndex_Dense              14  141       5
LlamaIndex_Hybrid_Rerank      12  136      12
RAG_Advanced_Dense            22  129       9
RAG_Advanced_Hybrid           15  131      14
RAG_Advanced_Sparse           13  131      16
RAG_Naive_Hybrid              16  141       3
SimpleKG_Dense                16  136       8
SimpleKG_Hybrid               12  142       6
SimpleKG_Hybrid_Community      9  147       4
SimpleKG_Hybrid_Rerank        12  143       5

In [27]:
rows_per_script = df_newest_combi.groupby("script").size()
print(rows_per_script)

script
LLMGraph_Dense               160
LLMGraph_Hybrid              160
LLMGraph_Hybrid_Community    160
LlamaIndex_Community         160
LlamaIndex_Dense             160
LlamaIndex_Hybrid_Rerank     160
RAG_Advanced_Dense           160
RAG_Advanced_Hybrid          160
RAG_Advanced_Sparse          160
RAG_Naive_Hybrid             160
SimpleKG_Dense               160
SimpleKG_Hybrid              160
SimpleKG_Hybrid_Community    160
SimpleKG_Hybrid_Rerank       160
dtype: int64

In [28]:
import pandas as pd

# -------------------------------
# 0) Helpers / config
# -------------------------------
METRIC_COLS = {
    "Answer_Relevance": "answer_relevance_1to5",
    "Completeness": "completeness_1to5",
    
    "Helpfulness": "helpfulness_final_1to5",
}

CAT_COL = "correctness_category"
SCRIPT_COL = "script"
QTYPE_COL = "query_type"


# -------------------------------
# 1) Alle Metriken pro script (+ Counts TP/FP/FN/PARTIAL)
# -------------------------------
metrics_per_script = (
    df_newest_combi
    .groupby(SCRIPT_COL)
    .agg(
        Answer_Relevance=(METRIC_COLS["Answer_Relevance"], "mean"),
        Completeness=(METRIC_COLS["Completeness"], "mean"),
       
        Helpfulness=(METRIC_COLS["Helpfulness"], "mean"),
    )
    .round(2)
)

# correctness_category counts (TP/FP/FN/PARTIAL) pro script
cat_counts_per_script = (
    df_newest_combi
    .groupby(SCRIPT_COL)[CAT_COL]
    .value_counts(dropna=False)
    .unstack(fill_value=0)
)

# Optional: Spalten sicher in gewünschter Reihenfolge
for c in ["TP", "FP", "FN", "PARTIAL"]:
    if c not in cat_counts_per_script.columns:
        cat_counts_per_script[c] = 0
cat_counts_per_script = cat_counts_per_script[["TP", "FP", "FN", "PARTIAL"]]

summary_per_script = metrics_per_script.join(cat_counts_per_script)


summary_per_script

,Answer_Relevance,Completeness,Helpfulness,TP,FP,FN,PARTIAL
script,,,,,,,
LLMGraph_Dense,3.71,2.74,4.51,99,7,22,32
LLMGraph_Hybrid,3.79,2.99,4.31,118,12,11,19
LLMGraph_Hybrid_Community,3.70,3.02,4.22,108,10,14,28
LlamaIndex_Community,3.60,2.52,3.85,74,16,35,35
LlamaIndex_Dense,3.62,2.39,4.12,79,11,45,25
LlamaIndex_Hybrid_Rerank,3.70,3.02,4.60,104,12,14,30
RAG_Advanced_Dense,3.42,1.42,2.00,9,21,110,20
RAG_Advanced_Hybrid,3.75,2.88,4.56,99,15,10,36
RAG_Advanced_Sparse,3.78,2.95,4.63,102,12,8,38
RAG_Naive_Hybrid,2.40,1.39,2.26,16,16,104,24
SimpleKG_Dense,3.71,2.99,4.22,101,16,23,20
SimpleKG_Hybrid,3.76,2.83,4.28,111,12,17,20
SimpleKG_Hybrid_Community,3.77,2.88,4.19,119,9,17,15
SimpleKG_Hybrid_Rerank,3.79,3.12,4.27,116,9,13,22

In [35]:
cat_counts_per_script = (
    df_newest_combi
    .groupby(SCRIPT_COL)[CAT_COL]
    .value_counts(dropna=False)
    .unstack(fill_value=0)
)

for c in ["TP", "FP", "FN", "PARTIAL"]:
    if c not in cat_counts_per_script.columns:
        cat_counts_per_script[c] = 0

cat_counts_per_script = cat_counts_per_script[["TP", "FP", "FN", "PARTIAL"]]
# Gewicht für PARTIAL
PARTIAL_WEIGHT = 0.5

metrics_pr = cat_counts_per_script.copy()

metrics_pr["TP_soft"] = (
    metrics_pr["TP"] + PARTIAL_WEIGHT * metrics_pr["PARTIAL"]
)

metrics_pr["Precision"] = (
    metrics_pr["TP_soft"] /
    (metrics_pr["TP_soft"] + metrics_pr["FP"])
)

metrics_pr["Recall"] = (
    metrics_pr["TP_soft"] /
    (metrics_pr["TP_soft"] + metrics_pr["FN"])
)

metrics_pr[["Precision", "Recall"]] = (
    metrics_pr[["Precision", "Recall"]]
    .fillna(0)
    .round(3)
)

In [37]:
summary_per_script = (
    metrics_per_script
    .join(
        metrics_pr[["Precision", "Recall"]]
    )
)

summary_per_script

,Answer_Relevance,Completeness,Helpfulness,Precision,Recall
script,,,,,
LLMGraph_Dense,3.71,2.74,4.51,0.943,0.839
LLMGraph_Hybrid,3.79,2.99,4.31,0.914,0.921
LLMGraph_Hybrid_Community,3.70,3.02,4.22,0.924,0.897
LlamaIndex_Community,3.60,2.52,3.85,0.851,0.723
LlamaIndex_Dense,3.62,2.39,4.12,0.893,0.670
LlamaIndex_Hybrid_Rerank,3.70,3.02,4.60,0.908,0.895
RAG_Advanced_Dense,3.42,1.42,2.00,0.475,0.147
RAG_Advanced_Hybrid,3.75,2.88,4.56,0.886,0.921
RAG_Advanced_Sparse,3.78,2.95,4.63,0.910,0.938
RAG_Naive_Hybrid,2.40,1.39,2.26,0.636,0.212
SimpleKG_Dense,3.71,2.99,4.22,0.874,0.828
SimpleKG_Hybrid,3.76,2.83,4.28,0.910,0.877
SimpleKG_Hybrid_Community,3.77,2.88,4.19,0.934,0.882
SimpleKG_Hybrid_Rerank,3.79,3.12,4.27,0.934,0.907

In [30]:
# -------------------------------

# -------------------------------
def pivot_metric_by_script_and_query_type(
    df: pd.DataFrame,
    metric_name: str,
    aggfunc="mean",
    round_digits: int = 2,
) -> pd.DataFrame:
    """
    metric_name: one of
      - "Answer_Relevance"
      - "Completeness"
      - "Correctness"
      - "Helpfulness"
    """
    if metric_name not in METRIC_COLS:
        raise ValueError(f"Unknown metric_name='{metric_name}'. Use: {list(METRIC_COLS.keys())}")

    col = METRIC_COLS[metric_name]

    pivot = (
        df.pivot_table(
            index=SCRIPT_COL,
            columns=QTYPE_COL,
            values=col,
            aggfunc=aggfunc,
        )
        .round(round_digits)
        .sort_index()
    )
    return pivot


# Beispiel: eine Metrik auswählen
metric_name = "Answer_Relevance"  # <- hier jeweils ändern, z.B. "Correctness"
pivot_df = pivot_metric_by_script_and_query_type(df_newest_combi, metric_name)

print(f"\n=== Pivot: {metric_name} (rows=script, cols=query_type) ===")
pivot_df


# -------------------------------
# 3) Optional: Pivot der correctness_category Counts (TP/FP/FN/PARTIAL) je script x query_type
# -------------------------------

=== Pivot: Answer_Relevance (rows=script, cols=query_type) ===

query_type,disambiguation,factual,multi_hop,reasoning,summary
script,,,,,
LLMGraph_Dense,3.63,3.87,3.67,3.57,3.80
LLMGraph_Hybrid,3.73,4.13,3.67,3.57,3.85
LLMGraph_Hybrid_Community,3.60,3.87,3.53,3.73,3.75
LlamaIndex_Community,3.63,3.53,3.57,3.37,3.82
LlamaIndex_Dense,3.83,3.43,3.73,3.43,3.68
LlamaIndex_Hybrid_Rerank,3.57,3.97,3.73,3.50,3.72
RAG_Advanced_Dense,3.33,3.37,3.43,3.43,3.50
RAG_Advanced_Hybrid,3.80,4.00,3.57,3.77,3.65
RAG_Advanced_Sparse,3.73,4.03,3.53,3.80,3.78
RAG_Naive_Hybrid,2.53,1.67,2.97,2.60,2.28
SimpleKG_Dense,3.77,3.80,3.67,3.67,3.68
SimpleKG_Hybrid,3.87,4.07,3.70,3.43,3.75
SimpleKG_Hybrid_Community,3.90,4.03,3.57,3.57,3.78
SimpleKG_Hybrid_Rerank,3.83,4.17,3.63,3.60,3.75

In [33]:
# -------------------------------

# -------------------------------
def pivot_metric_by_script_and_query_type(
    df: pd.DataFrame,
    metric_name: str,
    aggfunc="mean",
    round_digits: int = 2,
) -> pd.DataFrame:
    """
    metric_name: one of
      - "Answer_Relevance"
      - "Completeness"
      - "Correctness"
      - "Helpfulness"
    """
    if metric_name not in METRIC_COLS:
        raise ValueError(f"Unknown metric_name='{metric_name}'. Use: {list(METRIC_COLS.keys())}")

    col = METRIC_COLS[metric_name]

    pivot = (
        df.pivot_table(
            index=SCRIPT_COL,
            columns=QTYPE_COL,
            values=col,
            aggfunc=aggfunc,
        )
        .round(round_digits)
        .sort_index()
    )
    return pivot


# Beispiel: eine Metrik auswählen
metric_name = "Completeness"  # <- hier jeweils ändern, z.B. "Correctness"
pivot_df = pivot_metric_by_script_and_query_type(df_newest_combi, metric_name)

print(f"\n=== Pivot: {metric_name} (rows=script, cols=query_type) ===")
pivot_df


# -------------------------------
# 3) Optional: Pivot der correctness_category Counts (TP/FP/FN/PARTIAL) je script x query_type
# -------------------------------

=== Pivot: Completeness (rows=script, cols=query_type) ===

query_type,disambiguation,factual,multi_hop,reasoning,summary
script,,,,,
LLMGraph_Dense,2.53,3.13,2.90,2.60,2.60
LLMGraph_Hybrid,2.80,3.50,2.77,3.00,2.92
LLMGraph_Hybrid_Community,3.43,3.57,2.77,2.90,2.60
LlamaIndex_Community,2.67,2.53,2.43,2.47,2.50
LlamaIndex_Dense,2.43,2.37,2.43,2.23,2.45
LlamaIndex_Hybrid_Rerank,2.77,3.47,3.30,2.90,2.78
RAG_Advanced_Dense,1.30,1.13,1.60,1.37,1.65
RAG_Advanced_Hybrid,3.23,3.23,3.07,2.50,2.50
RAG_Advanced_Sparse,3.07,3.60,2.97,2.50,2.70
RAG_Naive_Hybrid,1.57,1.03,1.60,1.37,1.40
SimpleKG_Dense,3.13,3.40,3.17,2.93,2.50
SimpleKG_Hybrid,3.00,3.20,3.17,2.60,2.35
SimpleKG_Hybrid_Community,2.90,3.30,3.07,2.70,2.52
SimpleKG_Hybrid_Rerank,2.97,3.53,3.27,3.07,2.85

In [34]:
# -------------------------------

# -------------------------------
def pivot_metric_by_script_and_query_type(
    df: pd.DataFrame,
    metric_name: str,
    aggfunc="mean",
    round_digits: int = 2,
) -> pd.DataFrame:
    """
    metric_name: one of
      - "Answer_Relevance"
      - "Completeness"
      - "Correctness"
      - "Helpfulness"
    """
    if metric_name not in METRIC_COLS:
        raise ValueError(f"Unknown metric_name='{metric_name}'. Use: {list(METRIC_COLS.keys())}")

    col = METRIC_COLS[metric_name]

    pivot = (
        df.pivot_table(
            index=SCRIPT_COL,
            columns=QTYPE_COL,
            values=col,
            aggfunc=aggfunc,
        )
        .round(round_digits)
        .sort_index()
    )
    return pivot


# Beispiel: eine Metrik auswählen
metric_name = "Helpfulness"  # <- hier jeweils ändern, z.B. "Correctness"
pivot_df = pivot_metric_by_script_and_query_type(df_newest_combi, metric_name)

print(f"\n=== Pivot: {metric_name} (rows=script, cols=query_type) ===")
pivot_df


# -------------------------------
# 3) Optional: Pivot der correctness_category Counts (TP/FP/FN/PARTIAL) je script x query_type
# -------------------------------

=== Pivot: Helpfulness (rows=script, cols=query_type) ===

query_type,disambiguation,factual,multi_hop,reasoning,summary
script,,,,,
LLMGraph_Dense,4.53,3.87,4.73,4.77,4.62
LLMGraph_Hybrid,4.27,4.33,4.27,4.27,4.40
LLMGraph_Hybrid_Community,4.23,4.20,4.33,4.20,4.15
LlamaIndex_Community,3.80,3.33,4.00,3.97,4.08
LlamaIndex_Dense,4.30,3.27,4.53,4.27,4.20
LlamaIndex_Hybrid_Rerank,4.77,4.07,4.90,4.60,4.65
RAG_Advanced_Dense,2.17,1.17,2.13,2.27,2.20
RAG_Advanced_Hybrid,4.80,4.67,4.40,4.53,4.45
RAG_Advanced_Sparse,4.70,4.87,4.53,4.33,4.70
RAG_Naive_Hybrid,2.57,1.23,3.00,2.57,2.00
SimpleKG_Dense,4.33,4.07,4.33,4.23,4.15
SimpleKG_Hybrid,4.57,4.20,4.37,4.10,4.20
SimpleKG_Hybrid_Community,4.30,4.10,4.17,4.20,4.18
SimpleKG_Hybrid_Rerank,4.23,4.20,4.40,4.17,4.32

In [40]:
import numpy as np

PARTIAL_WEIGHT = 0.5

soft_recall = (
    df_newest_combi
    .assign(
        TP=lambda d: (d[CAT_COL] == "TP").astype(int),
        FN=lambda d: (d[CAT_COL] == "FN").astype(int),
        PARTIAL=lambda d: (d[CAT_COL] == "PARTIAL").astype(int),
    )
    .groupby([SCRIPT_COL, QTYPE_COL], as_index=False)
    .agg(
        TP=("TP", "sum"),
        FN=("FN", "sum"),
        PARTIAL=("PARTIAL", "sum"),
    )
)

soft_recall["Recall_soft"] = (
    (soft_recall["TP"] + PARTIAL_WEIGHT * soft_recall["PARTIAL"])
    /
    (soft_recall["TP"] + soft_recall["FN"] + PARTIAL_WEIGHT * soft_recall["PARTIAL"])
)

soft_recall["Recall_soft"] = (
    soft_recall["Recall_soft"]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
    .round(3)
)

soft_recall = soft_recall[
    [SCRIPT_COL, QTYPE_COL, "Recall_soft"]
]

soft_recall_matrix = soft_recall.pivot(
    index=SCRIPT_COL,
    columns=QTYPE_COL,
    values="Recall_soft"
).fillna(0)

soft_recall_matrix

query_type,disambiguation,factual,multi_hop,reasoning,summary
script,,,,,
LLMGraph_Dense,0.843,0.719,0.958,0.891,0.810
LLMGraph_Hybrid,0.915,0.778,1.000,0.926,0.971
LLMGraph_Hybrid_Community,0.875,0.782,0.923,0.961,0.939
LlamaIndex_Community,0.684,0.472,0.796,0.750,0.877
LlamaIndex_Dense,0.702,0.424,0.918,0.725,0.642
LlamaIndex_Hybrid_Rerank,0.913,0.741,1.000,0.849,0.967
RAG_Advanced_Dense,0.095,0.033,0.240,0.167,0.207
RAG_Advanced_Hybrid,0.959,0.966,0.913,0.917,0.849
RAG_Advanced_Sparse,0.962,0.965,0.958,0.880,0.920
RAG_Naive_Hybrid,0.224,0.033,0.500,0.286,0.108
SimpleKG_Dense,0.846,0.745,0.927,0.880,0.750
SimpleKG_Hybrid,0.922,0.750,0.966,0.852,0.895
SimpleKG_Hybrid_Community,0.917,0.719,0.927,0.963,0.890
SimpleKG_Hybrid_Rerank,0.833,0.808,1.000,0.891,0.970

In [ ]:
import numpy as np

# counts pro (script, query_type) x correctness_category
cat_counts_script_qtype = (
    df_newest_combi
    .groupby([SCRIPT_COL, QTYPE_COL])[CAT_COL]
    .value_counts(dropna=False)
    .unstack(fill_value=0)
)

for c in ["TP", "FP", "FN", "PARTIAL"]:
    if c not in cat_counts_script_qtype.columns:
        cat_counts_script_qtype[c] = 0

cat_counts_script_qtype = cat_counts_script_qtype[["TP", "FP", "FN", "PARTIAL"]]

# --- HARD metrics ---
pr_hard = cat_counts_script_qtype.copy()

pr_hard["Precision_hard"] = pr_hard["TP"] / (pr_hard["TP"] + pr_hard["FP"])
pr_hard["Recall_hard"]    = pr_hard["TP"] / (pr_hard["TP"] + pr_hard["FN"])
pr_hard["F1_hard"]        = (
    2 * pr_hard["Precision_hard"] * pr_hard["Recall_hard"]
    / (pr_hard["Precision_hard"] + pr_hard["Recall_hard"])
)

pr_hard[["Precision_hard", "Recall_hard", "F1_hard"]] = (
    pr_hard[["Precision_hard", "Recall_hard", "F1_hard"]]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
    .round(3)
)

pr_hard

In [32]:
cat_counts_script_qtype = (
    df_newest_combi
    .groupby([SCRIPT_COL, QTYPE_COL])[CAT_COL]
    .value_counts(dropna=False)
    .unstack(fill_value=0)
)

for c in ["TP", "FP", "FN", "PARTIAL"]:
    if c not in cat_counts_script_qtype.columns:
        cat_counts_script_qtype[c] = 0
cat_counts_script_qtype = cat_counts_script_qtype[["TP", "FP", "FN", "PARTIAL"]]


tp_counts = (
    df_newest_combi
    .query(f"{CAT_COL} == 'TP'")
    .groupby([SCRIPT_COL, QTYPE_COL])
    .size()
    .unstack(fill_value=0)
)

tp_counts

query_type,disambiguation,factual,multi_hop,reasoning,summary
script,,,,,
LLMGraph_Dense,20,19,18,22,20
LLMGraph_Hybrid,21,20,24,24,29
LLMGraph_Hybrid_Community,19,20,21,21,27
LlamaIndex_Community,10,11,14,17,22
LlamaIndex_Dense,14,12,19,16,18
LlamaIndex_Hybrid_Rerank,19,19,23,21,22
RAG_Advanced_Dense,1,1,2,2,3
RAG_Advanced_Hybrid,22,27,16,20,14
RAG_Advanced_Sparse,23,26,18,19,16
RAG_Naive_Hybrid,4,1,7,3,1
SimpleKG_Dense,20,19,24,20,18
SimpleKG_Hybrid,23,20,27,22,19
SimpleKG_Hybrid_Community,21,19,25,25,29
SimpleKG_Hybrid_Rerank,18,19,28,22,29

In [27]:
df_newest_combi[
    df_newest_combi["script"] == "Community_Vector_Retriever_HyDE"
]["correctness_category"].value_counts()

correctness_category
TP         74
FN         35
PARTIAL    35
FP         16
Name: count, dtype: int64

In [28]:
counts = (
    df_newest_combi.groupby(["script", "correctness_category"])
      .size()
      .unstack(fill_value=0)
)

counts = counts.reindex(columns=["TP", "FP", "FN", "PARTIAL"], fill_value=0)

# nach Anzahl TP 
counts = counts.sort_values(by="TP", ascending=False)

print(counts)

correctness_category              TP  FP   FN  PARTIAL
script
SimpleKG_Hybrid_Community        119   9   17       15
LLMGraph_Hybrid                  118  12   11       19
SimpleKG_Hybrid_Rerank           116   9   13       22
SimpleKG_Hybrid                  111  12   17       20
LLMGraph_Hybrid_Community        108  10   14       28
LlamaIndex_Hybrid_Rerank         104  12   14       30
RAG_Advanced_Sparse              102  12    8       38
SimpleKG_Dense                   101  16   23       20
RAG_Advanced_Hybrid               99  15   10       36
LLMGraph_Dense                    99   7   22       32
LlamaIndex_Dense                  79  11   45       25
LlamaIndex_Hybrid_Community       76   7   20       13
Community_Vector_Retriever_HyDE   74  16   35       35
RAG_Naive_Hybrid                  16  16  104       24
RAG_Advanced_Dense                 9  21  110       20

In [30]:
tp_counts = (
    df_newest_combi[df_newest_combi["correctness_category"] == "TP"]
        .groupby(["script", "query_type"])
        .size()
        .unstack(fill_value=0)
)

# optional: nach summary-TP sortieren
tp_counts = tp_counts.sort_values(by="factual", ascending=False)

print(tp_counts.to_string())

query_type                       disambiguation  factual  multi_hop  reasoning  summary
script
RAG_Advanced_Hybrid                          22       27         16         20       14
RAG_Advanced_Sparse                          23       26         18         19       16
LLMGraph_Hybrid                              21       20         24         24       29
LLMGraph_Hybrid_Community                    19       20         21         21       27
SimpleKG_Hybrid                              23       20         27         22       19
LlamaIndex_Hybrid_Rerank                     19       19         23         21       22
LLMGraph_Dense                               20       19         18         22       20
SimpleKG_Hybrid_Community                    21       19         25         25       29
SimpleKG_Hybrid_Rerank                       18       19         28         22       29
SimpleKG_Dense                               20       19         24         20       18
LlamaIndex_Hybrid_Community                  14       18         13         15       16
LlamaIndex_Dense                             14       12         19         16       18
Community_Vector_Retriever_HyDE              10       11         14         17       22
RAG_Naive_Hybrid                              4        1          7          3        1
RAG_Advanced_Dense                            1        1          2          2        3

In [31]:
tp_counts = (
    df_newest_combi[df_newest_combi["correctness_category"] == "TP"]
        .groupby(["script", "query_type"])
        .size()
        .unstack(fill_value=0)
)

# optional: nach summary-TP sortieren
tp_counts = tp_counts.sort_values(by="summary", ascending=False)

print(tp_counts.to_string())

query_type                       disambiguation  factual  multi_hop  reasoning  summary
script
LLMGraph_Hybrid                              21       20         24         24       29
SimpleKG_Hybrid_Rerank                       18       19         28         22       29
SimpleKG_Hybrid_Community                    21       19         25         25       29
LLMGraph_Hybrid_Community                    19       20         21         21       27
Community_Vector_Retriever_HyDE              10       11         14         17       22
LlamaIndex_Hybrid_Rerank                     19       19         23         21       22
LLMGraph_Dense                               20       19         18         22       20
SimpleKG_Hybrid                              23       20         27         22       19
LlamaIndex_Dense                             14       12         19         16       18
SimpleKG_Dense                               20       19         24         20       18
LlamaIndex_Hybrid_Community                  14       18         13         15       16
RAG_Advanced_Sparse                          23       26         18         19       16
RAG_Advanced_Hybrid                          22       27         16         20       14
RAG_Advanced_Dense                            1        1          2          2        3
RAG_Naive_Hybrid                              4        1          7          3        1

In [34]:
tp_counts = (
    df_newest_combi[df_newest_combi["correctness_category"] == "TP"]
        .groupby(["script", "query_type"])
        .size()
        .unstack(fill_value=0)
)

# optional: nach summary-TP sortieren
tp_counts = tp_counts.sort_values(by="multi_hop", ascending=False)

print(tp_counts.to_string())

query_type                       disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                       18       19         28         22       29
SimpleKG_Hybrid                              23       20         27         22       19
SimpleKG_Hybrid_Community                    21       19         25         25       29
SimpleKG_Dense                               20       19         24         20       18
LLMGraph_Hybrid                              21       20         24         24       29
LlamaIndex_Hybrid_Rerank                     19       19         23         21       22
LLMGraph_Hybrid_Community                    19       20         21         21       27
LlamaIndex_Dense                             14       12         19         16       18
RAG_Advanced_Sparse                          23       26         18         19       16
LLMGraph_Dense                               20       19         18         22       20
RAG_Advanced_Hybrid                          22       27         16         20       14
Community_Vector_Retriever_HyDE              10       11         14         17       22
LlamaIndex_Hybrid_Community                  14       18         13         15       16
RAG_Naive_Hybrid                              4        1          7          3        1
RAG_Advanced_Dense                            1        1          2          2        3

In [35]:
tp_counts = (
    df_newest_combi[df_newest_combi["correctness_category"] == "TP"]
        .groupby(["script", "query_type"])
        .size()
        .unstack(fill_value=0)
)

# optional: nach summary-TP sortieren
tp_counts = tp_counts.sort_values(by="script", ascending=True)

print(tp_counts.to_string())

query_type                       disambiguation  factual  multi_hop  reasoning  summary
script
Community_Vector_Retriever_HyDE              10       11         14         17       22
LLMGraph_Dense                               20       19         18         22       20
LLMGraph_Hybrid                              21       20         24         24       29
LLMGraph_Hybrid_Community                    19       20         21         21       27
LlamaIndex_Dense                             14       12         19         16       18
LlamaIndex_Hybrid_Community                  14       18         13         15       16
LlamaIndex_Hybrid_Rerank                     19       19         23         21       22
RAG_Advanced_Dense                            1        1          2          2        3
RAG_Advanced_Hybrid                          22       27         16         20       14
RAG_Advanced_Sparse                          23       26         18         19       16
RAG_Naive_Hybrid                              4        1          7          3        1
SimpleKG_Dense                               20       19         24         20       18
SimpleKG_Hybrid                              23       20         27         22       19
SimpleKG_Hybrid_Community                    21       19         25         25       29
SimpleKG_Hybrid_Rerank                       18       19         28         22       29

In [36]:


cols = ["script",  "faithfulness_1to5", "answer_relevance_1to5","completeness_1to5","correctness_coverage_1to5" ,"helpfulness_final_1to5" ]
df_new_scores = df_newest_combi[cols].copy()



summary = (
    df_new_scores.groupby("script", as_index=False)
      .agg(
            Faithfulness=("faithfulness_1to5", "mean"),
            Answer_Relevance=("answer_relevance_1to5", "mean"),
            Completeness=("completeness_1to5", "mean"),
            Correctness=("correctness_coverage_1to5", "mean"),
            Helpfulness=("helpfulness_final_1to5", "mean"),
            )
)


summary_no_n = summary


summary_no_n = summary_no_n.set_index("script").round(2)

print(summary_no_n.to_string())

                                 Faithfulness  Answer_Relevance  Completeness  Correctness  Helpfulness
script
Community_Vector_Retriever_HyDE          3.80              3.60          2.52         3.20         3.85
LLMGraph_Dense                           4.64              3.71          2.74         3.85         4.51
LLMGraph_Hybrid                          4.03              3.79          2.99         4.12         4.31
LLMGraph_Hybrid_Community                3.84              3.70          3.02         4.02         4.22
LlamaIndex_Dense                         4.71              3.62          2.39         3.23         4.12
LlamaIndex_Hybrid_Community              4.66              3.66          2.95         3.84         4.47
LlamaIndex_Hybrid_Rerank                 4.71              3.70          3.02         3.95         4.60
RAG_Advanced_Dense                       4.24              3.42          1.42         1.44         2.00
RAG_Advanced_Hybrid                      4.77              3.75          2.88         3.89         4.56
RAG_Advanced_Sparse                      4.79              3.78          2.95         3.94         4.63
RAG_Naive_Hybrid                         4.29              2.40          1.39         1.69         2.26
SimpleKG_Dense                           4.06              3.71          2.99         3.72         4.22
SimpleKG_Hybrid                          4.04              3.76          2.83         3.96         4.28
SimpleKG_Hybrid_Community                3.68              3.77          2.88         4.09         4.19
SimpleKG_Hybrid_Rerank                   3.78              3.79          3.12         4.09         4.27

In [38]:
counts = (
    df_newest_combi.groupby(["script", "correctness_category"])
      .size()
      .unstack(fill_value=0)
)

counts = counts.reindex(columns=["TP", "FP", "FN", "PARTIAL"], fill_value=0)
final = counts.join(summary_no_n, how="left")
final = final.sort_values(by="script", ascending=True)
print(final.to_string())

                                  TP  FP   FN  PARTIAL  Faithfulness  Answer_Relevance  Completeness  Correctness  Helpfulness
script
Community_Vector_Retriever_HyDE   74  16   35       35          3.80              3.60          2.52         3.20         3.85
LLMGraph_Dense                    99   7   22       32          4.64              3.71          2.74         3.85         4.51
LLMGraph_Hybrid                  118  12   11       19          4.03              3.79          2.99         4.12         4.31
LLMGraph_Hybrid_Community        108  10   14       28          3.84              3.70          3.02         4.02         4.22
LlamaIndex_Dense                  79  11   45       25          4.71              3.62          2.39         3.23         4.12
LlamaIndex_Hybrid_Community       76   7   20       13          4.66              3.66          2.95         3.84         4.47
LlamaIndex_Hybrid_Rerank         104  12   14       30          4.71              3.70          3.02         3.95         4.60
RAG_Advanced_Dense                 9  21  110       20          4.24              3.42          1.42         1.44         2.00
RAG_Advanced_Hybrid               99  15   10       36          4.77              3.75          2.88         3.89         4.56
RAG_Advanced_Sparse              102  12    8       38          4.79              3.78          2.95         3.94         4.63
RAG_Naive_Hybrid                  16  16  104       24          4.29              2.40          1.39         1.69         2.26
SimpleKG_Dense                   101  16   23       20          4.06              3.71          2.99         3.72         4.22
SimpleKG_Hybrid                  111  12   17       20          4.04              3.76          2.83         3.96         4.28
SimpleKG_Hybrid_Community        119   9   17       15          3.68              3.77          2.88         4.09         4.19
SimpleKG_Hybrid_Rerank           116   9   13       22          3.78              3.79          3.12         4.09         4.27

In [67]:
df_newest_combi.columns

Index(['script', 'question_id', 'query_type', 'answer_relevance_score',
       'answer_relevance_1to5', 'completeness_score', 'completeness_1to5',
       'correctness_category', 'correctness_coverage',
       'correctness_coverage_1to5', 'correctness_error_severity',
       'faithfulness_score', 'faithfulness_1to5', 'helpfulness_raw_1to5',
       'helpfulness_raw_score', 'helpfulness_final_score',
       'helpfulness_final_1to5', 'helpfulness_justification', 'metrics_json',
       'correctness_rank'],
      dtype='object')

In [ ]:


cols = ["query_type",  "faithfulness_1to5", "answer_relevance_1to5","completeness_1to5","correctness_coverage_1to5" ,"helpfulness_final_1to5", "helpfulness_final_score" ]
df_new_scores = df_newest_combi[cols].copy()



summary = (
    df_new_scores.groupby("query_type", as_index=False)
      .agg(
         Faithfulness=("faithfulness_1to5", "mean"),
            Answer_Relevance=("answer_relevance_1to5", "mean"),
            Completeness=("completeness_1to5", "mean"),
      
            Helpfulness=("helpfulness_final_1to5", "mean"),
             )
)


summary_no_n = summary


summary_no_n = summary_no_n.set_index("query_type").round(2)

counts = (
    df_newest_combi.groupby(["query_type", "correctness_category"])
      .size()
      .unstack(fill_value=0)
)

counts = counts.reindex(columns=["TP", "FP", "FN", "PARTIAL"], fill_value=0)
final = counts.join(summary_no_n, how="left")
final = final.sort_values(by="query_type", ascending=True)
print(final.to_string())

                 TP  FP   FN  PARTIAL  Faithfulness  Answer_Relevance  Completeness  Helpfulness
query_type
disambiguation  249  64   78       50          4.34              3.63          2.72         4.14
factual         251  13  152       34          4.49              3.72          2.93         3.72
multi_hop       279  13   49       94          4.16              3.57          2.77         4.17
reasoning       269  36   79       59          4.03              3.49          2.51         4.05
summary         283  59  105      140          4.28              3.64          2.47         4.04

In [74]:
summary_by_query_type = (
    df_newest_combi
        .groupby("query_type", as_index=False)
        .agg(
        Faithfulness=("faithfulness_1to5", "mean"),
            Answer_Relevance=("answer_relevance_1to5", "mean"),
            Completeness=("completeness_1to5", "mean"),
            Correctness=("correctness_coverage_1to5", "mean"),
            Helpfulness=("helpfulness_final_1to5", "mean"),
            # N=("query_type", "size"),
        )
        .set_index("query_type")
        .round(2)
)


print(summary_by_query_type.to_string())

                Faithfulness  Answer_Relevance  Completeness  Correctness  Helpfulness
query_type
disambiguation          4.38              3.63          2.73         3.55         4.17
factual                 4.52              3.73          2.96         3.42         3.75
multi_hop               4.17              3.56          2.79         3.94         4.18
reasoning               4.08              3.50          2.52         3.61         4.05
summary                 4.28              3.63          2.44         3.31         4.03

In [40]:
summary_by_script_and_query = (
    df_newest_combi 
        .groupby(["script", "query_type"], as_index=False)
        .agg(
            Faithfulness=("faithfulness_1to5", "mean"),
            Answer_Relevance=("answer_relevance_1to5", "mean"),
            Completeness=("completeness_1to5", "mean"),
    
            Helpfulness=("helpfulness_final_1to5", "mean"),
            
        )
        .set_index(["script", "query_type"])
        .round(2)
)

counts = (
    df_newest_combi.groupby(["query_type", "script" ,"correctness_category"])
      .size()
      .unstack(fill_value=0)
)

counts = counts.reindex(columns=["TP", "FP", "FN", "PARTIAL"], fill_value=0)
final = counts.join(summary_no_n, how="left")
final = final.sort_values(by="query_type", ascending=True)
print(final.to_string())

                                                TP  FP  FN  PARTIAL  Faithfulness  Answer_Relevance  Completeness  Helpfulness
query_type     script
disambiguation Community_Vector_Retriever_HyDE  10   8   6        6          4.34              3.63          2.72         4.14
               SimpleKG_Hybrid_Rerank           18   4   4        4          4.34              3.63          2.72         4.14
               SimpleKG_Hybrid_Community        21   5   2        2          4.34              3.63          2.72         4.14
               SimpleKG_Hybrid                  23   4   2        1          4.34              3.63          2.72         4.14
               SimpleKG_Dense                   20   2   4        4          4.34              3.63          2.72         4.14
               RAG_Advanced_Sparse              23   1   1        5          4.34              3.63          2.72         4.14
               RAG_Advanced_Hybrid              22   4   1        3          4.34              3.63          2.72         4.14
               RAG_Naive_Hybrid                  4   4  19        3          4.34              3.63          2.72         4.14
               LlamaIndex_Hybrid_Rerank         19   5   2        4          4.34              3.63          2.72         4.14
               LlamaIndex_Hybrid_Community      14   2   2        3          4.34              3.63          2.72         4.14
               LlamaIndex_Dense                 14   4   7        5          4.34              3.63          2.72         4.14
               LLMGraph_Hybrid_Community        19   4   3        4          4.34              3.63          2.72         4.14
               LLMGraph_Hybrid                  21   6   2        1          4.34              3.63          2.72         4.14
               LLMGraph_Dense                   20   3   4        3          4.34              3.63          2.72         4.14
               RAG_Advanced_Dense                1   8  19        2          4.34              3.63          2.72         4.14
factual        RAG_Advanced_Sparse              26   0   1        3          4.49              3.72          2.93         3.72
               SimpleKG_Hybrid_Rerank           19   2   5        4          4.49              3.72          2.93         3.72
               SimpleKG_Hybrid_Community        19   0   8        3          4.49              3.72          2.93         3.72
               SimpleKG_Hybrid                  20   1   7        2          4.49              3.72          2.93         3.72
               SimpleKG_Dense                   19   1   7        3          4.49              3.72          2.93         3.72
               RAG_Naive_Hybrid                  1   0  29        0          4.49              3.72          2.93         3.72
               RAG_Advanced_Hybrid              27   0   1        2          4.49              3.72          2.93         3.72
               LLMGraph_Hybrid_Community        20   1   6        3          4.49              3.72          2.93         3.72
               LlamaIndex_Hybrid_Rerank         19   2   7        2          4.49              3.72          2.93         3.72
               LlamaIndex_Hybrid_Community      18   2   7        3          4.49              3.72          2.93         3.72
               LlamaIndex_Dense                 12   0  17        1          4.49              3.72          2.93         3.72
               LLMGraph_Hybrid                  20   2   6        2          4.49              3.72          2.93         3.72
               LLMGraph_Dense                   19   0   8        3          4.49              3.72          2.93         3.72
               Community_Vector_Retriever_HyDE  11   2  14        3          4.49              3.72          2.93         3.72
               RAG_Advanced_Dense                1   0  29        0          4.49              3.72          2.93         3.72
multi_hop      RAG_Advanced_Sparse              18   1   1       10          4.16              3.57          2.77         4.17
               SimpleKG_Hybrid_Rerank           28   0   0        2          4.16              3.57          2.77         4.17
               SimpleKG_Hybrid_Community        25   2   2        1          4.16              3.57          2.77         4.17
               SimpleKG_Hybrid                  27   0   1        2          4.16              3.57          2.77         4.17
               SimpleKG_Dense                   24   1   2        3          4.16              3.57          2.77         4.17
               RAG_Naive_Hybrid                  7   1  12       10          4.16              3.57          2.77         4.17
               RAG_Advanced_Hybrid              16   2   2       10          4.16              3.57          2.77         4.17
               RAG_Advanced_Dense                2   1  19        8          4.16              3.57          2.77         4.17
               LlamaIndex_Hybrid_Rerank         23   0   0        7          4.16              3.57          2.77         4.17
               LlamaIndex_Hybrid_Community      13   0   0        2          4.16              3.57          2.77         4.17
               LlamaIndex_Dense                 19   2   2        7          4.16              3.57          2.77         4.17
               LLMGraph_Hybrid_Community        21   1   2        6          4.16              3.57          2.77         4.17
               LLMGraph_Hybrid                  24   1   0        5          4.16              3.57          2.77         4.17
               LLMGraph_Dense                   18   1   1       10          4.16              3.57          2.77         4.17
               Community_Vector_Retriever_HyDE  14   0   5       11          4.16              3.57          2.77         4.17
reasoning      SimpleKG_Hybrid_Rerank           22   0   3        5          4.03              3.49          2.51         4.05
               SimpleKG_Hybrid_Community        25   2   1        2          4.03              3.49          2.51         4.05
               SimpleKG_Hybrid                  22   2   4        2          4.03              3.49          2.51         4.05
               RAG_Naive_Hybrid                  3   6  15        6          4.03              3.49          2.51         4.05
               RAG_Advanced_Sparse              19   2   3        6          4.03              3.49          2.51         4.05
               RAG_Advanced_Hybrid              20   4   2        4          4.03              3.49          2.51         4.05
               RAG_Advanced_Dense                2   4  20        4          4.03              3.49          2.51         4.05
               SimpleKG_Dense                   20   3   3        4          4.03              3.49          2.51         4.05
               LlamaIndex_Hybrid_Community      15   1   5        2          4.03              3.49          2.51         4.05
               LlamaIndex_Dense                 16   2   7        5          4.03              3.49          2.51         4.05
               LLMGraph_Hybrid_Community        21   1   1        7          4.03              3.49          2.51         4.05
               LLMGraph_Hybrid                  24   2   2        2          4.03              3.49          2.51         4.05
               LLMGraph_Dense                   22   0   3        5          4.03              3.49          2.51         4.05
               Community_Vector_Retriever_HyDE  17   5   6        2          4.03              3.49          2.51         4.05
               LlamaIndex_Hybrid_Rerank         21   2   4        3          4.03              3.49          2.51         4.05
summary        SimpleKG_Hybrid                  19   5   3       13          4.28              3.64          2.47         4.04
               SimpleKG_Dense                   18   9   7        6          4.28              3.64          2.47         4.04
               RAG_Naive_Hybrid                  1   5  29        5          4.28              3.64          2.47         4.04
               RAG_Advanced_Sparse              16   8   2       14          4.28              3.64          2.47         4.04
               RAG_Advanced_Hybrid              14   5   4       17          4.28              3.64          2.47         4.04
               RAG_Advanced_Dense                3   8  23        6          4.28              3.64          2.47         4.04
               LLMGraph_Hybrid_Community        27   3   2        8          4.28              3.64          2.47         4.04
               LlamaIndex_Hybrid_Community      16   2   6        3          4.28              3.64          2.47         4.04
               LlamaIndex_Dense                 18   3  12        7          4.28              3.64          2.47         4.04
               LLMGraph_Hybrid                  29   1   1        9          4.28              3.64          2.47         4.04
               LLMGraph_Dense                   20   3   6       11          4.28              3.64          2.47         4.04
               Community_Vector_Retriever_HyDE  22   1   4       13          4.28              3.64          2.47         4.04
               SimpleKG_Hybrid_Community        29   0   4        7          4.28              3.64          2.47         4.04
               LlamaIndex_Hybrid_Rerank         22   3   1       14          4.28              3.64          2.47         4.04
               SimpleKG_Hybrid_Rerank           29   3   1        7          4.28              3.64          2.47         4.04

In [99]:
summary_by_script_and_query = (
    df_newest_combi 
        .groupby(["script", "query_type"], as_index=False)
        .agg(
            Faithfulness=("faithfulness_1to5", "mean"),
            Answer_Relevance=("answer_relevance_1to5", "mean"),
            Completeness=("completeness_1to5", "mean"),
        
            Helpfulness=("helpfulness_final_1to5", "mean"),
            
        )
        .set_index(["script", "query_type"])
        .round(2)
)

print(summary_by_script_and_query.to_string())

                                                Faithfulness  Answer_Relevance  Completeness  Helpfulness
script                          query_type
Community_Vector_Retriever_HyDE multi_hop               3.87              3.57          2.43         4.00
                                summary                 3.90              3.82          2.50         4.08
LLMGraph_Dense                  disambiguation          4.70              3.63          2.53         4.53
                                factual                 4.50              3.87          3.13         3.87
                                multi_hop               4.77              3.67          2.90         4.73
                                reasoning               4.57              3.57          2.60         4.77
                                summary                 4.68              3.80          2.60         4.62
LLMGraph_Hybrid                 disambiguation          4.03              3.73          2.80         4.27
                                factual                 4.60              4.13          3.50         4.33
                                multi_hop               3.60              3.67          2.77         4.27
                                reasoning               4.00              3.57          3.00         4.27
                                summary                 3.92              3.85          2.92         4.40
LLMGraph_Hybrid_Community       disambiguation          3.87              3.60          3.43         4.23
                                factual                 4.30              3.87          3.57         4.20
                                multi_hop               3.83              3.53          2.77         4.33
                                reasoning               3.60              3.73          2.90         4.20
                                summary                 3.68              3.75          2.60         4.15
LlamaIndex_Dense                disambiguation          4.50              3.83          2.43         4.30
                                factual                 4.67              3.43          2.37         3.27
                                multi_hop               4.80              3.73          2.43         4.53
                                reasoning               4.60              3.43          2.23         4.27
                                summary                 4.90              3.68          2.45         4.20
LlamaIndex_Hybrid_Community     disambiguation          4.90              3.67          3.19         4.71
                                factual                 4.70              3.80          3.00         4.17
                                multi_hop               4.87              3.47          3.40         4.87
                                reasoning               4.35              3.30          2.61         4.35
                                summary                 4.59              3.93          2.74         4.52
LlamaIndex_Hybrid_Rerank        disambiguation          4.87              3.57          2.77         4.77
                                factual                 4.77              3.97          3.47         4.07
                                multi_hop               4.80              3.73          3.30         4.90
                                reasoning               4.37              3.50          2.90         4.60
                                summary                 4.72              3.72          2.78         4.65
RAG_Advanced_Dense              disambiguation          4.17              3.33          1.30         2.17
                                factual                 4.30              3.37          1.13         1.17
                                multi_hop               4.00              3.43          1.60         2.13
                                reasoning               4.03              3.43          1.37         2.27
                                summary                 4.58              3.50          1.65         2.20
RAG_Advanced_Hybrid             disambiguation          4.93              3.80          3.23         4.80
                                factual                 4.90              4.00          3.23         4.67
                                multi_hop               4.50              3.57          3.07         4.40
                                reasoning               4.77              3.77          2.50         4.53
                                summary                 4.75              3.65          2.50         4.45
RAG_Advanced_Sparse             disambiguation          4.90              3.73          3.07         4.70
                                factual                 4.90              4.03          3.60         4.87
                                multi_hop               4.70              3.53          2.97         4.53
                                reasoning               4.53              3.80          2.50         4.33
                                summary                 4.90              3.78          2.70         4.70
RAG_Naive_Hybrid                disambiguation          4.40              2.53          1.57         2.57
                                factual                 4.50              1.67          1.03         1.23
                                multi_hop               4.00              2.97          1.60         3.00
                                reasoning               3.87              2.60          1.37         2.57
                                summary                 4.58              2.28          1.40         2.00
SimpleKG_Dense                  disambiguation          4.07              3.77          3.13         4.33
                                factual                 4.37              3.80          3.40         4.07
                                multi_hop               4.07              3.67          3.17         4.33
                                reasoning               3.77              3.67          2.93         4.23
                                summary                 4.05              3.68          2.50         4.15
SimpleKG_Hybrid                 disambiguation          4.33              3.87          3.00         4.57
                                factual                 4.53              4.07          3.20         4.20
                                multi_hop               3.87              3.70          3.17         4.37
                                reasoning               3.80              3.43          2.60         4.10
                                summary                 3.78              3.75          2.35         4.20
SimpleKG_Hybrid_Community       disambiguation          3.90              3.90          2.90         4.30
                                factual                 4.17              4.03          3.30         4.10
                                multi_hop               3.43              3.57          3.07         4.17
                                reasoning               3.47              3.57          2.70         4.20
                                summary                 3.50              3.78          2.52         4.18
SimpleKG_Hybrid_Rerank          disambiguation          3.90              3.83          2.97         4.23
                                factual                 4.07              4.17          3.53         4.20
                                multi_hop               3.63              3.63          3.27         4.40
                                reasoning               3.50              3.60          3.07         4.17
                                summary                 3.78              3.75          2.85         4.32

In [100]:
final
pivot_help = (
    final
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="TP"
        )
        .round(2)
)

# nach der Spalte "summary" sortieren (absteigend)
pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                       disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                     18.0     19.0       28.0       22.0     29.0
SimpleKG_Hybrid_Community                  21.0     19.0       25.0       25.0     29.0
SimpleKG_Hybrid                            23.0     20.0       27.0       22.0     19.0
SimpleKG_Dense                             20.0     19.0       24.0       20.0     18.0
RAG_Naive_Hybrid                            4.0      1.0        7.0        3.0      1.0
RAG_Advanced_Sparse                        23.0     26.0       18.0       19.0     16.0
RAG_Advanced_Hybrid                        22.0     27.0       16.0       20.0     14.0
RAG_Advanced_Dense                          1.0      1.0        2.0        2.0      3.0
LlamaIndex_Hybrid_Rerank                   19.0     19.0       23.0       21.0     22.0
LlamaIndex_Hybrid_Community                14.0     18.0       13.0       15.0     16.0
LlamaIndex_Dense                           14.0     12.0       19.0       16.0     18.0
LLMGraph_Hybrid_Community                  19.0     20.0       21.0       21.0     27.0
LLMGraph_Hybrid                            21.0     20.0       24.0       24.0     29.0
LLMGraph_Dense                             20.0     19.0       18.0       22.0     20.0
Community_Vector_Retriever_HyDE             NaN      NaN       14.0        NaN     22.0

In [41]:
final
pivot_help = (
    final
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="Helpfulness"
        )
        .round(2)
)

# nach der Spalte "summary" sortieren (absteigend)
pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                       disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                     4.14     3.72       4.17       4.05     4.04
SimpleKG_Hybrid_Community                  4.14     3.72       4.17       4.05     4.04
SimpleKG_Hybrid                            4.14     3.72       4.17       4.05     4.04
SimpleKG_Dense                             4.14     3.72       4.17       4.05     4.04
RAG_Naive_Hybrid                           4.14     3.72       4.17       4.05     4.04
RAG_Advanced_Sparse                        4.14     3.72       4.17       4.05     4.04
RAG_Advanced_Hybrid                        4.14     3.72       4.17       4.05     4.04
RAG_Advanced_Dense                         4.14     3.72       4.17       4.05     4.04
LlamaIndex_Hybrid_Rerank                   4.14     3.72       4.17       4.05     4.04
LlamaIndex_Hybrid_Community                4.14     3.72       4.17       4.05     4.04
LlamaIndex_Dense                           4.14     3.72       4.17       4.05     4.04
LLMGraph_Hybrid_Community                  4.14     3.72       4.17       4.05     4.04
LLMGraph_Hybrid                            4.14     3.72       4.17       4.05     4.04
LLMGraph_Dense                             4.14     3.72       4.17       4.05     4.04
Community_Vector_Retriever_HyDE            4.14     3.72       4.17       4.05     4.04

In [102]:
pivot_help = (
    summary_by_script_and_query
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="Answer_Relevance"
        )
        .round(2)
)

# nach der Spalte "summary" sortieren (absteigend)
pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                       disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                     3.83     4.17       3.63       3.60     3.75
SimpleKG_Hybrid_Community                  3.90     4.03       3.57       3.57     3.78
SimpleKG_Hybrid                            3.87     4.07       3.70       3.43     3.75
SimpleKG_Dense                             3.77     3.80       3.67       3.67     3.68
RAG_Naive_Hybrid                           2.53     1.67       2.97       2.60     2.28
RAG_Advanced_Sparse                        3.73     4.03       3.53       3.80     3.78
RAG_Advanced_Hybrid                        3.80     4.00       3.57       3.77     3.65
RAG_Advanced_Dense                         3.33     3.37       3.43       3.43     3.50
LlamaIndex_Hybrid_Rerank                   3.57     3.97       3.73       3.50     3.72
LlamaIndex_Hybrid_Community                3.67     3.80       3.47       3.30     3.93
LlamaIndex_Dense                           3.83     3.43       3.73       3.43     3.68
LLMGraph_Hybrid_Community                  3.60     3.87       3.53       3.73     3.75
LLMGraph_Hybrid                            3.73     4.13       3.67       3.57     3.85
LLMGraph_Dense                             3.63     3.87       3.67       3.57     3.80
Community_Vector_Retriever_HyDE             NaN      NaN       3.57        NaN     3.82

In [103]:
pivot_help = (
    summary_by_script_and_query
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="Faithfulness"
        )
        .round(2)
)


pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                       disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                     3.90     4.07       3.63       3.50     3.78
SimpleKG_Hybrid_Community                  3.90     4.17       3.43       3.47     3.50
SimpleKG_Hybrid                            4.33     4.53       3.87       3.80     3.78
SimpleKG_Dense                             4.07     4.37       4.07       3.77     4.05
RAG_Naive_Hybrid                           4.40     4.50       4.00       3.87     4.58
RAG_Advanced_Sparse                        4.90     4.90       4.70       4.53     4.90
RAG_Advanced_Hybrid                        4.93     4.90       4.50       4.77     4.75
RAG_Advanced_Dense                         4.17     4.30       4.00       4.03     4.58
LlamaIndex_Hybrid_Rerank                   4.87     4.77       4.80       4.37     4.72
LlamaIndex_Hybrid_Community                4.90     4.70       4.87       4.35     4.59
LlamaIndex_Dense                           4.50     4.67       4.80       4.60     4.90
LLMGraph_Hybrid_Community                  3.87     4.30       3.83       3.60     3.68
LLMGraph_Hybrid                            4.03     4.60       3.60       4.00     3.92
LLMGraph_Dense                             4.70     4.50       4.77       4.57     4.68
Community_Vector_Retriever_HyDE             NaN      NaN       3.87        NaN     3.90

In [104]:
pivot_help = (
    summary_by_script_and_query
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="Completeness"
        )
        .round(2)
)


pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                       disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                     2.97     3.53       3.27       3.07     2.85
SimpleKG_Hybrid_Community                  2.90     3.30       3.07       2.70     2.52
SimpleKG_Hybrid                            3.00     3.20       3.17       2.60     2.35
SimpleKG_Dense                             3.13     3.40       3.17       2.93     2.50
RAG_Naive_Hybrid                           1.57     1.03       1.60       1.37     1.40
RAG_Advanced_Sparse                        3.07     3.60       2.97       2.50     2.70
RAG_Advanced_Hybrid                        3.23     3.23       3.07       2.50     2.50
RAG_Advanced_Dense                         1.30     1.13       1.60       1.37     1.65
LlamaIndex_Hybrid_Rerank                   2.77     3.47       3.30       2.90     2.78
LlamaIndex_Hybrid_Community                3.19     3.00       3.40       2.61     2.74
LlamaIndex_Dense                           2.43     2.37       2.43       2.23     2.45
LLMGraph_Hybrid_Community                  3.43     3.57       2.77       2.90     2.60
LLMGraph_Hybrid                            2.80     3.50       2.77       3.00     2.92
LLMGraph_Dense                             2.53     3.13       2.90       2.60     2.60
Community_Vector_Retriever_HyDE             NaN      NaN       2.43        NaN     2.50

In [105]:
pivot_help = (
    summary_by_script_and_query
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="Completeness"
        )
        .round(2)
)


pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                       disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                     2.97     3.53       3.27       3.07     2.85
SimpleKG_Hybrid_Community                  2.90     3.30       3.07       2.70     2.52
SimpleKG_Hybrid                            3.00     3.20       3.17       2.60     2.35
SimpleKG_Dense                             3.13     3.40       3.17       2.93     2.50
RAG_Naive_Hybrid                           1.57     1.03       1.60       1.37     1.40
RAG_Advanced_Sparse                        3.07     3.60       2.97       2.50     2.70
RAG_Advanced_Hybrid                        3.23     3.23       3.07       2.50     2.50
RAG_Advanced_Dense                         1.30     1.13       1.60       1.37     1.65
LlamaIndex_Hybrid_Rerank                   2.77     3.47       3.30       2.90     2.78
LlamaIndex_Hybrid_Community                3.19     3.00       3.40       2.61     2.74
LlamaIndex_Dense                           2.43     2.37       2.43       2.23     2.45
LLMGraph_Hybrid_Community                  3.43     3.57       2.77       2.90     2.60
LLMGraph_Hybrid                            2.80     3.50       2.77       3.00     2.92
LLMGraph_Dense                             2.53     3.13       2.90       2.60     2.60
Community_Vector_Retriever_HyDE             NaN      NaN       2.43        NaN     2.50

In [107]:
import pandas as pd

# 1) Ensure both have the SAME MultiIndex order: (script, query_type)
summary_metrics = summary_by_script_and_query.copy()  # index: (script, query_type)

counts_fixed = (
    counts.copy()
         .reorder_levels(["script", "query_type"])  # was (query_type, script) -> (script, query_type)
         .sort_index()
)

# 2) Join metrics + counts into one table
summary_all = summary_metrics.join(counts_fixed, how="left").fillna(0)

# Optional: make TP/FP/FN integers (after fillna)
for col in ["TP", "FP", "FN"]:
    if col in summary_all.columns:
        summary_all[col] = summary_all[col].astype(int)

summary_all.head(5)

                                                Faithfulness  \
script                          query_type
Community_Vector_Retriever_HyDE multi_hop               3.87
                                summary                 3.90
LLMGraph_Dense                  disambiguation          4.70
                                factual                 4.50
                                multi_hop               4.77

                                                Answer_Relevance  \
script                          query_type
Community_Vector_Retriever_HyDE multi_hop                   3.57
                                summary                     3.82
LLMGraph_Dense                  disambiguation              3.63
                                factual                     3.87
                                multi_hop                   3.67

                                                Completeness  Helpfulness  TP  \
script                          query_type
Community_Vector_Retriever_HyDE multi_hop               2.43         4.00  14
                                summary                 2.50         4.08  22
LLMGraph_Dense                  disambiguation          2.53         4.53  20
                                factual                 3.13         3.87  19
                                multi_hop               2.90         4.73  18

                                                FP  FN
script                          query_type
Community_Vector_Retriever_HyDE multi_hop        0   5
                                summary          1   4
LLMGraph_Dense                  disambiguation   3   4
                                factual          0   8
                                multi_hop        1   1

In [108]:
summary_only = summary_all.xs("multi_hop", level="query_type")
summary_only

,Faithfulness,Answer_Relevance,Completeness,Correctness,Helpfulness,TP,FP,FN
script,,,,,,,,
LLMGraph_Dense,4.77,3.67,2.90,4.03,4.73,18,1,1
LLMGraph_Hybrid,3.60,3.67,2.77,4.37,4.27,24,1,0
LLMGraph_Hybrid_Community,3.83,3.53,2.77,4.20,4.33,21,1,2
LlamaIndex_Dense,4.83,3.67,2.33,3.70,4.53,16,2,3
LlamaIndex_Hybrid_Community,4.87,3.47,3.40,4.73,4.87,13,0,0
LlamaIndex_Hybrid_Rerank,4.80,3.73,3.30,4.43,4.90,23,0,0
RAG_Advanced_Dense,4.00,3.43,1.60,1.77,2.13,2,1,19
RAG_Advanced_Hybrid,4.50,3.57,3.07,3.67,4.40,16,2,2
RAG_Advanced_Sparse,4.70,3.53,2.97,4.00,4.53,18,1,1
RAG_Naive_Hybrid,4.00,2.97,1.60,2.63,3.00,7,1,12
SimpleKG_Dense,4.07,3.67,3.17,4.23,4.33,24,1,2
SimpleKG_Hybrid,3.87,3.70,3.17,4.63,4.37,27,0,1
SimpleKG_Hybrid_Community,3.43,3.57,3.07,4.37,4.17,25,2,2
SimpleKG_Hybrid_Rerank,3.50,3.67,3.30,4.73,4.33,27,0,0

In [ ]:
summary_only = summary_all.xs("summary", level="query_type")
summary_only

,Faithfulness,Answer_Relevance,Completeness,Correctness,Helpfulness,TP,FP,FN
script,,,,,,,,
LLMGraph_Dense,4.68,3.80,2.60,3.58,4.62,20,3,6
LLMGraph_Hybrid,3.92,3.85,2.92,4.22,4.40,29,1,1
LLMGraph_Hybrid_Community,3.68,3.75,2.60,4.05,4.15,27,3,2
LlamaIndex_Dense,4.82,3.60,2.30,3.05,4.18,15,2,12
LlamaIndex_Hybrid_Community,4.59,3.93,2.74,3.59,4.52,16,2,6
LlamaIndex_Hybrid_Rerank,4.72,3.74,2.74,3.85,4.67,21,3,1
RAG_Advanced_Dense,4.58,3.50,1.65,1.55,2.20,3,8,23
RAG_Advanced_Hybrid,4.75,3.65,2.50,3.22,4.45,14,5,4
RAG_Advanced_Sparse,4.90,3.78,2.70,3.30,4.70,16,8,2
RAG_Naive_Hybrid,4.58,2.28,1.40,1.38,2.00,1,5,29
SimpleKG_Dense,4.03,3.67,2.54,3.08,4.18,18,9,6
SimpleKG_Hybrid,3.78,3.75,2.35,3.50,4.20,19,5,3
SimpleKG_Hybrid_Community,3.50,3.78,2.52,4.15,4.18,29,0,4
SimpleKG_Hybrid_Rerank,3.45,3.80,2.75,3.92,4.18,26,2,3

In [112]:
rows_per_script = df_newest_combi.groupby("script").size()
print(rows_per_script)

script
LLMGraph_Dense                 160
LLMGraph_Hybrid                160
LLMGraph_Hybrid_Community      160
LlamaIndex_Dense               160
LlamaIndex_Hybrid_Community    116
LlamaIndex_Hybrid_Rerank       157
RAG_Advanced_Dense             160
RAG_Advanced_Hybrid            160
RAG_Advanced_Sparse            160
RAG_Naive_Hybrid               160
SimpleKG_Dense                 159
SimpleKG_Hybrid                160
SimpleKG_Hybrid_Community      160
SimpleKG_Hybrid_Rerank         160
dtype: int64

In [ ]:
df_newest_combi

In [111]:
df_newest_combi = df_newest_combi.drop_duplicates(
    subset=["script", "question_id"],
    keep="first"
)

In [127]:
dups = df_newest_combi[
    (df_newest_combi["script"] == "RAG_Advanced_Sparse") &
    (df_newest_combi.duplicated(subset=["question_id"], keep=False))
]

In [138]:
df_newest_combi[
    (df_newest_combi["script"] == "SimpleKG_Dense") &
    (df_newest_combi["question_id"].isin([42, 58, 70]))
]

,script,question_id,query_type,answer_relevance_score,answer_relevance_1to5,completeness_score,completeness_1to5,correctness_category,correctness_coverage,correctness_coverage_1to5,correctness_error_severity,faithfulness_score,faithfulness_1to5,helpfulness_raw_1to5,helpfulness_raw_score,helpfulness_final_score,helpfulness_final_1to5,helpfulness_justification,metrics_json,correctness_rank
71,SimpleKG_Dense,42,reasoning,0.529677,3,0.00,1,FP,0.0,1,high,0.95,5,5,1.0,0.9750,5,The answer directly addresses the question by ...,"{""answer_relevance"": {""score"": 0.5296768546104...",NaN
87,SimpleKG_Dense,58,reasoning,0.701175,4,0.75,4,TP,1.0,5,low,0.95,5,3,0.5,0.4875,3,The answer correctly identifies the voltage li...,"{""answer_relevance"": {""score"": 0.7011746168136...",NaN

In [ ]:
df_new_llamaindex = df_newest_combi[df_newest_combi["script"].isin(["SimpleKG_Dense"])]
df_new_llamaindex.groupby("script").size()

script
LlamaIndex_Hybrid_Rerank    157
dtype: int64

In [129]:
df_new_llamaindex2 = df_newest_combi[df_newest_combi["script"].isin(["SimpleKG_Dense"])]
df_new_llamaindex2.groupby("script").size()

script
SimpleKG_Dense    159
dtype: int64

In [130]:
OUTPUT_PATH = PROJECT_ROOT / "main" / "evaluation" / "evaluation_datasets" / "golden_answers_dataset_llmaindex_missing.jsonl"

In [104]:
df_only_not_in_llamaindex.to_json(OUTPUT_PATH, orient="records", lines=True, force_ascii=False)

In [131]:
# ---------------------------------------------------------------------------
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())
PROJECT_ROOT = Path(os.getenv("PROJECT_ROOT")).expanduser().resolve()

QUESTIONS_PATH = (
    PROJECT_ROOT
    / "main"
    / "evaluation"
    / "evaluation_datasets"
    / "golden_answers_dataset.jsonl"
)
QUESTIONS_PATH

WindowsPath('C:/Users/Nasiba/Documents/1 Master Data Science/Master Thesis/VS Code New/master_thesis-rag/main/evaluation/evaluation_datasets/golden_answers_dataset.jsonl')

In [132]:
# Load
df = pd.read_json(QUESTIONS_PATH, lines=True)
df = df[df["query_type"]!= "relational"]
df.head(2)

,id,query_type,question,gold_answer
0,1,factual,What is the pressure measurement range of the ...,The LPS22HB measures absolute pressure from 26...
1,2,factual,What is the humidity measurement range of the ...,The HS3003 measures relative humidity from 0% ...

In [133]:
df["question_id"] = df["id"].astype(str)
df_new_llamaindex["question_id"] = df_new_llamaindex["question_id"].astype(str)
df_new_llamaindex2["question_id"] = df_new_llamaindex2["question_id"].astype(str)

C:\Users\Nasiba\AppData\Local\Temp\ipykernel_25248\2468996886.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_llamaindex["question_id"] = df_new_llamaindex["question_id"].astype(str)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_25248\2468996886.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_llamaindex2["question_id"] = df_new_llamaindex2["question_id"].astype(str)

In [134]:
df_only_not_in_llamaindex = df[
    ~df["question_id"].isin(df_new_llamaindex["question_id"])
]
df_only_not_in_llamaindex

,id,query_type,question,gold_answer,question_id
41,42,reasoning,Which board is better suited for edge AI execu...,"The Nicla Sense ME, because the BHI260 can run...",42
57,58,reasoning,Can a 5-volt sensor be connected directly to t...,"No, because the Due operates at 3.3 V and its ...",58
69,70,summary,Compare the AI-related capabilities of the Nan...,The Nano family includes no specialized AI har...,70

In [25]:
EXCLUDE_COLS = {"script", "question_id", "query_type"}

metric_cols = [
    c for c in df_newest_combi.columns
    if c not in EXCLUDE_COLS
]

metric_cols

['answer_relevance_score',
 'answer_relevance_1to5',
 'completeness_score',
 'completeness_1to5',
 'correctness_category',
 'correctness_coverage',
 'correctness_coverage_1to5',
 'correctness_error_severity',
 'faithfulness_score',
 'faithfulness_1to5',
 'helpfulness_raw_1to5',
 'helpfulness_raw_score',
 'helpfulness_final_score',
 'helpfulness_final_1to5',
 'helpfulness_justification',
 'metrics_json',
 'correctness_rank']

In [28]:

N = 50  # wie viele du willst


score_col = "faithfulness_1to5"
df_newest_combi[score_col] = pd.to_numeric(df_newest_combi[score_col], errors="coerce")

worst_overall = (
    df_newest_combi
    .dropna(subset=[score_col])
    .sort_values(score_col, ascending=True)   
    .head(N)
    .loc[:, ["script","question_id","query_type", score_col]]
)

worst_overall

                        script  question_id      query_type  faithfulness_1to5
265            LLMGraph_Hybrid          186         summary                  2
223            LLMGraph_Hybrid          105  disambiguation                  2
207            LLMGraph_Hybrid           89         factual                  2
179            LLMGraph_Hybrid           61  disambiguation                  2
69             LLMGraph_Hybrid           70         summary                  2
194            LLMGraph_Hybrid           76         summary                  2
170            LLMGraph_Hybrid           52         factual                  2
143            LLMGraph_Hybrid           25       multi_hop                  2
65              SimpleKG_Dense           36         factual                  2
12         RAG_Advanced_Hybrid          113       multi_hop                  2
329           LlamaIndex_Dense           90         factual                  2
344           LlamaIndex_Dense          105  disambiguation                  2
253           LlamaIndex_Dense           14         factual                  2
95              SimpleKG_Dense          166         summary                  2
56              SimpleKG_Dense           27  disambiguation                  2
57              SimpleKG_Dense           28         factual                  2
58              SimpleKG_Dense           29       reasoning                  2
292  LLMGraph_Hybrid_Community          123       reasoning                  2
296  LLMGraph_Hybrid_Community          127       reasoning                  2
284  LLMGraph_Hybrid_Community          115       multi_hop                  2
112   LlamaIndex_Hybrid_Rerank          123       reasoning                  2
26             LLMGraph_Hybrid           27  disambiguation                  2
31             LLMGraph_Hybrid           32         summary                  2
151            LLMGraph_Hybrid           33         factual                  2
155            LLMGraph_Hybrid           37       multi_hop                  2
84             SimpleKG_Hybrid          175       multi_hop                  2
94             SimpleKG_Hybrid          185         summary                  2
95             SimpleKG_Hybrid          186         summary                  2
96             SimpleKG_Hybrid          187         summary                  2
64             SimpleKG_Hybrid          155         summary                  2
356  LLMGraph_Hybrid_Community          187         summary                  2
335  LLMGraph_Hybrid_Community          166         summary                  2
337  LLMGraph_Hybrid_Community          168  disambiguation                  2
309  LLMGraph_Hybrid_Community          140  disambiguation                  2
27             SimpleKG_Hybrid          165       multi_hop                  2
29             SimpleKG_Hybrid          167       multi_hop                  2
118           RAG_Naive_Hybrid          119         summary                  2
120           RAG_Naive_Hybrid          121       reasoning                  2
122           RAG_Naive_Hybrid          123       reasoning                  2
19             SimpleKG_Hybrid          151       multi_hop                  2
385  SimpleKG_Hybrid_Community          126       multi_hop                  2
364  SimpleKG_Hybrid_Community          105  disambiguation                  2
374  SimpleKG_Hybrid_Community          115       multi_hop                  2
352         RAG_Advanced_Dense          173       reasoning                  2
416  SimpleKG_Hybrid_Community          157       multi_hop                  2
417  SimpleKG_Hybrid_Community          158         summary                  2
422  SimpleKG_Hybrid_Community          163         summary                  2
424  SimpleKG_Hybrid_Community          165       multi_hop                  2
394  SimpleKG_Hybrid_Community          135       multi_hop                  2
398  SimpleKG_Hybrid_Community          139       reasoning                  2

In [46]:
import pandas as pd

# ============================================================
# CONFIG – NUR HIER ÄNDERN
# ============================================================
score_col = "faithfulness_1to5"     # z.B. "helpfulness_final_score"
script_name = "LLMGraph_Hybrid_Community"                # z.B. "rag_chat.py" oder "rag_chat_graph.py"
N = 10

# ============================================================
# LOGIK – NICHT MEHR ANFASSEN
# ============================================================
if score_col not in df_newest_combi.columns:
    raise ValueError(f"score_col '{score_col}' not found. Available: {list(df_newest_combi.columns)}")

if script_name != "ALL" and script_name not in df_newest_combi["script"].unique():
    raise ValueError(f"script_name '{script_name}' not found in df_newest_combi['script'].")

df_tmp = df_newest_combi.copy()

# optional: nach Script filtern
if script_name != "ALL":
    df_tmp = df_tmp[df_tmp["script"] == script_name].copy()

# robust cast
df_tmp[score_col] = pd.to_numeric(df_tmp[score_col], errors="coerce")

# Spalten, die du immer sehen willst (ohne Duplikate)
base_cols = ["script", "question_id", "query_type"]
always_show = [
    "helpfulness_final_1to5",
    "helpfulness_final_score",
    "answer_relevance_score",
    "answer_relevance_1to5",
    "completeness_score",
    "completeness_1to5",
    "faithfulness_score",
    "faithfulness_1to5",
    "correctness_category",
    "correctness_coverage",
    "correctness_coverage_1to5",
    "correctness_error_severity",
    "helpfulness_justification",
    "metrics_json",
]

show_cols = base_cols + [score_col] + [c for c in always_show if c != score_col]
show_cols = [c for c in show_cols if c in df_tmp.columns]  # falls mal was fehlt

worst_overall = (
    df_tmp
    .dropna(subset=[score_col])
    .sort_values(score_col, ascending=True)  # kleinster Wert = schlechtester
    .head(N)
    .loc[:, show_cols]
)

worst_overall

,script,question_id,query_type,faithfulness_1to5,helpfulness_final_1to5,helpfulness_final_score,answer_relevance_score,answer_relevance_1to5,completeness_score,completeness_1to5,faithfulness_score,correctness_category,correctness_coverage,correctness_coverage_1to5,correctness_error_severity,helpfulness_justification,metrics_json
284,LLMGraph_Hybrid_Community,115,multi_hop,2,4,0.625000,0.696934,4,0.333333,2,0.250000,TP,1.0,5,low,"The answer provides clear, actionable steps fo...","{""answer_relevance"": {""score"": 0.6969343026479..."
292,LLMGraph_Hybrid_Community,123,reasoning,2,4,0.675000,0.811855,4,1.000000,5,0.350000,PARTIAL,0.5,3,low,The answer provides a clear diagnosis of the '...,"{""answer_relevance"": {""score"": 0.8118548989295..."
296,LLMGraph_Hybrid_Community,127,reasoning,2,4,0.625000,0.524782,3,0.375000,2,0.250000,TP,0.6,3,low,"The answer provides a clear, structured approa...","{""answer_relevance"": {""score"": 0.5247817039489..."
309,LLMGraph_Hybrid_Community,140,disambiguation,2,4,0.625000,0.404257,3,0.500000,3,0.250000,PARTIAL,0.5,3,medium,The answer directly addresses the user's issue...,"{""answer_relevance"": {""score"": 0.4042568902174..."
335,LLMGraph_Hybrid_Community,166,summary,2,4,0.625000,0.475183,3,0.250000,2,0.250000,PARTIAL,0.5,3,low,"The answer provides clear, actionable steps fo...","{""answer_relevance"": {""score"": 0.4751827518145..."
131,LLMGraph_Hybrid_Community,32,summary,2,4,0.625000,0.720978,4,0.416667,3,0.250000,PARTIAL,0.6,3,medium,The answer provides a clear and detailed summa...,"{""answer_relevance"": {""score"": 0.7209778825441..."
127,LLMGraph_Hybrid_Community,28,factual,2,4,0.625000,0.792386,4,1.000000,5,0.250000,TP,1.0,5,low,The answer directly addresses the question abo...,"{""answer_relevance"": {""score"": 0.7923855384190..."
152,LLMGraph_Hybrid_Community,53,factual,2,4,0.625000,0.830788,4,0.750000,4,0.250000,TP,1.0,5,low,The answer directly addresses the question wit...,"{""answer_relevance"": {""score"": 0.8307879169782..."
126,LLMGraph_Hybrid_Community,27,disambiguation,2,3,0.583333,0.769350,4,0.750000,4,0.166667,TP,1.0,5,low,The answer directly defines 'XiP' and explains...,"{""answer_relevance"": {""score"": 0.7693501313527..."
124,LLMGraph_Hybrid_Community,25,multi_hop,2,4,0.625000,0.407595,3,0.500000,3,0.250000,TP,1.0,5,low,The answer directly addresses the question by ...,"{""answer_relevance"": {""score"": 0.4075945317745..."

In [47]:
import pandas as pd
from pathlib import Path
import os
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())
PROJECT_ROOT = Path(os.getenv("PROJECT_ROOT")).expanduser().resolve()

INPUT_PATH = (
    PROJECT_ROOT
    / "main"
    / "evaluation"
    / "evaluation_datasets"
    / "golden_answers_dataset.jsonl"
)
OUTPUT_PATH = (
    PROJECT_ROOT
    / "main"
    / "evaluation"
    / "evaluation_datasets"
    / "golden_answers_dataset_filtered_short.jsonl"
)
df_gold = pd.read_json(INPUT_PATH, lines=True)

# sicherstellen, dass IDs vergleichbar sind
df_gold["id"] = pd.to_numeric(df_gold["id"], errors="coerce")
worst_overall["question_id"] = pd.to_numeric(worst_overall["question_id"], errors="coerce")

# ------------------------------------------------------------
# 2) Nur die schlechtesten question_ids selektieren
# ------------------------------------------------------------
worst_ids = worst_overall["question_id"].dropna().unique()

df_worst_gold = df_gold[df_gold["id"].isin(worst_ids)].copy()

# ------------------------------------------------------------
# 3) Schema NICHT verändern, nur speichern
# ------------------------------------------------------------


#print(f"Saved {len(df_worst_gold)} worst-case questions to: {OUTPUT_PATH}")

df_worst_gold.head(10)

,id,query_type,question,gold_answer
24,25,multi_hop,"Which board uses the Bosch BME688 sensor, and ...","The Nicla Sense ME uses the BME688, which supp..."
26,27,disambiguation,What does the term 'XiP' refer to in the Nicla...,It refers to execute-in-place code support pro...
27,28,factual,What is the bit depth of temperature readings ...,Temperature readings can be polled at up to 16...
31,32,summary,Summarize the sensing architecture of the Nicl...,It integrates a programmable BHI260 sensor hub...
52,53,factual,How much memory does the Arduino Due provide?,It provides 512 KB Flash memory and 96 KB SRAM...
114,115,multi_hop,I connected my MKR Vidor 4000 to my computer a...,You need to install the WiFiNINA library to en...
122,123,reasoning,The PLC IDE shows my device as 'No License'. W...,"Without activating the PLC IDE license, the de..."
126,127,reasoning,I compiled and uploaded the program without er...,You should check whether the temperature varia...
139,140,disambiguation,During upload I briefly see a USB drive appear...,This is expected behavior because the Nano RP2...
165,166,summary,I want to understand whether my robot is respo...,"You can check the robot’s power state, acknowl..."

In [48]:
df_worst_gold.to_json(
    OUTPUT_PATH,
    orient="records",
    lines=True,
    force_ascii=False
)