In [66]:


import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH11 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_llmaindex_missing_rows_1_to_76.csv"
)


CSV_PATH_NEW11 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH11))).expanduser().resolve()
df_new_11 = pd.read_csv(CSV_PATH_NEW11)

In [67]:


import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH10 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_filtered_simplekg_rows_1_to_84.csv"
)
JUDGE_PATH10

CSV_PATH_NEW10 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH10))).expanduser().resolve()
df_new_10 = pd.read_csv(CSV_PATH_NEW10)

In [68]:

import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH9 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_empty_responses_rows_1_to_40.csv"
)


CSV_PATH_NEW9 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH9))).expanduser().resolve()
df_new_9 = pd.read_csv(CSV_PATH_NEW9)

In [69]:




import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH8 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_llmaindex_nonempty_rows_1_to_50.csv"
)


CSV_PATH_NEW8 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH8))).expanduser().resolve()
df_new_8 = pd.read_csv(CSV_PATH_NEW8)

In [70]:



import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH7 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_part4_rows_1_to_370.csv"
)


CSV_PATH_NEW7 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH7))).expanduser().resolve()
df_new_7 = pd.read_csv(CSV_PATH_NEW7)

In [71]:




import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH6 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_part3_rows_1_to_299.csv"
)


CSV_PATH_NEW6 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH6))).expanduser().resolve()
df_new_6 = pd.read_csv(CSV_PATH_NEW6)

In [72]:



import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH5 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_part2_rows_1_to_400.csv"
)


CSV_PATH_NEW5 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH5))).expanduser().resolve()
df_new_5 = pd.read_csv(CSV_PATH_NEW5)

In [73]:

import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH4 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_rows_1_to_500.csv"
)


CSV_PATH_NEW4 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH4))).expanduser().resolve()
df_new_4 = pd.read_csv(CSV_PATH_NEW4)

In [74]:
import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH3 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_rows_1_to_402.csv"
)


CSV_PATH_NEW3 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH3))).expanduser().resolve()
df_new_3 = pd.read_csv(CSV_PATH_NEW3)

In [75]:
import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH2 = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_rows_1_to_289.csv"
)


CSV_PATH_NEW2 =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH2))).expanduser().resolve()
df_new_2 = pd.read_csv(CSV_PATH_NEW2)

In [76]:
import pandas as pd
from pathlib import Path

import os

PROJECT_ROOT = Path(
    os.getenv("PROJECT_ROOT", Path.cwd())
).expanduser().resolve()


JUDGE_PATH = (
    PROJECT_ROOT


    / "llm_judge_results_answers_log_new_dataset_8_rows_1_to_400.csv"
)


CSV_PATH_NEW =  Path(os.getenv("ANSWERS_LOG_PATH", str(JUDGE_PATH))).expanduser().resolve()
df_new_1 = pd.read_csv(CSV_PATH_NEW)

In [77]:
df_new = (
    pd.concat(
        [ df_new_11, df_new_10,df_new_9, df_new_8,df_new_7, df_new_6, df_new_5, df_new_4, df_new_3, df_new_2, df_new_1],
        axis=0
    )
    .drop_duplicates()
)

In [78]:
script_name = "SimpleKG_Hybrid_Retriever"

In [79]:
df_new["script"] = df_new["script"].replace({
    "SimpleKG_Hybrid_KG_Retriever": "SimpleKG_Hybrid_Retriever"
})

In [80]:
rows_per_script = df_new.groupby("script").size()
print(rows_per_script)

script
LLMGraph_Dense                       190
LLMGraph_Hybrid                      380
LLMGraph_Hybrid_Community            190
LlamaIndex_Dense                     190
LlamaIndex_Dense_Community_Rerank    143
LlamaIndex_Hybrid_Rerank             189
RAG_Advanced_Dense                   190
RAG_Advanced_Hybrid                  190
RAG_Advanced_Sparse                  192
RAG_Naive_Hybrid                     190
SimpleKG_Dense                       192
SimpleKG_Hybrid                      230
SimpleKG_Hybrid_Community_Rerank     190
SimpleKG_Hybrid_Rerank               254
dtype: int64

In [88]:
df3= df_new[df_new["script"] == "SimpleKG_Hybrid_Rerank"]
import pandas as pd



# 1) Priorität für correctness_category festlegen (höher = besser)
# TP soll gewinnen, danach FP, danach alles andere
category_rank = {"TP": 2, "FP": 1}

df3["correctness_rank"] = df3["correctness_category"].map(category_rank).fillna(0).astype(int)

# 2) Scores robust in Zahlen umwandeln (falls sie als Strings vorliegen)
df3["faithfulness_1to5"] = pd.to_numeric(df3["faithfulness_1to5"], errors="coerce").fillna(-1)
df3["answer_relevance_1to5"] = pd.to_numeric(df3["answer_relevance_1to5"], errors="coerce").fillna(-1)
# (Optional) weiterer Tie-Breaker, falls du willst:
df3["helpfulness_final_1to5"] = pd.to_numeric(df3["helpfulness_final_1to5"], errors="coerce").fillna(-1)

# 3) Sortieren: pro (script, question_id) die beste Zeile nach Ranking zuerst
df_sorted3 = df3.sort_values(
    by=[
        "script",
        "question_id",
        "correctness_rank",      # TP > FP > Rest
        "faithfulness_1to5",     # höher besser
        "answer_relevance_1to5", # höher besser
        "helpfulness_final_1to5" # optional tie-breaker
    ],
    ascending=[True, True, False, False, False, False],
)

# 4) Pro (script, question_id) nur die erste (beste) Zeile behalten
df_best3 = df_sorted3.drop_duplicates(subset=["script", "question_id"], keep="first")

C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\2523977324.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["correctness_rank"] = df3["correctness_category"].map(category_rank).fillna(0).astype(int)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\2523977324.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["faithfulness_1to5"] = pd.to_numeric(df3["faithfulness_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\2523977324.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["answer_relevance_1to5"] = pd.to_numeric(df3["answer_relevance_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\2523977324.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["helpfulness_final_1to5"] = pd.to_numeric(df3["helpfulness_final_1to5"], errors="coerce").fillna(-1)

In [81]:
df2= df_new[df_new["script"] == "SimpleKG_Hybrid"]
import pandas as pd



# 1) Priorität für correctness_category festlegen (höher = besser)
# TP soll gewinnen, danach FP, danach alles andere
category_rank = {"TP": 2, "FP": 1}

df2["correctness_rank"] = df2["correctness_category"].map(category_rank).fillna(0).astype(int)

# 2) Scores robust in Zahlen umwandeln (falls sie als Strings vorliegen)
df2["faithfulness_1to5"] = pd.to_numeric(df2["faithfulness_1to5"], errors="coerce").fillna(-1)
df2["answer_relevance_1to5"] = pd.to_numeric(df2["answer_relevance_1to5"], errors="coerce").fillna(-1)
# (Optional) weiterer Tie-Breaker, falls du willst:
df2["helpfulness_final_1to5"] = pd.to_numeric(df2["helpfulness_final_1to5"], errors="coerce").fillna(-1)

# 3) Sortieren: pro (script, question_id) die beste Zeile nach Ranking zuerst
df_sorted2 = df2.sort_values(
    by=[
        "script",
        "question_id",
        "correctness_rank",      # TP > FP > Rest
        "faithfulness_1to5",     # höher besser
        "answer_relevance_1to5", # höher besser
        "helpfulness_final_1to5" # optional tie-breaker
    ],
    ascending=[True, True, False, False, False, False],
)

# 4) Pro (script, question_id) nur die erste (beste) Zeile behalten
df_best2 = df_sorted2.drop_duplicates(subset=["script", "question_id"], keep="first")

C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\1010867016.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["correctness_rank"] = df2["correctness_category"].map(category_rank).fillna(0).astype(int)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\1010867016.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["faithfulness_1to5"] = pd.to_numeric(df2["faithfulness_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\1010867016.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["answer_relevance_1to5"] = pd.to_numeric(df2["answer_relevance_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\1010867016.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["helpfulness_final_1to5"] = pd.to_numeric(df2["helpfulness_final_1to5"], errors="coerce").fillna(-1)

In [82]:
df= df_new[df_new["script"] == "LLMGraph_Hybrid"]
import pandas as pd



# 1) Priorität für correctness_category festlegen (höher = besser)
# TP soll gewinnen, danach FP, danach alles andere
category_rank = {"TP": 2, "FP": 1}

df["correctness_rank"] = df["correctness_category"].map(category_rank).fillna(0).astype(int)

# 2) Scores robust in Zahlen umwandeln (falls sie als Strings vorliegen)
df["faithfulness_1to5"] = pd.to_numeric(df["faithfulness_1to5"], errors="coerce").fillna(-1)
df["answer_relevance_1to5"] = pd.to_numeric(df["answer_relevance_1to5"], errors="coerce").fillna(-1)

# (Optional) weiterer Tie-Breaker, falls du willst:
df["helpfulness_final_1to5"] = pd.to_numeric(df["helpfulness_final_1to5"], errors="coerce").fillna(-1)

# 3) Sortieren: pro (script, question_id) die beste Zeile nach Ranking zuerst
df_sorted = df.sort_values(
    by=[
        "script",
        "question_id",
        "correctness_rank",      # TP > FP > Rest
        "faithfulness_1to5",     # höher besser
        "answer_relevance_1to5", # höher besser
        "helpfulness_final_1to5" # optional tie-breaker
    ],
    ascending=[True, True, False, False, False, False],
)

# 4) Pro (script, question_id) nur die erste (beste) Zeile behalten
df_best = df_sorted.drop_duplicates(subset=["script", "question_id"], keep="first")

C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\1181950045.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["correctness_rank"] = df["correctness_category"].map(category_rank).fillna(0).astype(int)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\1181950045.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["faithfulness_1to5"] = pd.to_numeric(df["faithfulness_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\1181950045.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["answer_relevance_1to5"] = pd.to_numeric(df["answer_relevance_1to5"], errors="coerce").fillna(-1)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_26924\1181950045.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["helpfulness_final_1to5"] = pd.to_numeric(df["helpfulness_final_1to5"], errors="coerce").fillna(-1)

In [83]:
check = df_best.groupby(["script", "question_id"]).size().value_counts()
print(check)
check2 = df_best2.groupby(["script", "question_id"]).size().value_counts()
print(check2)

1    190
Name: count, dtype: int64
1    190
Name: count, dtype: int64

In [ ]:
df_newest = df_new[df_new["script"] != "LLMGraph_Hybrid"]
df_newest2 = df_newest[df_newest["script"] != "SimpleKG_Hybrid"] 
df_newest3 = df_newest2[df_newest2["script"] != "SimpleKG_Hybrid_Rerank"] 

df_newest_combi = (
    pd.concat(
        [df_newest3,df_best3,df_best2, df_best ],
        axis=0
    )
    .drop_duplicates()
)
df_newest_combi=  df_newest_combi[df_newest_combi["query_type"] != "relational"]
df_newest_combi["script"] = df_newest_combi["script"].replace({
    "LlamaIndex_Dense_Community_Rerank": "LlamaIndex_Hybrid_Community"
})
df_newest_combi["script"] = df_newest_combi["script"].replace({
    "SimpleKG_Hybrid_Community_Rerank": "SimpleKG_Hybrid_Community"
})

In [91]:
df_newest_combi = df_newest_combi.drop_duplicates(
    subset=["script", "question_id"],
    keep="first"
)

In [85]:
check = df_best.groupby(["script", "question_id"]).size().value_counts()
print(check)

1    190
Name: count, dtype: int64

In [86]:
counts = (
    df_newest_combi.groupby(["script", "correctness_error_severity"])
      .size()
      .unstack(fill_value=0)
)
print(counts)

correctness_error_severity   high  low  medium
script
LLMGraph_Dense                  7  143      10
LLMGraph_Hybrid                14  141       5
LLMGraph_Hybrid_Community      10  143       7
LlamaIndex_Dense               12  139       9
LlamaIndex_Hybrid_Community     8  103       5
LlamaIndex_Hybrid_Rerank       12  136      12
RAG_Advanced_Dense             22  129       9
RAG_Advanced_Hybrid            15  131      14
RAG_Advanced_Sparse            13  133      16
RAG_Naive_Hybrid               16  141       3
SimpleKG_Dense                 17  137       8
SimpleKG_Hybrid                12  142       6
SimpleKG_Hybrid_Community       9  147       4
SimpleKG_Hybrid_Rerank         14  211       5

In [92]:
rows_per_script = df_newest_combi.groupby("script").size()
print(rows_per_script)

script
LLMGraph_Dense                 160
LLMGraph_Hybrid                160
LLMGraph_Hybrid_Community      160
LlamaIndex_Dense               160
LlamaIndex_Hybrid_Community    116
LlamaIndex_Hybrid_Rerank       160
RAG_Advanced_Dense             160
RAG_Advanced_Hybrid            160
RAG_Advanced_Sparse            160
RAG_Naive_Hybrid               160
SimpleKG_Dense                 160
SimpleKG_Hybrid                160
SimpleKG_Hybrid_Community      160
SimpleKG_Hybrid_Rerank         160
dtype: int64

In [93]:
counts = (
    df_newest_combi.groupby(["script", "correctness_category"])
      .size()
      .unstack(fill_value=0)
)

counts = counts.reindex(columns=["TP", "FP", "FN"], fill_value=0)

# nach Anzahl TP 
counts = counts.sort_values(by="TP", ascending=False)

print(counts)

correctness_category          TP  FP   FN
script
SimpleKG_Hybrid_Community    119   9   17
LLMGraph_Hybrid              118  12   11
SimpleKG_Hybrid_Rerank       115   9   13
SimpleKG_Hybrid              111  12   17
LLMGraph_Hybrid_Community    108  10   14
LlamaIndex_Hybrid_Rerank     104  12   14
RAG_Advanced_Sparse          102  12    8
SimpleKG_Dense               101  16   23
LLMGraph_Dense                99   7   22
RAG_Advanced_Hybrid           99  15   10
LlamaIndex_Hybrid_Community   76   7   20
LlamaIndex_Dense              73  10   46
RAG_Naive_Hybrid              16  16  104
RAG_Advanced_Dense             9  21  110

In [68]:
tp_counts = (
    df_newest_combi[df_newest_combi["correctness_category"] == "TP"]
        .groupby(["script", "query_type"])
        .size()
        .unstack(fill_value=0)
)

# optional: nach summary-TP sortieren
tp_counts = tp_counts.sort_values(by="factual", ascending=False)

print(tp_counts.to_string())

query_type                   disambiguation  factual  multi_hop  reasoning  summary
script
RAG_Advanced_Sparse                      23       28         18         19       16
RAG_Advanced_Hybrid                      22       27         16         20       14
LLMGraph_Hybrid                          21       20         24         24       29
SimpleKG_Hybrid                          23       20         27         22       19
LLMGraph_Hybrid_Community                19       20         21         21       27
LLMGraph_Dense                           20       19         18         22       20
SimpleKG_Hybrid_Community                21       19         25         25       29
SimpleKG_Hybrid_Rerank                   18       19         27         22       26
LlamaIndex_Hybrid_Rerank                 19       19         23         20       21
SimpleKG_Dense                           20       19         24         20       18
LlamaIndex_Hybrid_Community              14       18         13         15       16
LlamaIndex_Dense                         14       12         16         16       15
RAG_Naive_Hybrid                          4        1          7          3        1
RAG_Advanced_Dense                        1        1          2          2        3

In [69]:
tp_counts = (
    df_newest_combi[df_newest_combi["correctness_category"] == "TP"]
        .groupby(["script", "query_type"])
        .size()
        .unstack(fill_value=0)
)

# optional: nach summary-TP sortieren
tp_counts = tp_counts.sort_values(by="multi_hop", ascending=False)

print(tp_counts.to_string())

query_type                   disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid                          23       20         27         22       19
SimpleKG_Hybrid_Rerank                   18       19         27         22       26
SimpleKG_Hybrid_Community                21       19         25         25       29
SimpleKG_Dense                           20       19         24         20       18
LLMGraph_Hybrid                          21       20         24         24       29
LlamaIndex_Hybrid_Rerank                 19       19         23         20       21
LLMGraph_Hybrid_Community                19       20         21         21       27
RAG_Advanced_Sparse                      23       28         18         19       16
LLMGraph_Dense                           20       19         18         22       20
LlamaIndex_Dense                         14       12         16         16       15
RAG_Advanced_Hybrid                      22       27         16         20       14
LlamaIndex_Hybrid_Community              14       18         13         15       16
RAG_Naive_Hybrid                          4        1          7          3        1
RAG_Advanced_Dense                        1        1          2          2        3

In [70]:
tp_counts = (
    df_newest_combi[df_newest_combi["correctness_category"] == "TP"]
        .groupby(["script", "query_type"])
        .size()
        .unstack(fill_value=0)
)

# optional: nach summary-TP sortieren
tp_counts = tp_counts.sort_values(by="script", ascending=True)

print(tp_counts.to_string())

query_type                   disambiguation  factual  multi_hop  reasoning  summary
script
LLMGraph_Dense                           20       19         18         22       20
LLMGraph_Hybrid                          21       20         24         24       29
LLMGraph_Hybrid_Community                19       20         21         21       27
LlamaIndex_Dense                         14       12         16         16       15
LlamaIndex_Hybrid_Community              14       18         13         15       16
LlamaIndex_Hybrid_Rerank                 19       19         23         20       21
RAG_Advanced_Dense                        1        1          2          2        3
RAG_Advanced_Hybrid                      22       27         16         20       14
RAG_Advanced_Sparse                      23       28         18         19       16
RAG_Naive_Hybrid                          4        1          7          3        1
SimpleKG_Dense                           20       19         24         20       18
SimpleKG_Hybrid                          23       20         27         22       19
SimpleKG_Hybrid_Community                21       19         25         25       29
SimpleKG_Hybrid_Rerank                   18       19         27         22       26

In [94]:


cols = ["script",  "faithfulness_1to5", "answer_relevance_1to5","completeness_1to5","correctness_coverage_1to5" ,"helpfulness_final_1to5" ]
df_new_scores = df_newest_combi[cols].copy()



summary = (
    df_new_scores.groupby("script", as_index=False)
      .agg(
            Faithfulness=("faithfulness_1to5", "mean"),
            Answer_Relevance=("answer_relevance_1to5", "mean"),
            Completeness=("completeness_1to5", "mean"),
            Correctness=("correctness_coverage_1to5", "mean"),
            Helpfulness=("helpfulness_final_1to5", "mean"),
            )
)


summary_no_n = summary


summary_no_n = summary_no_n.set_index("script").round(2)

print(summary_no_n.to_string())

                             Faithfulness  Answer_Relevance  Completeness  Correctness  Helpfulness
script
LLMGraph_Dense                       4.64              3.71          2.74         3.85         4.51
LLMGraph_Hybrid                      4.03              3.79          2.99         4.12         4.31
LLMGraph_Hybrid_Community            3.84              3.70          3.02         4.02         4.22
LlamaIndex_Dense                     4.69              3.59          2.33         3.17         4.11
LlamaIndex_Hybrid_Community          4.66              3.66          2.95         3.84         4.47
LlamaIndex_Hybrid_Rerank             4.71              3.70          3.02         3.95         4.60
RAG_Advanced_Dense                   4.24              3.42          1.42         1.44         2.00
RAG_Advanced_Hybrid                  4.77              3.75          2.88         3.89         4.56
RAG_Advanced_Sparse                  4.79              3.78          2.95         3.94         4.63
RAG_Naive_Hybrid                     4.29              2.40          1.39         1.69         2.26
SimpleKG_Dense                       4.06              3.71          2.99         3.72         4.22
SimpleKG_Hybrid                      4.04              3.76          2.83         3.96         4.28
SimpleKG_Hybrid_Community            3.68              3.77          2.88         4.09         4.19
SimpleKG_Hybrid_Rerank               3.73              3.79          3.10         4.09         4.27

In [72]:
counts = (
    df_newest_combi.groupby(["script", "correctness_category"])
      .size()
      .unstack(fill_value=0)
)

counts = counts.reindex(columns=["TP", "FP", "FN"], fill_value=0)
final = counts.join(summary_no_n, how="left")
final = final.sort_values(by="script", ascending=True)
print(final.to_string())

                              TP  FP   FN  Faithfulness  Answer_Relevance  Completeness  Correctness  Helpfulness
script
LLMGraph_Dense                99   7   22          4.64              3.71          2.74         3.85         4.51
LLMGraph_Hybrid              118  12   11          4.03              3.79          2.99         4.12         4.31
LLMGraph_Hybrid_Community    108  10   14          3.84              3.70          3.02         4.02         4.22
LlamaIndex_Dense              73  10   46          4.69              3.59          2.33         3.17         4.11
LlamaIndex_Hybrid_Community   76   7   20          4.66              3.66          2.95         3.84         4.47
LlamaIndex_Hybrid_Rerank     102  11   14          4.70              3.71          3.03         3.96         4.60
RAG_Advanced_Dense             9  21  110          4.24              3.42          1.42         1.44         2.00
RAG_Advanced_Hybrid           99  15   10          4.77              3.75          2.88         3.89         4.56
RAG_Advanced_Sparse          104  12    8          4.79              3.78          2.96         3.95         4.64
RAG_Naive_Hybrid              16  16  104          4.29              2.40          1.39         1.69         2.26
SimpleKG_Dense               101  16   22          4.06              3.72          3.01         3.74         4.21
SimpleKG_Hybrid              111  12   17          4.04              3.76          2.83         3.96         4.28
SimpleKG_Hybrid_Community    119   9   17          3.68              3.77          2.88         4.09         4.19
SimpleKG_Hybrid_Rerank       112   8   15          3.67              3.81          3.10         4.04         4.22

In [95]:


cols = ["query_type",  "faithfulness_1to5", "answer_relevance_1to5","completeness_1to5","correctness_coverage_1to5" ,"helpfulness_final_1to5" ]
df_new_scores = df_newest_combi[cols].copy()



summary = (
    df_new_scores.groupby("query_type", as_index=False)
      .agg(
         Faithfulness=("faithfulness_1to5", "mean"),
            Answer_Relevance=("answer_relevance_1to5", "mean"),
            Completeness=("completeness_1to5", "mean"),
            Correctness=("correctness_coverage_1to5", "mean"),
            Helpfulness=("helpfulness_final_1to5", "mean"),
             )
)


summary_no_n = summary


summary_no_n = summary_no_n.set_index("query_type").round(2)

counts = (
    df_newest_combi.groupby(["query_type", "correctness_category"])
      .size()
      .unstack(fill_value=0)
)

counts = counts.reindex(columns=["TP", "FP", "FN"], fill_value=0)
final = counts.join(summary_no_n, how="left")
final = final.sort_values(by="query_type", ascending=True)
print(final.to_string())

                 TP  FP   FN  Faithfulness  Answer_Relevance  Completeness  Correctness  Helpfulness
query_type
disambiguation  239  56   72          4.38              3.63          2.73         3.55         4.17
factual         240  11  138          4.52              3.73          2.96         3.41         3.74
multi_hop       262  13   45          4.18              3.56          2.79         3.94         4.19
reasoning       252  31   73          4.08              3.50          2.52         3.61         4.06
summary         257  57  101          4.29              3.62          2.45         3.32         4.04

In [74]:
summary_by_query_type = (
    df_newest_combi
        .groupby("query_type", as_index=False)
        .agg(
        Faithfulness=("faithfulness_1to5", "mean"),
            Answer_Relevance=("answer_relevance_1to5", "mean"),
            Completeness=("completeness_1to5", "mean"),
            Correctness=("correctness_coverage_1to5", "mean"),
            Helpfulness=("helpfulness_final_1to5", "mean"),
            # N=("query_type", "size"),
        )
        .set_index("query_type")
        .round(2)
)


print(summary_by_query_type.to_string())

                Faithfulness  Answer_Relevance  Completeness  Correctness  Helpfulness
query_type
disambiguation          4.38              3.63          2.73         3.55         4.17
factual                 4.52              3.73          2.96         3.42         3.75
multi_hop               4.17              3.56          2.79         3.94         4.18
reasoning               4.08              3.50          2.52         3.61         4.05
summary                 4.28              3.63          2.44         3.31         4.03

In [96]:
summary_by_script_and_query = (
    df_newest_combi 
        .groupby(["script", "query_type"], as_index=False)
        .agg(
            Faithfulness=("faithfulness_1to5", "mean"),
            Answer_Relevance=("answer_relevance_1to5", "mean"),
            Completeness=("completeness_1to5", "mean"),
            Correctness=("correctness_coverage_1to5", "mean"),
            Helpfulness=("helpfulness_final_1to5", "mean"),
            
        )
        .set_index(["script", "query_type"])
        .round(2)
)

counts = (
    df_newest_combi.groupby(["query_type", "script" ,"correctness_category"])
      .size()
      .unstack(fill_value=0)
)

counts = counts.reindex(columns=["TP", "FP", "FN"], fill_value=0)
final = counts.join(summary_no_n, how="left")
final = final.sort_values(by="query_type", ascending=True)
print(final.to_string())

                                            TP  FP  FN  Faithfulness  Answer_Relevance  Completeness  Correctness  Helpfulness
query_type     script
disambiguation LLMGraph_Dense               20   3   4          4.38              3.63          2.73         3.55         4.17
               SimpleKG_Hybrid_Rerank       18   4   4          4.38              3.63          2.73         3.55         4.17
               SimpleKG_Hybrid_Community    21   5   2          4.38              3.63          2.73         3.55         4.17
               SimpleKG_Hybrid              23   4   2          4.38              3.63          2.73         3.55         4.17
               RAG_Naive_Hybrid              4   4  19          4.38              3.63          2.73         3.55         4.17
               RAG_Advanced_Sparse          23   1   1          4.38              3.63          2.73         3.55         4.17
               RAG_Advanced_Hybrid          22   4   1          4.38              3.63          2.73         3.55         4.17
               SimpleKG_Dense               20   2   4          4.38              3.63          2.73         3.55         4.17
               LlamaIndex_Hybrid_Rerank     19   5   2          4.38              3.63          2.73         3.55         4.17
               LlamaIndex_Hybrid_Community  14   2   2          4.38              3.63          2.73         3.55         4.17
               LlamaIndex_Dense             14   4   7          4.38              3.63          2.73         3.55         4.17
               LLMGraph_Hybrid_Community    19   4   3          4.38              3.63          2.73         3.55         4.17
               LLMGraph_Hybrid              21   6   2          4.38              3.63          2.73         3.55         4.17
               RAG_Advanced_Dense            1   8  19          4.38              3.63          2.73         3.55         4.17
factual        RAG_Advanced_Sparse          26   0   1          4.52              3.73          2.96         3.41         3.74
               SimpleKG_Hybrid_Rerank       19   2   5          4.52              3.73          2.96         3.41         3.74
               SimpleKG_Hybrid_Community    19   0   8          4.52              3.73          2.96         3.41         3.74
               SimpleKG_Hybrid              20   1   7          4.52              3.73          2.96         3.41         3.74
               SimpleKG_Dense               19   1   7          4.52              3.73          2.96         3.41         3.74
               RAG_Naive_Hybrid              1   0  29          4.52              3.73          2.96         3.41         3.74
               RAG_Advanced_Hybrid          27   0   1          4.52              3.73          2.96         3.41         3.74
               LlamaIndex_Dense             12   0  17          4.52              3.73          2.96         3.41         3.74
               LlamaIndex_Hybrid_Rerank     19   2   7          4.52              3.73          2.96         3.41         3.74
               LlamaIndex_Hybrid_Community  18   2   7          4.52              3.73          2.96         3.41         3.74
               LLMGraph_Hybrid_Community    20   1   6          4.52              3.73          2.96         3.41         3.74
               LLMGraph_Hybrid              20   2   6          4.52              3.73          2.96         3.41         3.74
               LLMGraph_Dense               19   0   8          4.52              3.73          2.96         3.41         3.74
               RAG_Advanced_Dense            1   0  29          4.52              3.73          2.96         3.41         3.74
multi_hop      RAG_Advanced_Sparse          18   1   1          4.18              3.56          2.79         3.94         4.19
               SimpleKG_Hybrid_Rerank       28   0   0          4.18              3.56          2.79         3.94         4.19
               SimpleKG_Hybrid_Community    25   2   2          4.18              3.56          2.79         3.94         4.19
               SimpleKG_Hybrid              27   0   1          4.18              3.56          2.79         3.94         4.19
               SimpleKG_Dense               24   1   2          4.18              3.56          2.79         3.94         4.19
               RAG_Naive_Hybrid              7   1  12          4.18              3.56          2.79         3.94         4.19
               RAG_Advanced_Hybrid          16   2   2          4.18              3.56          2.79         3.94         4.19
               RAG_Advanced_Dense            2   1  19          4.18              3.56          2.79         3.94         4.19
               LlamaIndex_Hybrid_Rerank     23   0   0          4.18              3.56          2.79         3.94         4.19
               LlamaIndex_Hybrid_Community  13   0   0          4.18              3.56          2.79         3.94         4.19
               LlamaIndex_Dense             16   2   3          4.18              3.56          2.79         3.94         4.19
               LLMGraph_Hybrid_Community    21   1   2          4.18              3.56          2.79         3.94         4.19
               LLMGraph_Hybrid              24   1   0          4.18              3.56          2.79         3.94         4.19
               LLMGraph_Dense               18   1   1          4.18              3.56          2.79         3.94         4.19
reasoning      SimpleKG_Hybrid_Rerank       22   0   3          4.08              3.50          2.52         3.61         4.06
               SimpleKG_Hybrid_Community    25   2   1          4.08              3.50          2.52         3.61         4.06
               SimpleKG_Hybrid              22   2   4          4.08              3.50          2.52         3.61         4.06
               RAG_Naive_Hybrid              3   6  15          4.08              3.50          2.52         3.61         4.06
               RAG_Advanced_Sparse          19   2   3          4.08              3.50          2.52         3.61         4.06
               RAG_Advanced_Hybrid          20   4   2          4.08              3.50          2.52         3.61         4.06
               SimpleKG_Dense               20   3   3          4.08              3.50          2.52         3.61         4.06
               LlamaIndex_Hybrid_Rerank     21   2   4          4.08              3.50          2.52         3.61         4.06
               LlamaIndex_Hybrid_Community  15   1   5          4.08              3.50          2.52         3.61         4.06
               LlamaIndex_Dense             16   2   7          4.08              3.50          2.52         3.61         4.06
               LLMGraph_Hybrid_Community    21   1   1          4.08              3.50          2.52         3.61         4.06
               LLMGraph_Hybrid              24   2   2          4.08              3.50          2.52         3.61         4.06
               LLMGraph_Dense               22   0   3          4.08              3.50          2.52         3.61         4.06
               RAG_Advanced_Dense            2   4  20          4.08              3.50          2.52         3.61         4.06
summary        SimpleKG_Hybrid              19   5   3          4.29              3.62          2.45         3.32         4.04
               SimpleKG_Dense               18   9   7          4.29              3.62          2.45         3.32         4.04
               RAG_Naive_Hybrid              1   5  29          4.29              3.62          2.45         3.32         4.04
               RAG_Advanced_Sparse          16   8   2          4.29              3.62          2.45         3.32         4.04
               RAG_Advanced_Hybrid          14   5   4          4.29              3.62          2.45         3.32         4.04
               RAG_Advanced_Dense            3   8  23          4.29              3.62          2.45         3.32         4.04
               LlamaIndex_Dense             15   2  12          4.29              3.62          2.45         3.32         4.04
               LlamaIndex_Hybrid_Community  16   2   6          4.29              3.62          2.45         3.32         4.04
               LLMGraph_Hybrid_Community    27   3   2          4.29              3.62          2.45         3.32         4.04
               LLMGraph_Hybrid              29   1   1          4.29              3.62          2.45         3.32         4.04
               LLMGraph_Dense               20   3   6          4.29              3.62          2.45         3.32         4.04
               SimpleKG_Hybrid_Community    29   0   4          4.29              3.62          2.45         3.32         4.04
               LlamaIndex_Hybrid_Rerank     22   3   1          4.29              3.62          2.45         3.32         4.04
               SimpleKG_Hybrid_Rerank       28   3   1          4.29              3.62          2.45         3.32         4.04

In [97]:
summary_by_script_and_query = (
    df_newest_combi 
        .groupby(["script", "query_type"], as_index=False)
        .agg(
            Faithfulness=("faithfulness_1to5", "mean"),
            Answer_Relevance=("answer_relevance_1to5", "mean"),
            Completeness=("completeness_1to5", "mean"),
            Correctness=("correctness_coverage_1to5", "mean"),
            Helpfulness=("helpfulness_final_1to5", "mean"),
            
        )
        .set_index(["script", "query_type"])
        .round(2)
)

print(summary_by_script_and_query.to_string())

                                            Faithfulness  Answer_Relevance  Completeness  Correctness  Helpfulness
script                      query_type
LLMGraph_Dense              disambiguation          4.70              3.63          2.53         3.87         4.53
                            factual                 4.50              3.87          3.13         3.73         3.87
                            multi_hop               4.77              3.67          2.90         4.03         4.73
                            reasoning               4.57              3.57          2.60         4.13         4.77
                            summary                 4.68              3.80          2.60         3.58         4.62
LLMGraph_Hybrid             disambiguation          4.03              3.73          2.80         3.93         4.27
                            factual                 4.60              4.13          3.50         3.80         4.33
                            multi_hop               3.60              3.67          2.77         4.37         4.27
                            reasoning               4.00              3.57          3.00         4.23         4.27
                            summary                 3.92              3.85          2.92         4.22         4.40
LLMGraph_Hybrid_Community   disambiguation          3.87              3.60          3.43         3.87         4.23
                            factual                 4.30              3.87          3.57         3.87         4.20
                            multi_hop               3.83              3.53          2.77         4.20         4.33
                            reasoning               3.60              3.73          2.90         4.10         4.20
                            summary                 3.68              3.75          2.60         4.05         4.15
LlamaIndex_Dense            disambiguation          4.50              3.83          2.43         3.17         4.30
                            factual                 4.67              3.43          2.37         2.67         3.27
                            multi_hop               4.83              3.67          2.33         3.70         4.53
                            reasoning               4.60              3.43          2.23         3.30         4.27
                            summary                 4.82              3.60          2.30         3.05         4.18
LlamaIndex_Hybrid_Community disambiguation          4.90              3.67          3.19         4.05         4.71
                            factual                 4.70              3.80          3.00         3.60         4.17
                            multi_hop               4.87              3.47          3.40         4.73         4.87
                            reasoning               4.35              3.30          2.61         3.65         4.35
                            summary                 4.59              3.93          2.74         3.59         4.52
LlamaIndex_Hybrid_Rerank    disambiguation          4.87              3.57          2.77         3.80         4.77
                            factual                 4.77              3.97          3.47         3.67         4.07
                            multi_hop               4.80              3.73          3.30         4.43         4.90
                            reasoning               4.37              3.50          2.90         4.00         4.60
                            summary                 4.72              3.72          2.78         3.88         4.65
RAG_Advanced_Dense          disambiguation          4.17              3.33          1.30         1.27         2.17
                            factual                 4.30              3.37          1.13         1.13         1.17
                            multi_hop               4.00              3.43          1.60         1.77         2.13
                            reasoning               4.03              3.43          1.37         1.43         2.27
                            summary                 4.58              3.50          1.65         1.55         2.20
RAG_Advanced_Hybrid         disambiguation          4.93              3.80          3.23         4.13         4.80
                            factual                 4.90              4.00          3.23         4.67         4.67
                            multi_hop               4.50              3.57          3.07         3.67         4.40
                            reasoning               4.77              3.77          2.50         3.97         4.53
                            summary                 4.75              3.65          2.50         3.22         4.45
RAG_Advanced_Sparse         disambiguation          4.90              3.73          3.07         4.30         4.70
                            factual                 4.90              4.03          3.60         4.60         4.87
                            multi_hop               4.70              3.53          2.97         4.00         4.53
                            reasoning               4.53              3.80          2.50         3.70         4.33
                            summary                 4.90              3.78          2.70         3.30         4.70
RAG_Naive_Hybrid            disambiguation          4.40              2.53          1.57         1.67         2.57
                            factual                 4.50              1.67          1.03         1.13         1.23
                            multi_hop               4.00              2.97          1.60         2.63         3.00
                            reasoning               3.87              2.60          1.37         1.77         2.57
                            summary                 4.58              2.28          1.40         1.38         2.00
SimpleKG_Dense              disambiguation          4.07              3.77          3.13         4.00         4.33
                            factual                 4.37              3.80          3.40         3.67         4.07
                            multi_hop               4.07              3.67          3.17         4.23         4.33
                            reasoning               3.77              3.67          2.93         3.93         4.23
                            summary                 4.05              3.68          2.50         3.02         4.15
SimpleKG_Hybrid             disambiguation          4.33              3.87          3.00         4.10         4.57
                            factual                 4.53              4.07          3.20         3.77         4.20
                            multi_hop               3.87              3.70          3.17         4.63         4.37
                            reasoning               3.80              3.43          2.60         3.93         4.10
                            summary                 3.78              3.75          2.35         3.50         4.20
SimpleKG_Hybrid_Community   disambiguation          3.90              3.90          2.90         3.97         4.30
                            factual                 4.17              4.03          3.30         3.67         4.10
                            multi_hop               3.43              3.57          3.07         4.37         4.17
                            reasoning               3.47              3.57          2.70         4.30         4.20
                            summary                 3.50              3.78          2.52         4.15         4.18
SimpleKG_Hybrid_Rerank      disambiguation          3.90              3.83          2.97         3.73         4.23
                            factual                 4.07              4.17          3.53         3.80         4.20
                            multi_hop               3.63              3.63          3.27         4.80         4.40
                            reasoning               3.50              3.60          3.07         4.03         4.17
                            summary                 3.60              3.75          2.78         4.08         4.32

In [104]:
final
pivot_help = (
    final
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="TP"
        )
        .round(2)
)

# nach der Spalte "summary" sortieren (absteigend)
pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                   disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                   18       19         28         22       28
SimpleKG_Hybrid_Community                21       19         25         25       29
SimpleKG_Hybrid                          23       20         27         22       19
SimpleKG_Dense                           20       19         24         20       18
RAG_Naive_Hybrid                          4        1          7          3        1
RAG_Advanced_Sparse                      23       26         18         19       16
RAG_Advanced_Hybrid                      22       27         16         20       14
RAG_Advanced_Dense                        1        1          2          2        3
LlamaIndex_Hybrid_Rerank                 19       19         23         21       22
LlamaIndex_Hybrid_Community              14       18         13         15       16
LlamaIndex_Dense                         14       12         16         16       15
LLMGraph_Hybrid_Community                19       20         21         21       27
LLMGraph_Hybrid                          21       20         24         24       29
LLMGraph_Dense                           20       19         18         22       20

In [103]:
final
pivot_help = (
    final
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="Helpfulness"
        )
        .round(2)
)

# nach der Spalte "summary" sortieren (absteigend)
pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                   disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                 4.17     3.74       4.19       4.06     4.04
SimpleKG_Hybrid_Community              4.17     3.74       4.19       4.06     4.04
SimpleKG_Hybrid                        4.17     3.74       4.19       4.06     4.04
SimpleKG_Dense                         4.17     3.74       4.19       4.06     4.04
RAG_Naive_Hybrid                       4.17     3.74       4.19       4.06     4.04
RAG_Advanced_Sparse                    4.17     3.74       4.19       4.06     4.04
RAG_Advanced_Hybrid                    4.17     3.74       4.19       4.06     4.04
RAG_Advanced_Dense                     4.17     3.74       4.19       4.06     4.04
LlamaIndex_Hybrid_Rerank               4.17     3.74       4.19       4.06     4.04
LlamaIndex_Hybrid_Community            4.17     3.74       4.19       4.06     4.04
LlamaIndex_Dense                       4.17     3.74       4.19       4.06     4.04
LLMGraph_Hybrid_Community              4.17     3.74       4.19       4.06     4.04
LLMGraph_Hybrid                        4.17     3.74       4.19       4.06     4.04
LLMGraph_Dense                         4.17     3.74       4.19       4.06     4.04

In [99]:
pivot_help = (
    summary_by_script_and_query
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="Answer_Relevance"
        )
        .round(2)
)

# nach der Spalte "summary" sortieren (absteigend)
pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                   disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                 3.83     4.17       3.63       3.60     3.75
SimpleKG_Hybrid_Community              3.90     4.03       3.57       3.57     3.78
SimpleKG_Hybrid                        3.87     4.07       3.70       3.43     3.75
SimpleKG_Dense                         3.77     3.80       3.67       3.67     3.68
RAG_Naive_Hybrid                       2.53     1.67       2.97       2.60     2.28
RAG_Advanced_Sparse                    3.73     4.03       3.53       3.80     3.78
RAG_Advanced_Hybrid                    3.80     4.00       3.57       3.77     3.65
RAG_Advanced_Dense                     3.33     3.37       3.43       3.43     3.50
LlamaIndex_Hybrid_Rerank               3.57     3.97       3.73       3.50     3.72
LlamaIndex_Hybrid_Community            3.67     3.80       3.47       3.30     3.93
LlamaIndex_Dense                       3.83     3.43       3.67       3.43     3.60
LLMGraph_Hybrid_Community              3.60     3.87       3.53       3.73     3.75
LLMGraph_Hybrid                        3.73     4.13       3.67       3.57     3.85
LLMGraph_Dense                         3.63     3.87       3.67       3.57     3.80

In [102]:
pivot_help = (
    summary_by_script_and_query
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="Faithfulness"
        )
        .round(2)
)


pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                   disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                 3.90     4.07       3.63       3.50     3.60
SimpleKG_Hybrid_Community              3.90     4.17       3.43       3.47     3.50
SimpleKG_Hybrid                        4.33     4.53       3.87       3.80     3.78
SimpleKG_Dense                         4.07     4.37       4.07       3.77     4.05
RAG_Naive_Hybrid                       4.40     4.50       4.00       3.87     4.58
RAG_Advanced_Sparse                    4.90     4.90       4.70       4.53     4.90
RAG_Advanced_Hybrid                    4.93     4.90       4.50       4.77     4.75
RAG_Advanced_Dense                     4.17     4.30       4.00       4.03     4.58
LlamaIndex_Hybrid_Rerank               4.87     4.77       4.80       4.37     4.72
LlamaIndex_Hybrid_Community            4.90     4.70       4.87       4.35     4.59
LlamaIndex_Dense                       4.50     4.67       4.83       4.60     4.82
LLMGraph_Hybrid_Community              3.87     4.30       3.83       3.60     3.68
LLMGraph_Hybrid                        4.03     4.60       3.60       4.00     3.92
LLMGraph_Dense                         4.70     4.50       4.77       4.57     4.68

In [101]:
pivot_help = (
    summary_by_script_and_query
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="Completeness"
        )
        .round(2)
)


pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                   disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                 2.97     3.53       3.27       3.07     2.78
SimpleKG_Hybrid_Community              2.90     3.30       3.07       2.70     2.52
SimpleKG_Hybrid                        3.00     3.20       3.17       2.60     2.35
SimpleKG_Dense                         3.13     3.40       3.17       2.93     2.50
RAG_Naive_Hybrid                       1.57     1.03       1.60       1.37     1.40
RAG_Advanced_Sparse                    3.07     3.60       2.97       2.50     2.70
RAG_Advanced_Hybrid                    3.23     3.23       3.07       2.50     2.50
RAG_Advanced_Dense                     1.30     1.13       1.60       1.37     1.65
LlamaIndex_Hybrid_Rerank               2.77     3.47       3.30       2.90     2.78
LlamaIndex_Hybrid_Community            3.19     3.00       3.40       2.61     2.74
LlamaIndex_Dense                       2.43     2.37       2.33       2.23     2.30
LLMGraph_Hybrid_Community              3.43     3.57       2.77       2.90     2.60
LLMGraph_Hybrid                        2.80     3.50       2.77       3.00     2.92
LLMGraph_Dense                         2.53     3.13       2.90       2.60     2.60

In [82]:
pivot_help = (
    summary_by_script_and_query
        .reset_index()
        .pivot(
            index="script",
            columns="query_type",
            values="Completeness"
        )
        .round(2)
)


pivot_help = pivot_help.sort_values(by="script", ascending=False)

print(pivot_help.to_string())

query_type                   disambiguation  factual  multi_hop  reasoning  summary
script
SimpleKG_Hybrid_Rerank                 2.97     3.53       3.30       3.07     2.75
SimpleKG_Hybrid_Community              2.90     3.30       3.07       2.70     2.52
SimpleKG_Hybrid                        3.00     3.20       3.17       2.60     2.35
SimpleKG_Dense                         3.13     3.40       3.17       2.93     2.54
RAG_Naive_Hybrid                       1.57     1.03       1.60       1.37     1.40
RAG_Advanced_Sparse                    3.07     3.59       2.97       2.50     2.70
RAG_Advanced_Hybrid                    3.23     3.23       3.07       2.50     2.50
RAG_Advanced_Dense                     1.30     1.13       1.60       1.37     1.65
LlamaIndex_Hybrid_Rerank               2.77     3.47       3.30       2.93     2.74
LlamaIndex_Hybrid_Community            3.19     3.00       3.40       2.61     2.74
LlamaIndex_Dense                       2.43     2.37       2.33       2.23     2.30
LLMGraph_Hybrid_Community              3.43     3.57       2.77       2.90     2.60
LLMGraph_Hybrid                        2.80     3.50       2.77       3.00     2.92
LLMGraph_Dense                         2.53     3.13       2.90       2.60     2.60

In [106]:
import pandas as pd

# 1) Ensure both have the SAME MultiIndex order: (script, query_type)
summary_metrics = summary_by_script_and_query.copy()  # index: (script, query_type)

counts_fixed = (
    counts.copy()
         .reorder_levels(["script", "query_type"])  # was (query_type, script) -> (script, query_type)
         .sort_index()
)

# 2) Join metrics + counts into one table
summary_all = summary_metrics.join(counts_fixed, how="left").fillna(0)

# Optional: make TP/FP/FN integers (after fillna)
for col in ["TP", "FP", "FN"]:
    if col in summary_all.columns:
        summary_all[col] = summary_all[col].astype(int)

summary_all.head(1)

,,Faithfulness,Answer_Relevance,Completeness,Correctness,Helpfulness,TP,FP,FN
script,query_type,,,,,,,,
LLMGraph_Dense,disambiguation,4.7,3.63,2.53,3.87,4.53,20,3,4

In [108]:
summary_only = summary_all.xs("multi_hop", level="query_type")
summary_only

,Faithfulness,Answer_Relevance,Completeness,Correctness,Helpfulness,TP,FP,FN
script,,,,,,,,
LLMGraph_Dense,4.77,3.67,2.90,4.03,4.73,18,1,1
LLMGraph_Hybrid,3.60,3.67,2.77,4.37,4.27,24,1,0
LLMGraph_Hybrid_Community,3.83,3.53,2.77,4.20,4.33,21,1,2
LlamaIndex_Dense,4.83,3.67,2.33,3.70,4.53,16,2,3
LlamaIndex_Hybrid_Community,4.87,3.47,3.40,4.73,4.87,13,0,0
LlamaIndex_Hybrid_Rerank,4.80,3.73,3.30,4.43,4.90,23,0,0
RAG_Advanced_Dense,4.00,3.43,1.60,1.77,2.13,2,1,19
RAG_Advanced_Hybrid,4.50,3.57,3.07,3.67,4.40,16,2,2
RAG_Advanced_Sparse,4.70,3.53,2.97,4.00,4.53,18,1,1
RAG_Naive_Hybrid,4.00,2.97,1.60,2.63,3.00,7,1,12
SimpleKG_Dense,4.07,3.67,3.17,4.23,4.33,24,1,2
SimpleKG_Hybrid,3.87,3.70,3.17,4.63,4.37,27,0,1
SimpleKG_Hybrid_Community,3.43,3.57,3.07,4.37,4.17,25,2,2
SimpleKG_Hybrid_Rerank,3.50,3.67,3.30,4.73,4.33,27,0,0

In [ ]:
summary_only = summary_all.xs("summary", level="query_type")
summary_only

,Faithfulness,Answer_Relevance,Completeness,Correctness,Helpfulness,TP,FP,FN
script,,,,,,,,
LLMGraph_Dense,4.68,3.80,2.60,3.58,4.62,20,3,6
LLMGraph_Hybrid,3.92,3.85,2.92,4.22,4.40,29,1,1
LLMGraph_Hybrid_Community,3.68,3.75,2.60,4.05,4.15,27,3,2
LlamaIndex_Dense,4.82,3.60,2.30,3.05,4.18,15,2,12
LlamaIndex_Hybrid_Community,4.59,3.93,2.74,3.59,4.52,16,2,6
LlamaIndex_Hybrid_Rerank,4.72,3.74,2.74,3.85,4.67,21,3,1
RAG_Advanced_Dense,4.58,3.50,1.65,1.55,2.20,3,8,23
RAG_Advanced_Hybrid,4.75,3.65,2.50,3.22,4.45,14,5,4
RAG_Advanced_Sparse,4.90,3.78,2.70,3.30,4.70,16,8,2
RAG_Naive_Hybrid,4.58,2.28,1.40,1.38,2.00,1,5,29
SimpleKG_Dense,4.03,3.67,2.54,3.08,4.18,18,9,6
SimpleKG_Hybrid,3.78,3.75,2.35,3.50,4.20,19,5,3
SimpleKG_Hybrid_Community,3.50,3.78,2.52,4.15,4.18,29,0,4
SimpleKG_Hybrid_Rerank,3.45,3.80,2.75,3.92,4.18,26,2,3

In [112]:
rows_per_script = df_newest_combi.groupby("script").size()
print(rows_per_script)

script
LLMGraph_Dense                 160
LLMGraph_Hybrid                160
LLMGraph_Hybrid_Community      160
LlamaIndex_Dense               160
LlamaIndex_Hybrid_Community    116
LlamaIndex_Hybrid_Rerank       157
RAG_Advanced_Dense             160
RAG_Advanced_Hybrid            160
RAG_Advanced_Sparse            160
RAG_Naive_Hybrid               160
SimpleKG_Dense                 159
SimpleKG_Hybrid                160
SimpleKG_Hybrid_Community      160
SimpleKG_Hybrid_Rerank         160
dtype: int64

In [ ]:
df_newest_combi

In [111]:
df_newest_combi = df_newest_combi.drop_duplicates(
    subset=["script", "question_id"],
    keep="first"
)

In [127]:
dups = df_newest_combi[
    (df_newest_combi["script"] == "RAG_Advanced_Sparse") &
    (df_newest_combi.duplicated(subset=["question_id"], keep=False))
]

In [138]:
df_newest_combi[
    (df_newest_combi["script"] == "SimpleKG_Dense") &
    (df_newest_combi["question_id"].isin([42, 58, 70]))
]

,script,question_id,query_type,answer_relevance_score,answer_relevance_1to5,completeness_score,completeness_1to5,correctness_category,correctness_coverage,correctness_coverage_1to5,correctness_error_severity,faithfulness_score,faithfulness_1to5,helpfulness_raw_1to5,helpfulness_raw_score,helpfulness_final_score,helpfulness_final_1to5,helpfulness_justification,metrics_json,correctness_rank
71,SimpleKG_Dense,42,reasoning,0.529677,3,0.00,1,FP,0.0,1,high,0.95,5,5,1.0,0.9750,5,The answer directly addresses the question by ...,"{""answer_relevance"": {""score"": 0.5296768546104...",NaN
87,SimpleKG_Dense,58,reasoning,0.701175,4,0.75,4,TP,1.0,5,low,0.95,5,3,0.5,0.4875,3,The answer correctly identifies the voltage li...,"{""answer_relevance"": {""score"": 0.7011746168136...",NaN

In [ ]:
df_new_llamaindex = df_newest_combi[df_newest_combi["script"].isin(["SimpleKG_Dense"])]
df_new_llamaindex.groupby("script").size()

script
LlamaIndex_Hybrid_Rerank    157
dtype: int64

In [129]:
df_new_llamaindex2 = df_newest_combi[df_newest_combi["script"].isin(["SimpleKG_Dense"])]
df_new_llamaindex2.groupby("script").size()

script
SimpleKG_Dense    159
dtype: int64

In [130]:
OUTPUT_PATH = PROJECT_ROOT / "main" / "evaluation" / "evaluation_datasets" / "golden_answers_dataset_llmaindex_missing.jsonl"

In [104]:
df_only_not_in_llamaindex.to_json(OUTPUT_PATH, orient="records", lines=True, force_ascii=False)

In [131]:
# ---------------------------------------------------------------------------
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())
PROJECT_ROOT = Path(os.getenv("PROJECT_ROOT")).expanduser().resolve()

QUESTIONS_PATH = (
    PROJECT_ROOT
    / "main"
    / "evaluation"
    / "evaluation_datasets"
    / "golden_answers_dataset.jsonl"
)
QUESTIONS_PATH

WindowsPath('C:/Users/Nasiba/Documents/1 Master Data Science/Master Thesis/VS Code New/master_thesis-rag/main/evaluation/evaluation_datasets/golden_answers_dataset.jsonl')

In [132]:
# Load
df = pd.read_json(QUESTIONS_PATH, lines=True)
df = df[df["query_type"]!= "relational"]
df.head(2)

,id,query_type,question,gold_answer
0,1,factual,What is the pressure measurement range of the ...,The LPS22HB measures absolute pressure from 26...
1,2,factual,What is the humidity measurement range of the ...,The HS3003 measures relative humidity from 0% ...

In [133]:
df["question_id"] = df["id"].astype(str)
df_new_llamaindex["question_id"] = df_new_llamaindex["question_id"].astype(str)
df_new_llamaindex2["question_id"] = df_new_llamaindex2["question_id"].astype(str)

C:\Users\Nasiba\AppData\Local\Temp\ipykernel_25248\2468996886.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_llamaindex["question_id"] = df_new_llamaindex["question_id"].astype(str)
C:\Users\Nasiba\AppData\Local\Temp\ipykernel_25248\2468996886.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new_llamaindex2["question_id"] = df_new_llamaindex2["question_id"].astype(str)

In [134]:
df_only_not_in_llamaindex = df[
    ~df["question_id"].isin(df_new_llamaindex["question_id"])
]
df_only_not_in_llamaindex

,id,query_type,question,gold_answer,question_id
41,42,reasoning,Which board is better suited for edge AI execu...,"The Nicla Sense ME, because the BHI260 can run...",42
57,58,reasoning,Can a 5-volt sensor be connected directly to t...,"No, because the Due operates at 3.3 V and its ...",58
69,70,summary,Compare the AI-related capabilities of the Nan...,The Nano family includes no specialized AI har...,70

In [114]:
from openai import OpenAI
client = OpenAI()

emb = client.embeddings.create(
    model="text-embedding-3-small",  # falls du 1536 nutzt (typisch)
    input="secure communication and control systems"
).data[0].embedding

print(len(emb))  # muss 1536 sein
print(emb)  # zum checken

1536

In [115]:
from neo4j import GraphDatabase
import os

URI = os.getenv("NEO4J_URI")
AUTH = (os.getenv("NEO4J_USER"), os.getenv("NEO4J_PASSWORD"))
DATABASE = "llmakg"

cypher = """
CALL db.index.vector.queryNodes('community_vec', $k, $embedding)
YIELD node, score
WHERE node.level = 1
RETURN node.communityId AS communityId, score
ORDER BY score DESC
LIMIT $k
"""

with GraphDatabase.driver(URI, auth=AUTH) as driver:
    res = driver.execute_query(
        cypher,
        k=5,
        embedding=emb,   # <- deine 1536er Liste aus OpenAI
        database_=DATABASE
    )
    print(res.records)

[<Record communityId=669 score=0.6668701171875>, <Record communityId=667 score=0.6599116325378418>, <Record communityId=194 score=0.6440299153327942>, <Record communityId=606 score=0.6380442976951599>, <Record communityId=535 score=0.6374026536941528>]